-- SQL Logging Session
-- Session ID: b115da68-1ce3-4d22-a6ff-5dbc4f8bb810
-- Started: 2026-07-25T23:14:44.691Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_a48f347e UNIQUEIDENTIFIER,
@Code_a48f347e NVARCHAR(40),
@Name_a48f347e NVARCHAR(200),
@Description_a48f347e NVARCHAR(MAX),
@DriverClass_a48f347e NVARCHAR(200),
@IsDeferred_a48f347e BIT,
@RequiresServicePeriod_a48f347e BIT,
@Sequence_a48f347e INT,
@IsActive_a48f347e BIT
SET
  @ID_a48f347e = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F01'
SET
  @Code_a48f347e = N'UpFront'
SET
  @Name_a48f347e = N'Up Front'
SET
  @Description_a48f347e = N'100% recognized when the order is booked. One-time goods and services — the booking entry credits Sales directly, with no deferral round-trip.'
SET
  @DriverClass_a48f347e = N'UpFront'
SET
  @IsDeferred_a48f347e = 0
SET
  @RequiresServicePeriod_a48f347e = 0
SET
  @Sequence_a48f347e = 10
SET
  @IsActive_a48f347e = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_a48f347e,
  @Code = @Code_a48f347e,
  @Name = @Name_a48f347e,
  @Description = @Description_a48f347e,
  @DriverClass = @DriverClass_a48f347e,
  @IsDeferred = @IsDeferred_a48f347e,
  @RequiresServicePeriod = @RequiresServicePeriod_a48f347e,
  @Sequence = @Sequence_a48f347e,
  @IsActive = @IsActive_a48f347e;

GO

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_9f5299a4 UNIQUEIDENTIFIER,
@Code_9f5299a4 NVARCHAR(40),
@Name_9f5299a4 NVARCHAR(200),
@Description_9f5299a4 NVARCHAR(MAX),
@DriverClass_9f5299a4 NVARCHAR(200),
@IsDeferred_9f5299a4 BIT,
@RequiresServicePeriod_9f5299a4 BIT,
@Sequence_9f5299a4 INT,
@IsActive_9f5299a4 BIT
SET
  @ID_9f5299a4 = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F02'
SET
  @Code_9f5299a4 = N'EvenOverTime'
SET
  @Name_9f5299a4 = N'Even Over Time (Straight Line)'
SET
  @Description_9f5299a4 = N'Straight-line across the line''s service period — most subscriptions. A 12-month $1,200 line books to Deferred Revenue and releases 12 dated $100 entries. Rounding remainder is front-loaded into the first period.'
SET
  @DriverClass_9f5299a4 = N'EvenOverTime'
SET
  @IsDeferred_9f5299a4 = 1
SET
  @RequiresServicePeriod_9f5299a4 = 1
SET
  @Sequence_9f5299a4 = 20
SET
  @IsActive_9f5299a4 = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_9f5299a4,
  @Code = @Code_9f5299a4,
  @Name = @Name_9f5299a4,
  @Description = @Description_9f5299a4,
  @DriverClass = @DriverClass_9f5299a4,
  @IsDeferred = @IsDeferred_9f5299a4,
  @RequiresServicePeriod = @RequiresServicePeriod_9f5299a4,
  @Sequence = @Sequence_9f5299a4,
  @IsActive = @IsActive_9f5299a4;

GO

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_43aa6d4a UNIQUEIDENTIFIER,
@Code_43aa6d4a NVARCHAR(40),
@Name_43aa6d4a NVARCHAR(200),
@Description_43aa6d4a NVARCHAR(MAX),
@DriverClass_43aa6d4a NVARCHAR(200),
@IsDeferred_43aa6d4a BIT,
@RequiresServicePeriod_43aa6d4a BIT,
@Sequence_43aa6d4a INT,
@IsActive_43aa6d4a BIT
SET
  @ID_43aa6d4a = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F03'
SET
  @Code_43aa6d4a = N'AllBackEnd'
SET
  @Name_43aa6d4a = N'All Back End (On Completion)'
SET
  @Description_43aa6d4a = N'100% recognized on the service period END date — events and milestone deliverables, where nothing is earned until delivery. Cash sits in Deferred Revenue until the event date.'
SET
  @DriverClass_43aa6d4a = N'AllBackEnd'
SET
  @IsDeferred_43aa6d4a = 1
SET
  @RequiresServicePeriod_43aa6d4a = 1
SET
  @Sequence_43aa6d4a = 30
SET
  @IsActive_43aa6d4a = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_43aa6d4a,
  @Code = @Code_43aa6d4a,
  @Name = @Name_43aa6d4a,
  @Description = @Description_43aa6d4a,
  @DriverClass = @DriverClass_43aa6d4a,
  @IsDeferred = @IsDeferred_43aa6d4a,
  @RequiresServicePeriod = @RequiresServicePeriod_43aa6d4a,
  @Sequence = @Sequence_43aa6d4a,
  @IsActive = @IsActive_43aa6d4a;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_a3b5fc96 UNIQUEIDENTIFIER,
@Code_a3b5fc96 NVARCHAR(40),
@Name_a3b5fc96 NVARCHAR(200),
@Description_a3b5fc96 NVARCHAR(MAX),
@DriverClass_a3b5fc96 NVARCHAR(200),
@SupportsTokenization_a3b5fc96 BIT,
@SupportsRefund_a3b5fc96 BIT,
@SupportsWebhooks_a3b5fc96 BIT,
@Sequence_a3b5fc96 INT,
@IsActive_a3b5fc96 BIT
SET
  @ID_a3b5fc96 = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C01'
SET
  @Code_a3b5fc96 = N'Stripe'
SET
  @Name_a3b5fc96 = N'Stripe'
SET
  @Description_a3b5fc96 = N'Stripe payments — cards, wallets, hosted checkout.'
SET
  @DriverClass_a3b5fc96 = N'StripePaymentProvider'
SET
  @SupportsTokenization_a3b5fc96 = 1
SET
  @SupportsRefund_a3b5fc96 = 1
SET
  @SupportsWebhooks_a3b5fc96 = 1
SET
  @Sequence_a3b5fc96 = 10
SET
  @IsActive_a3b5fc96 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_a3b5fc96,
  @Code = @Code_a3b5fc96,
  @Name = @Name_a3b5fc96,
  @Description = @Description_a3b5fc96,
  @DriverClass = @DriverClass_a3b5fc96,
  @SupportsTokenization = @SupportsTokenization_a3b5fc96,
  @SupportsRefund = @SupportsRefund_a3b5fc96,
  @SupportsWebhooks = @SupportsWebhooks_a3b5fc96,
  @Sequence = @Sequence_a3b5fc96,
  @IsActive = @IsActive_a3b5fc96;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_52406bda UNIQUEIDENTIFIER,
@Code_52406bda NVARCHAR(40),
@Name_52406bda NVARCHAR(200),
@Description_52406bda NVARCHAR(MAX),
@DriverClass_52406bda NVARCHAR(200),
@SupportsTokenization_52406bda BIT,
@SupportsRefund_52406bda BIT,
@SupportsWebhooks_52406bda BIT,
@Sequence_52406bda INT,
@IsActive_52406bda BIT
SET
  @ID_52406bda = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C02'
SET
  @Code_52406bda = N'Manual'
SET
  @Name_52406bda = N'Manual'
SET
  @Description_52406bda = N'Finance records the money movement by hand (check, wire, cash). Always available.'
SET
  @DriverClass_52406bda = N'ManualPaymentProvider'
SET
  @SupportsTokenization_52406bda = 0
SET
  @SupportsRefund_52406bda = 1
SET
  @SupportsWebhooks_52406bda = 0
SET
  @Sequence_52406bda = 20
SET
  @IsActive_52406bda = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_52406bda,
  @Code = @Code_52406bda,
  @Name = @Name_52406bda,
  @Description = @Description_52406bda,
  @DriverClass = @DriverClass_52406bda,
  @SupportsTokenization = @SupportsTokenization_52406bda,
  @SupportsRefund = @SupportsRefund_52406bda,
  @SupportsWebhooks = @SupportsWebhooks_52406bda,
  @Sequence = @Sequence_52406bda,
  @IsActive = @IsActive_52406bda;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_70aca528 UNIQUEIDENTIFIER,
@Code_70aca528 NVARCHAR(40),
@Name_70aca528 NVARCHAR(200),
@Description_70aca528 NVARCHAR(MAX),
@IsReversal_70aca528 BIT,
@RequiresProvider_70aca528 BIT,
@RequiresInstrument_70aca528 BIT,
@RequiresReference_70aca528 BIT,
@DetailExtensionEntity_70aca528 NVARCHAR(255),
@Sequence_70aca528 INT,
@IsActive_70aca528 BIT
SET
  @ID_70aca528 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E01'
SET
  @Code_70aca528 = N'CreditCard'
SET
  @Name_70aca528 = N'Credit Card'
SET
  @Description_70aca528 = N'Card payment through a gateway; the instrument is a provider token, never a PAN.'
SET
  @IsReversal_70aca528 = 0
SET
  @RequiresProvider_70aca528 = 1
SET
  @RequiresInstrument_70aca528 = 1
SET
  @RequiresReference_70aca528 = 0
SET
  @Sequence_70aca528 = 10
SET
  @IsActive_70aca528 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_70aca528,
  @Code = @Code_70aca528,
  @Name = @Name_70aca528,
  @Description = @Description_70aca528,
  @IsReversal = @IsReversal_70aca528,
  @RequiresProvider = @RequiresProvider_70aca528,
  @RequiresInstrument = @RequiresInstrument_70aca528,
  @RequiresReference = @RequiresReference_70aca528,
  @DetailExtensionEntity = @DetailExtensionEntity_70aca528,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_70aca528,
  @IsActive = @IsActive_70aca528;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_2b45398c UNIQUEIDENTIFIER,
@Code_2b45398c NVARCHAR(40),
@Name_2b45398c NVARCHAR(200),
@Description_2b45398c NVARCHAR(MAX),
@IsReversal_2b45398c BIT,
@RequiresProvider_2b45398c BIT,
@RequiresInstrument_2b45398c BIT,
@RequiresReference_2b45398c BIT,
@DetailExtensionEntity_2b45398c NVARCHAR(255),
@Sequence_2b45398c INT,
@IsActive_2b45398c BIT
SET
  @ID_2b45398c = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E02'
SET
  @Code_2b45398c = N'ACH'
SET
  @Name_2b45398c = N'ACH / Bank Transfer'
SET
  @Description_2b45398c = N'Bank debit through a gateway; instrument carries routing/account last-4 only.'
SET
  @IsReversal_2b45398c = 0
SET
  @RequiresProvider_2b45398c = 1
SET
  @RequiresInstrument_2b45398c = 1
SET
  @RequiresReference_2b45398c = 0
SET
  @Sequence_2b45398c = 20
SET
  @IsActive_2b45398c = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_2b45398c,
  @Code = @Code_2b45398c,
  @Name = @Name_2b45398c,
  @Description = @Description_2b45398c,
  @IsReversal = @IsReversal_2b45398c,
  @RequiresProvider = @RequiresProvider_2b45398c,
  @RequiresInstrument = @RequiresInstrument_2b45398c,
  @RequiresReference = @RequiresReference_2b45398c,
  @DetailExtensionEntity = @DetailExtensionEntity_2b45398c,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_2b45398c,
  @IsActive = @IsActive_2b45398c;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_da529e0a UNIQUEIDENTIFIER,
@Code_da529e0a NVARCHAR(40),
@Name_da529e0a NVARCHAR(200),
@Description_da529e0a NVARCHAR(MAX),
@IsReversal_da529e0a BIT,
@RequiresProvider_da529e0a BIT,
@RequiresInstrument_da529e0a BIT,
@RequiresReference_da529e0a BIT,
@DetailExtensionEntity_da529e0a NVARCHAR(255),
@Sequence_da529e0a INT,
@IsActive_da529e0a BIT
SET
  @ID_da529e0a = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E03'
SET
  @Code_da529e0a = N'Wire'
SET
  @Name_da529e0a = N'Wire Transfer'
SET
  @Description_da529e0a = N'Wire received; the confirmation number is captured as the instrument reference.'
SET
  @IsReversal_da529e0a = 0
SET
  @RequiresProvider_da529e0a = 0
SET
  @RequiresInstrument_da529e0a = 0
SET
  @RequiresReference_da529e0a = 1
SET
  @Sequence_da529e0a = 30
SET
  @IsActive_da529e0a = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_da529e0a,
  @Code = @Code_da529e0a,
  @Name = @Name_da529e0a,
  @Description = @Description_da529e0a,
  @IsReversal = @IsReversal_da529e0a,
  @RequiresProvider = @RequiresProvider_da529e0a,
  @RequiresInstrument = @RequiresInstrument_da529e0a,
  @RequiresReference = @RequiresReference_da529e0a,
  @DetailExtensionEntity = @DetailExtensionEntity_da529e0a,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_da529e0a,
  @IsActive = @IsActive_da529e0a;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_a3399b92 UNIQUEIDENTIFIER,
@Code_a3399b92 NVARCHAR(40),
@Name_a3399b92 NVARCHAR(200),
@Description_a3399b92 NVARCHAR(MAX),
@IsReversal_a3399b92 BIT,
@RequiresProvider_a3399b92 BIT,
@RequiresInstrument_a3399b92 BIT,
@RequiresReference_a3399b92 BIT,
@DetailExtensionEntity_a3399b92 NVARCHAR(255),
@Sequence_a3399b92 INT,
@IsActive_a3399b92 BIT
SET
  @ID_a3399b92 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E04'
SET
  @Code_a3399b92 = N'Check'
SET
  @Name_a3399b92 = N'Check'
SET
  @Description_a3399b92 = N'Paper check; the check number is captured as the instrument reference.'
SET
  @IsReversal_a3399b92 = 0
SET
  @RequiresProvider_a3399b92 = 0
SET
  @RequiresInstrument_a3399b92 = 1
SET
  @RequiresReference_a3399b92 = 1
SET
  @Sequence_a3399b92 = 40
SET
  @IsActive_a3399b92 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_a3399b92,
  @Code = @Code_a3399b92,
  @Name = @Name_a3399b92,
  @Description = @Description_a3399b92,
  @IsReversal = @IsReversal_a3399b92,
  @RequiresProvider = @RequiresProvider_a3399b92,
  @RequiresInstrument = @RequiresInstrument_a3399b92,
  @RequiresReference = @RequiresReference_a3399b92,
  @DetailExtensionEntity = @DetailExtensionEntity_a3399b92,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_a3399b92,
  @IsActive = @IsActive_a3399b92;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_e1e2e14b UNIQUEIDENTIFIER,
@Code_e1e2e14b NVARCHAR(40),
@Name_e1e2e14b NVARCHAR(200),
@Description_e1e2e14b NVARCHAR(MAX),
@IsReversal_e1e2e14b BIT,
@RequiresProvider_e1e2e14b BIT,
@RequiresInstrument_e1e2e14b BIT,
@RequiresReference_e1e2e14b BIT,
@DetailExtensionEntity_e1e2e14b NVARCHAR(255),
@Sequence_e1e2e14b INT,
@IsActive_e1e2e14b BIT
SET
  @ID_e1e2e14b = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E05'
SET
  @Code_e1e2e14b = N'Cash'
SET
  @Name_e1e2e14b = N'Cash'
SET
  @Description_e1e2e14b = N'Cash received. No instrument, no reference.'
SET
  @IsReversal_e1e2e14b = 0
SET
  @RequiresProvider_e1e2e14b = 0
SET
  @RequiresInstrument_e1e2e14b = 0
SET
  @RequiresReference_e1e2e14b = 0
SET
  @Sequence_e1e2e14b = 50
SET
  @IsActive_e1e2e14b = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_e1e2e14b,
  @Code = @Code_e1e2e14b,
  @Name = @Name_e1e2e14b,
  @Description = @Description_e1e2e14b,
  @IsReversal = @IsReversal_e1e2e14b,
  @RequiresProvider = @RequiresProvider_e1e2e14b,
  @RequiresInstrument = @RequiresInstrument_e1e2e14b,
  @RequiresReference = @RequiresReference_e1e2e14b,
  @DetailExtensionEntity = @DetailExtensionEntity_e1e2e14b,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_e1e2e14b,
  @IsActive = @IsActive_e1e2e14b;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_11e7e462 UNIQUEIDENTIFIER,
@Code_11e7e462 NVARCHAR(40),
@Name_11e7e462 NVARCHAR(200),
@Description_11e7e462 NVARCHAR(MAX),
@IsReversal_11e7e462 BIT,
@RequiresProvider_11e7e462 BIT,
@RequiresInstrument_11e7e462 BIT,
@RequiresReference_11e7e462 BIT,
@DetailExtensionEntity_11e7e462 NVARCHAR(255),
@Sequence_11e7e462 INT,
@IsActive_11e7e462 BIT
SET
  @ID_11e7e462 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E06'
SET
  @Code_11e7e462 = N'InternalTransfer'
SET
  @Name_11e7e462 = N'Internal Transfer'
SET
  @Description_11e7e462 = N'Movement between our own companies or accounts; reference identifies the transfer.'
SET
  @IsReversal_11e7e462 = 0
SET
  @RequiresProvider_11e7e462 = 0
SET
  @RequiresInstrument_11e7e462 = 0
SET
  @RequiresReference_11e7e462 = 1
SET
  @Sequence_11e7e462 = 60
SET
  @IsActive_11e7e462 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_11e7e462,
  @Code = @Code_11e7e462,
  @Name = @Name_11e7e462,
  @Description = @Description_11e7e462,
  @IsReversal = @IsReversal_11e7e462,
  @RequiresProvider = @RequiresProvider_11e7e462,
  @RequiresInstrument = @RequiresInstrument_11e7e462,
  @RequiresReference = @RequiresReference_11e7e462,
  @DetailExtensionEntity = @DetailExtensionEntity_11e7e462,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_11e7e462,
  @IsActive = @IsActive_11e7e462;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_36005227 UNIQUEIDENTIFIER,
@Code_36005227 NVARCHAR(40),
@Name_36005227 NVARCHAR(200),
@Description_36005227 NVARCHAR(MAX),
@IsReversal_36005227 BIT,
@RequiresProvider_36005227 BIT,
@RequiresInstrument_36005227 BIT,
@RequiresReference_36005227 BIT,
@DetailExtensionEntity_36005227 NVARCHAR(255),
@Sequence_36005227 INT,
@IsActive_36005227 BIT
SET
  @ID_36005227 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E07'
SET
  @Code_36005227 = N'GiftCard'
SET
  @Name_36005227 = N'Gift Card / Stored Value'
SET
  @Description_36005227 = N'Redemption against a StoredValueAccount; books liability relief, not revenue.'
SET
  @IsReversal_36005227 = 0
SET
  @RequiresProvider_36005227 = 0
SET
  @RequiresInstrument_36005227 = 1
SET
  @RequiresReference_36005227 = 0
SET
  @Sequence_36005227 = 70
SET
  @IsActive_36005227 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_36005227,
  @Code = @Code_36005227,
  @Name = @Name_36005227,
  @Description = @Description_36005227,
  @IsReversal = @IsReversal_36005227,
  @RequiresProvider = @RequiresProvider_36005227,
  @RequiresInstrument = @RequiresInstrument_36005227,
  @RequiresReference = @RequiresReference_36005227,
  @DetailExtensionEntity = @DetailExtensionEntity_36005227,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_36005227,
  @IsActive = @IsActive_36005227;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_0b63cde3 UNIQUEIDENTIFIER,
@Code_0b63cde3 NVARCHAR(40),
@Name_0b63cde3 NVARCHAR(200),
@Description_0b63cde3 NVARCHAR(MAX),
@IsReversal_0b63cde3 BIT,
@RequiresProvider_0b63cde3 BIT,
@RequiresInstrument_0b63cde3 BIT,
@RequiresReference_0b63cde3 BIT,
@DetailExtensionEntity_0b63cde3 NVARCHAR(255),
@Sequence_0b63cde3 INT,
@IsActive_0b63cde3 BIT
SET
  @ID_0b63cde3 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E08'
SET
  @Code_0b63cde3 = N'Refund'
SET
  @Name_0b63cde3 = N'Refund'
SET
  @Description_0b63cde3 = N'REVERSAL — money returned to the customer. Never offered as an initial payment.'
SET
  @IsReversal_0b63cde3 = 1
SET
  @RequiresProvider_0b63cde3 = 0
SET
  @RequiresInstrument_0b63cde3 = 0
SET
  @RequiresReference_0b63cde3 = 0
SET
  @Sequence_0b63cde3 = 80
SET
  @IsActive_0b63cde3 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_0b63cde3,
  @Code = @Code_0b63cde3,
  @Name = @Name_0b63cde3,
  @Description = @Description_0b63cde3,
  @IsReversal = @IsReversal_0b63cde3,
  @RequiresProvider = @RequiresProvider_0b63cde3,
  @RequiresInstrument = @RequiresInstrument_0b63cde3,
  @RequiresReference = @RequiresReference_0b63cde3,
  @DetailExtensionEntity = @DetailExtensionEntity_0b63cde3,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_0b63cde3,
  @IsActive = @IsActive_0b63cde3;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_43aa11a3 UNIQUEIDENTIFIER,
@Code_43aa11a3 NVARCHAR(40),
@Name_43aa11a3 NVARCHAR(200),
@Description_43aa11a3 NVARCHAR(MAX),
@IsReversal_43aa11a3 BIT,
@RequiresProvider_43aa11a3 BIT,
@RequiresInstrument_43aa11a3 BIT,
@RequiresReference_43aa11a3 BIT,
@DetailExtensionEntity_43aa11a3 NVARCHAR(255),
@Sequence_43aa11a3 INT,
@IsActive_43aa11a3 BIT
SET
  @ID_43aa11a3 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E09'
SET
  @Code_43aa11a3 = N'Chargeback'
SET
  @Name_43aa11a3 = N'Chargeback'
SET
  @Description_43aa11a3 = N'REVERSAL — funds pulled back by the card network. Never an initial payment.'
SET
  @IsReversal_43aa11a3 = 1
SET
  @RequiresProvider_43aa11a3 = 0
SET
  @RequiresInstrument_43aa11a3 = 0
SET
  @RequiresReference_43aa11a3 = 0
SET
  @Sequence_43aa11a3 = 90
SET
  @IsActive_43aa11a3 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_43aa11a3,
  @Code = @Code_43aa11a3,
  @Name = @Name_43aa11a3,
  @Description = @Description_43aa11a3,
  @IsReversal = @IsReversal_43aa11a3,
  @RequiresProvider = @RequiresProvider_43aa11a3,
  @RequiresInstrument = @RequiresInstrument_43aa11a3,
  @RequiresReference = @RequiresReference_43aa11a3,
  @DetailExtensionEntity = @DetailExtensionEntity_43aa11a3,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_43aa11a3,
  @IsActive = @IsActive_43aa11a3;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_0d94f960 UNIQUEIDENTIFIER,
@Code_0d94f960 NVARCHAR(40),
@Name_0d94f960 NVARCHAR(200),
@Description_0d94f960 NVARCHAR(MAX),
@IsReversal_0d94f960 BIT,
@RequiresProvider_0d94f960 BIT,
@RequiresInstrument_0d94f960 BIT,
@RequiresReference_0d94f960 BIT,
@DetailExtensionEntity_0d94f960 NVARCHAR(255),
@Sequence_0d94f960 INT,
@IsActive_0d94f960 BIT
SET
  @ID_0d94f960 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E0A'
SET
  @Code_0d94f960 = N'BankReturn'
SET
  @Name_0d94f960 = N'Bank Return'
SET
  @Description_0d94f960 = N'REVERSAL — bank returned the debit (NSF etc.). Never an initial payment.'
SET
  @IsReversal_0d94f960 = 1
SET
  @RequiresProvider_0d94f960 = 0
SET
  @RequiresInstrument_0d94f960 = 0
SET
  @RequiresReference_0d94f960 = 0
SET
  @Sequence_0d94f960 = 100
SET
  @IsActive_0d94f960 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_0d94f960,
  @Code = @Code_0d94f960,
  @Name = @Name_0d94f960,
  @Description = @Description_0d94f960,
  @IsReversal = @IsReversal_0d94f960,
  @RequiresProvider = @RequiresProvider_0d94f960,
  @RequiresInstrument = @RequiresInstrument_0d94f960,
  @RequiresReference = @RequiresReference_0d94f960,
  @DetailExtensionEntity = @DetailExtensionEntity_0d94f960,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_0d94f960,
  @IsActive = @IsActive_0d94f960;

GO


-- End of SQL Logging Session
-- Session ID: b115da68-1ce3-4d22-a6ff-5dbc4f8bb810
-- Completed: 2026-07-25T23:14:45.541Z
-- Duration: 850ms
-- Total Statements: 15
