-- SQL Logging Session
-- Session ID: 2ca31dfc-490c-40dc-a21a-28e14a409684
-- Started: 2026-07-25T19:11:09.374Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_bc654724 UNIQUEIDENTIFIER,
@Code_bc654724 NVARCHAR(40),
@Name_bc654724 NVARCHAR(200),
@Description_bc654724 NVARCHAR(MAX),
@DriverClass_bc654724 NVARCHAR(200),
@IsDeferred_bc654724 BIT,
@RequiresServicePeriod_bc654724 BIT,
@Sequence_bc654724 INT,
@IsActive_bc654724 BIT
SET
  @ID_bc654724 = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F01'
SET
  @Code_bc654724 = N'UpFront'
SET
  @Name_bc654724 = N'Up Front'
SET
  @Description_bc654724 = N'100% recognized when the order is booked. One-time goods and services — the booking entry credits Sales directly, with no deferral round-trip.'
SET
  @DriverClass_bc654724 = N'UpFront'
SET
  @IsDeferred_bc654724 = 0
SET
  @RequiresServicePeriod_bc654724 = 0
SET
  @Sequence_bc654724 = 10
SET
  @IsActive_bc654724 = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_bc654724,
  @Code = @Code_bc654724,
  @Name = @Name_bc654724,
  @Description = @Description_bc654724,
  @DriverClass = @DriverClass_bc654724,
  @IsDeferred = @IsDeferred_bc654724,
  @RequiresServicePeriod = @RequiresServicePeriod_bc654724,
  @Sequence = @Sequence_bc654724,
  @IsActive = @IsActive_bc654724;

GO

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_3a4f69c0 UNIQUEIDENTIFIER,
@Code_3a4f69c0 NVARCHAR(40),
@Name_3a4f69c0 NVARCHAR(200),
@Description_3a4f69c0 NVARCHAR(MAX),
@DriverClass_3a4f69c0 NVARCHAR(200),
@IsDeferred_3a4f69c0 BIT,
@RequiresServicePeriod_3a4f69c0 BIT,
@Sequence_3a4f69c0 INT,
@IsActive_3a4f69c0 BIT
SET
  @ID_3a4f69c0 = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F02'
SET
  @Code_3a4f69c0 = N'EvenOverTime'
SET
  @Name_3a4f69c0 = N'Even Over Time (Straight Line)'
SET
  @Description_3a4f69c0 = N'Straight-line across the line''s service period — most subscriptions. A 12-month $1,200 line books to Deferred Revenue and releases 12 dated $100 entries. Rounding remainder is front-loaded into the first period.'
SET
  @DriverClass_3a4f69c0 = N'EvenOverTime'
SET
  @IsDeferred_3a4f69c0 = 1
SET
  @RequiresServicePeriod_3a4f69c0 = 1
SET
  @Sequence_3a4f69c0 = 20
SET
  @IsActive_3a4f69c0 = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_3a4f69c0,
  @Code = @Code_3a4f69c0,
  @Name = @Name_3a4f69c0,
  @Description = @Description_3a4f69c0,
  @DriverClass = @DriverClass_3a4f69c0,
  @IsDeferred = @IsDeferred_3a4f69c0,
  @RequiresServicePeriod = @RequiresServicePeriod_3a4f69c0,
  @Sequence = @Sequence_3a4f69c0,
  @IsActive = @IsActive_3a4f69c0;

GO

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_131c6505 UNIQUEIDENTIFIER,
@Code_131c6505 NVARCHAR(40),
@Name_131c6505 NVARCHAR(200),
@Description_131c6505 NVARCHAR(MAX),
@DriverClass_131c6505 NVARCHAR(200),
@IsDeferred_131c6505 BIT,
@RequiresServicePeriod_131c6505 BIT,
@Sequence_131c6505 INT,
@IsActive_131c6505 BIT
SET
  @ID_131c6505 = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F03'
SET
  @Code_131c6505 = N'AllBackEnd'
SET
  @Name_131c6505 = N'All Back End (On Completion)'
SET
  @Description_131c6505 = N'100% recognized on the service period END date — events and milestone deliverables, where nothing is earned until delivery. Cash sits in Deferred Revenue until the event date.'
SET
  @DriverClass_131c6505 = N'AllBackEnd'
SET
  @IsDeferred_131c6505 = 1
SET
  @RequiresServicePeriod_131c6505 = 1
SET
  @Sequence_131c6505 = 30
SET
  @IsActive_131c6505 = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_131c6505,
  @Code = @Code_131c6505,
  @Name = @Name_131c6505,
  @Description = @Description_131c6505,
  @DriverClass = @DriverClass_131c6505,
  @IsDeferred = @IsDeferred_131c6505,
  @RequiresServicePeriod = @RequiresServicePeriod_131c6505,
  @Sequence = @Sequence_131c6505,
  @IsActive = @IsActive_131c6505;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_a3a7c6e7 UNIQUEIDENTIFIER,
@Code_a3a7c6e7 NVARCHAR(40),
@Name_a3a7c6e7 NVARCHAR(200),
@Description_a3a7c6e7 NVARCHAR(MAX),
@DriverClass_a3a7c6e7 NVARCHAR(200),
@SupportsTokenization_a3a7c6e7 BIT,
@SupportsRefund_a3a7c6e7 BIT,
@SupportsWebhooks_a3a7c6e7 BIT,
@Sequence_a3a7c6e7 INT,
@IsActive_a3a7c6e7 BIT
SET
  @ID_a3a7c6e7 = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C01'
SET
  @Code_a3a7c6e7 = N'Stripe'
SET
  @Name_a3a7c6e7 = N'Stripe'
SET
  @Description_a3a7c6e7 = N'Stripe payments — cards, wallets, hosted checkout.'
SET
  @DriverClass_a3a7c6e7 = N'StripePaymentProvider'
SET
  @SupportsTokenization_a3a7c6e7 = 1
SET
  @SupportsRefund_a3a7c6e7 = 1
SET
  @SupportsWebhooks_a3a7c6e7 = 1
SET
  @Sequence_a3a7c6e7 = 10
SET
  @IsActive_a3a7c6e7 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_a3a7c6e7,
  @Code = @Code_a3a7c6e7,
  @Name = @Name_a3a7c6e7,
  @Description = @Description_a3a7c6e7,
  @DriverClass = @DriverClass_a3a7c6e7,
  @SupportsTokenization = @SupportsTokenization_a3a7c6e7,
  @SupportsRefund = @SupportsRefund_a3a7c6e7,
  @SupportsWebhooks = @SupportsWebhooks_a3a7c6e7,
  @Sequence = @Sequence_a3a7c6e7,
  @IsActive = @IsActive_a3a7c6e7;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_10c29188 UNIQUEIDENTIFIER,
@Code_10c29188 NVARCHAR(40),
@Name_10c29188 NVARCHAR(200),
@Description_10c29188 NVARCHAR(MAX),
@DriverClass_10c29188 NVARCHAR(200),
@SupportsTokenization_10c29188 BIT,
@SupportsRefund_10c29188 BIT,
@SupportsWebhooks_10c29188 BIT,
@Sequence_10c29188 INT,
@IsActive_10c29188 BIT
SET
  @ID_10c29188 = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C02'
SET
  @Code_10c29188 = N'Manual'
SET
  @Name_10c29188 = N'Manual'
SET
  @Description_10c29188 = N'Finance records the money movement by hand (check, wire, cash). Always available.'
SET
  @DriverClass_10c29188 = N'ManualPaymentProvider'
SET
  @SupportsTokenization_10c29188 = 0
SET
  @SupportsRefund_10c29188 = 1
SET
  @SupportsWebhooks_10c29188 = 0
SET
  @Sequence_10c29188 = 20
SET
  @IsActive_10c29188 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_10c29188,
  @Code = @Code_10c29188,
  @Name = @Name_10c29188,
  @Description = @Description_10c29188,
  @DriverClass = @DriverClass_10c29188,
  @SupportsTokenization = @SupportsTokenization_10c29188,
  @SupportsRefund = @SupportsRefund_10c29188,
  @SupportsWebhooks = @SupportsWebhooks_10c29188,
  @Sequence = @Sequence_10c29188,
  @IsActive = @IsActive_10c29188;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_d2367e5f UNIQUEIDENTIFIER,
@Code_d2367e5f NVARCHAR(40),
@Name_d2367e5f NVARCHAR(200),
@Description_d2367e5f NVARCHAR(MAX),
@IsReversal_d2367e5f BIT,
@RequiresProvider_d2367e5f BIT,
@RequiresInstrument_d2367e5f BIT,
@RequiresReference_d2367e5f BIT,
@DetailExtensionEntity_d2367e5f NVARCHAR(255),
@Sequence_d2367e5f INT,
@IsActive_d2367e5f BIT
SET
  @ID_d2367e5f = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E01'
SET
  @Code_d2367e5f = N'CreditCard'
SET
  @Name_d2367e5f = N'Credit Card'
SET
  @Description_d2367e5f = N'Card payment through a gateway; the instrument is a provider token, never a PAN.'
SET
  @IsReversal_d2367e5f = 0
SET
  @RequiresProvider_d2367e5f = 1
SET
  @RequiresInstrument_d2367e5f = 1
SET
  @RequiresReference_d2367e5f = 0
SET
  @Sequence_d2367e5f = 10
SET
  @IsActive_d2367e5f = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_d2367e5f,
  @Code = @Code_d2367e5f,
  @Name = @Name_d2367e5f,
  @Description = @Description_d2367e5f,
  @IsReversal = @IsReversal_d2367e5f,
  @RequiresProvider = @RequiresProvider_d2367e5f,
  @RequiresInstrument = @RequiresInstrument_d2367e5f,
  @RequiresReference = @RequiresReference_d2367e5f,
  @DetailExtensionEntity = @DetailExtensionEntity_d2367e5f,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_d2367e5f,
  @IsActive = @IsActive_d2367e5f;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_e0db6e71 UNIQUEIDENTIFIER,
@Code_e0db6e71 NVARCHAR(40),
@Name_e0db6e71 NVARCHAR(200),
@Description_e0db6e71 NVARCHAR(MAX),
@IsReversal_e0db6e71 BIT,
@RequiresProvider_e0db6e71 BIT,
@RequiresInstrument_e0db6e71 BIT,
@RequiresReference_e0db6e71 BIT,
@DetailExtensionEntity_e0db6e71 NVARCHAR(255),
@Sequence_e0db6e71 INT,
@IsActive_e0db6e71 BIT
SET
  @ID_e0db6e71 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E02'
SET
  @Code_e0db6e71 = N'ACH'
SET
  @Name_e0db6e71 = N'ACH / Bank Transfer'
SET
  @Description_e0db6e71 = N'Bank debit through a gateway; instrument carries routing/account last-4 only.'
SET
  @IsReversal_e0db6e71 = 0
SET
  @RequiresProvider_e0db6e71 = 1
SET
  @RequiresInstrument_e0db6e71 = 1
SET
  @RequiresReference_e0db6e71 = 0
SET
  @Sequence_e0db6e71 = 20
SET
  @IsActive_e0db6e71 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_e0db6e71,
  @Code = @Code_e0db6e71,
  @Name = @Name_e0db6e71,
  @Description = @Description_e0db6e71,
  @IsReversal = @IsReversal_e0db6e71,
  @RequiresProvider = @RequiresProvider_e0db6e71,
  @RequiresInstrument = @RequiresInstrument_e0db6e71,
  @RequiresReference = @RequiresReference_e0db6e71,
  @DetailExtensionEntity = @DetailExtensionEntity_e0db6e71,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_e0db6e71,
  @IsActive = @IsActive_e0db6e71;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_ec586bd5 UNIQUEIDENTIFIER,
@Code_ec586bd5 NVARCHAR(40),
@Name_ec586bd5 NVARCHAR(200),
@Description_ec586bd5 NVARCHAR(MAX),
@IsReversal_ec586bd5 BIT,
@RequiresProvider_ec586bd5 BIT,
@RequiresInstrument_ec586bd5 BIT,
@RequiresReference_ec586bd5 BIT,
@DetailExtensionEntity_ec586bd5 NVARCHAR(255),
@Sequence_ec586bd5 INT,
@IsActive_ec586bd5 BIT
SET
  @ID_ec586bd5 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E03'
SET
  @Code_ec586bd5 = N'Wire'
SET
  @Name_ec586bd5 = N'Wire Transfer'
SET
  @Description_ec586bd5 = N'Wire received; the confirmation number is captured as the instrument reference.'
SET
  @IsReversal_ec586bd5 = 0
SET
  @RequiresProvider_ec586bd5 = 0
SET
  @RequiresInstrument_ec586bd5 = 0
SET
  @RequiresReference_ec586bd5 = 1
SET
  @Sequence_ec586bd5 = 30
SET
  @IsActive_ec586bd5 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_ec586bd5,
  @Code = @Code_ec586bd5,
  @Name = @Name_ec586bd5,
  @Description = @Description_ec586bd5,
  @IsReversal = @IsReversal_ec586bd5,
  @RequiresProvider = @RequiresProvider_ec586bd5,
  @RequiresInstrument = @RequiresInstrument_ec586bd5,
  @RequiresReference = @RequiresReference_ec586bd5,
  @DetailExtensionEntity = @DetailExtensionEntity_ec586bd5,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_ec586bd5,
  @IsActive = @IsActive_ec586bd5;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_e965774a UNIQUEIDENTIFIER,
@Code_e965774a NVARCHAR(40),
@Name_e965774a NVARCHAR(200),
@Description_e965774a NVARCHAR(MAX),
@IsReversal_e965774a BIT,
@RequiresProvider_e965774a BIT,
@RequiresInstrument_e965774a BIT,
@RequiresReference_e965774a BIT,
@DetailExtensionEntity_e965774a NVARCHAR(255),
@Sequence_e965774a INT,
@IsActive_e965774a BIT
SET
  @ID_e965774a = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E04'
SET
  @Code_e965774a = N'Check'
SET
  @Name_e965774a = N'Check'
SET
  @Description_e965774a = N'Paper check; the check number is captured as the instrument reference.'
SET
  @IsReversal_e965774a = 0
SET
  @RequiresProvider_e965774a = 0
SET
  @RequiresInstrument_e965774a = 1
SET
  @RequiresReference_e965774a = 1
SET
  @Sequence_e965774a = 40
SET
  @IsActive_e965774a = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_e965774a,
  @Code = @Code_e965774a,
  @Name = @Name_e965774a,
  @Description = @Description_e965774a,
  @IsReversal = @IsReversal_e965774a,
  @RequiresProvider = @RequiresProvider_e965774a,
  @RequiresInstrument = @RequiresInstrument_e965774a,
  @RequiresReference = @RequiresReference_e965774a,
  @DetailExtensionEntity = @DetailExtensionEntity_e965774a,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_e965774a,
  @IsActive = @IsActive_e965774a;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_582aa719 UNIQUEIDENTIFIER,
@Code_582aa719 NVARCHAR(40),
@Name_582aa719 NVARCHAR(200),
@Description_582aa719 NVARCHAR(MAX),
@IsReversal_582aa719 BIT,
@RequiresProvider_582aa719 BIT,
@RequiresInstrument_582aa719 BIT,
@RequiresReference_582aa719 BIT,
@DetailExtensionEntity_582aa719 NVARCHAR(255),
@Sequence_582aa719 INT,
@IsActive_582aa719 BIT
SET
  @ID_582aa719 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E05'
SET
  @Code_582aa719 = N'Cash'
SET
  @Name_582aa719 = N'Cash'
SET
  @Description_582aa719 = N'Cash received. No instrument, no reference.'
SET
  @IsReversal_582aa719 = 0
SET
  @RequiresProvider_582aa719 = 0
SET
  @RequiresInstrument_582aa719 = 0
SET
  @RequiresReference_582aa719 = 0
SET
  @Sequence_582aa719 = 50
SET
  @IsActive_582aa719 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_582aa719,
  @Code = @Code_582aa719,
  @Name = @Name_582aa719,
  @Description = @Description_582aa719,
  @IsReversal = @IsReversal_582aa719,
  @RequiresProvider = @RequiresProvider_582aa719,
  @RequiresInstrument = @RequiresInstrument_582aa719,
  @RequiresReference = @RequiresReference_582aa719,
  @DetailExtensionEntity = @DetailExtensionEntity_582aa719,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_582aa719,
  @IsActive = @IsActive_582aa719;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_ad07eee0 UNIQUEIDENTIFIER,
@Code_ad07eee0 NVARCHAR(40),
@Name_ad07eee0 NVARCHAR(200),
@Description_ad07eee0 NVARCHAR(MAX),
@IsReversal_ad07eee0 BIT,
@RequiresProvider_ad07eee0 BIT,
@RequiresInstrument_ad07eee0 BIT,
@RequiresReference_ad07eee0 BIT,
@DetailExtensionEntity_ad07eee0 NVARCHAR(255),
@Sequence_ad07eee0 INT,
@IsActive_ad07eee0 BIT
SET
  @ID_ad07eee0 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E06'
SET
  @Code_ad07eee0 = N'InternalTransfer'
SET
  @Name_ad07eee0 = N'Internal Transfer'
SET
  @Description_ad07eee0 = N'Movement between our own companies or accounts; reference identifies the transfer.'
SET
  @IsReversal_ad07eee0 = 0
SET
  @RequiresProvider_ad07eee0 = 0
SET
  @RequiresInstrument_ad07eee0 = 0
SET
  @RequiresReference_ad07eee0 = 1
SET
  @Sequence_ad07eee0 = 60
SET
  @IsActive_ad07eee0 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_ad07eee0,
  @Code = @Code_ad07eee0,
  @Name = @Name_ad07eee0,
  @Description = @Description_ad07eee0,
  @IsReversal = @IsReversal_ad07eee0,
  @RequiresProvider = @RequiresProvider_ad07eee0,
  @RequiresInstrument = @RequiresInstrument_ad07eee0,
  @RequiresReference = @RequiresReference_ad07eee0,
  @DetailExtensionEntity = @DetailExtensionEntity_ad07eee0,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_ad07eee0,
  @IsActive = @IsActive_ad07eee0;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_fef37378 UNIQUEIDENTIFIER,
@Code_fef37378 NVARCHAR(40),
@Name_fef37378 NVARCHAR(200),
@Description_fef37378 NVARCHAR(MAX),
@IsReversal_fef37378 BIT,
@RequiresProvider_fef37378 BIT,
@RequiresInstrument_fef37378 BIT,
@RequiresReference_fef37378 BIT,
@DetailExtensionEntity_fef37378 NVARCHAR(255),
@Sequence_fef37378 INT,
@IsActive_fef37378 BIT
SET
  @ID_fef37378 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E07'
SET
  @Code_fef37378 = N'GiftCard'
SET
  @Name_fef37378 = N'Gift Card / Stored Value'
SET
  @Description_fef37378 = N'Redemption against a StoredValueAccount; books liability relief, not revenue.'
SET
  @IsReversal_fef37378 = 0
SET
  @RequiresProvider_fef37378 = 0
SET
  @RequiresInstrument_fef37378 = 1
SET
  @RequiresReference_fef37378 = 0
SET
  @Sequence_fef37378 = 70
SET
  @IsActive_fef37378 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_fef37378,
  @Code = @Code_fef37378,
  @Name = @Name_fef37378,
  @Description = @Description_fef37378,
  @IsReversal = @IsReversal_fef37378,
  @RequiresProvider = @RequiresProvider_fef37378,
  @RequiresInstrument = @RequiresInstrument_fef37378,
  @RequiresReference = @RequiresReference_fef37378,
  @DetailExtensionEntity = @DetailExtensionEntity_fef37378,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_fef37378,
  @IsActive = @IsActive_fef37378;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_f2f88652 UNIQUEIDENTIFIER,
@Code_f2f88652 NVARCHAR(40),
@Name_f2f88652 NVARCHAR(200),
@Description_f2f88652 NVARCHAR(MAX),
@IsReversal_f2f88652 BIT,
@RequiresProvider_f2f88652 BIT,
@RequiresInstrument_f2f88652 BIT,
@RequiresReference_f2f88652 BIT,
@DetailExtensionEntity_f2f88652 NVARCHAR(255),
@Sequence_f2f88652 INT,
@IsActive_f2f88652 BIT
SET
  @ID_f2f88652 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E08'
SET
  @Code_f2f88652 = N'Refund'
SET
  @Name_f2f88652 = N'Refund'
SET
  @Description_f2f88652 = N'REVERSAL — money returned to the customer. Never offered as an initial payment.'
SET
  @IsReversal_f2f88652 = 1
SET
  @RequiresProvider_f2f88652 = 0
SET
  @RequiresInstrument_f2f88652 = 0
SET
  @RequiresReference_f2f88652 = 0
SET
  @Sequence_f2f88652 = 80
SET
  @IsActive_f2f88652 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_f2f88652,
  @Code = @Code_f2f88652,
  @Name = @Name_f2f88652,
  @Description = @Description_f2f88652,
  @IsReversal = @IsReversal_f2f88652,
  @RequiresProvider = @RequiresProvider_f2f88652,
  @RequiresInstrument = @RequiresInstrument_f2f88652,
  @RequiresReference = @RequiresReference_f2f88652,
  @DetailExtensionEntity = @DetailExtensionEntity_f2f88652,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_f2f88652,
  @IsActive = @IsActive_f2f88652;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_6bdd3b8e UNIQUEIDENTIFIER,
@Code_6bdd3b8e NVARCHAR(40),
@Name_6bdd3b8e NVARCHAR(200),
@Description_6bdd3b8e NVARCHAR(MAX),
@IsReversal_6bdd3b8e BIT,
@RequiresProvider_6bdd3b8e BIT,
@RequiresInstrument_6bdd3b8e BIT,
@RequiresReference_6bdd3b8e BIT,
@DetailExtensionEntity_6bdd3b8e NVARCHAR(255),
@Sequence_6bdd3b8e INT,
@IsActive_6bdd3b8e BIT
SET
  @ID_6bdd3b8e = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E09'
SET
  @Code_6bdd3b8e = N'Chargeback'
SET
  @Name_6bdd3b8e = N'Chargeback'
SET
  @Description_6bdd3b8e = N'REVERSAL — funds pulled back by the card network. Never an initial payment.'
SET
  @IsReversal_6bdd3b8e = 1
SET
  @RequiresProvider_6bdd3b8e = 0
SET
  @RequiresInstrument_6bdd3b8e = 0
SET
  @RequiresReference_6bdd3b8e = 0
SET
  @Sequence_6bdd3b8e = 90
SET
  @IsActive_6bdd3b8e = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_6bdd3b8e,
  @Code = @Code_6bdd3b8e,
  @Name = @Name_6bdd3b8e,
  @Description = @Description_6bdd3b8e,
  @IsReversal = @IsReversal_6bdd3b8e,
  @RequiresProvider = @RequiresProvider_6bdd3b8e,
  @RequiresInstrument = @RequiresInstrument_6bdd3b8e,
  @RequiresReference = @RequiresReference_6bdd3b8e,
  @DetailExtensionEntity = @DetailExtensionEntity_6bdd3b8e,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_6bdd3b8e,
  @IsActive = @IsActive_6bdd3b8e;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_5c38edc0 UNIQUEIDENTIFIER,
@Code_5c38edc0 NVARCHAR(40),
@Name_5c38edc0 NVARCHAR(200),
@Description_5c38edc0 NVARCHAR(MAX),
@IsReversal_5c38edc0 BIT,
@RequiresProvider_5c38edc0 BIT,
@RequiresInstrument_5c38edc0 BIT,
@RequiresReference_5c38edc0 BIT,
@DetailExtensionEntity_5c38edc0 NVARCHAR(255),
@Sequence_5c38edc0 INT,
@IsActive_5c38edc0 BIT
SET
  @ID_5c38edc0 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E0A'
SET
  @Code_5c38edc0 = N'BankReturn'
SET
  @Name_5c38edc0 = N'Bank Return'
SET
  @Description_5c38edc0 = N'REVERSAL — bank returned the debit (NSF etc.). Never an initial payment.'
SET
  @IsReversal_5c38edc0 = 1
SET
  @RequiresProvider_5c38edc0 = 0
SET
  @RequiresInstrument_5c38edc0 = 0
SET
  @RequiresReference_5c38edc0 = 0
SET
  @Sequence_5c38edc0 = 100
SET
  @IsActive_5c38edc0 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_5c38edc0,
  @Code = @Code_5c38edc0,
  @Name = @Name_5c38edc0,
  @Description = @Description_5c38edc0,
  @IsReversal = @IsReversal_5c38edc0,
  @RequiresProvider = @RequiresProvider_5c38edc0,
  @RequiresInstrument = @RequiresInstrument_5c38edc0,
  @RequiresReference = @RequiresReference_5c38edc0,
  @DetailExtensionEntity = @DetailExtensionEntity_5c38edc0,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_5c38edc0,
  @IsActive = @IsActive_5c38edc0;

GO


-- End of SQL Logging Session
-- Session ID: 2ca31dfc-490c-40dc-a21a-28e14a409684
-- Completed: 2026-07-25T19:11:10.227Z
-- Duration: 853ms
-- Total Statements: 15
