-- SQL Logging Session
-- Session ID: 8f6a5e31-7fe0-42c9-873f-9bef59db5065
-- Started: 2026-07-26T03:15:07.978Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Orders: Subscription Types (core SP call only)
DECLARE @Code_813918e7 NVARCHAR(40),
@Name_813918e7 NVARCHAR(200),
@Description_813918e7 NVARCHAR(MAX),
@DriverClass_813918e7 NVARCHAR(200),
@SubscriberScope_813918e7 NVARCHAR(20),
@StartMode_813918e7 NVARCHAR(20),
@DeferredStartDays_813918e7 INT,
@AnchorMonth_813918e7 TINYINT,
@AnchorDay_813918e7 TINYINT,
@PartialPeriodMode_813918e7 NVARCHAR(20),
@DefaultTermMonths_813918e7 INT,
@BillingCadence_813918e7 NVARCHAR(20),
@RecognitionCadence_813918e7 NVARCHAR(20),
@CustomCycleDays_813918e7 INT,
@TrialDays_813918e7 INT,
@ConcurrencyMode_813918e7 NVARCHAR(20),
@ReactivationMode_813918e7 NVARCHAR(30),
@ReactivationWindowDays_813918e7 INT,
@AutoRenewDefault_813918e7 BIT,
@RenewalLeadDays_813918e7 INT,
@CancellationMode_813918e7 NVARCHAR(20),
@CancellationRefundMode_813918e7 NVARCHAR(30),
@CancellationWindowDays_813918e7 INT,
@GracePeriodDays_813918e7 INT,
@Sequence_813918e7 INT,
@IsActive_813918e7 BIT,
@ID_813918e7 UNIQUEIDENTIFIER
SET
  @Code_813918e7 = N'CalendarYear'
SET
  @Name_813918e7 = N'Calendar Year (Jan 1 anchor)'
SET
  @Description_813918e7 = N'Membership year runs 1/1-12/31 for everyone. A mid-year join is PRORATED to the next anchor, so all members renew together. Bills annually, recognizes monthly. Cancels IMMEDIATELY and refunds the unused portion — `EndOfTerm` would be contradictory here, since coverage running to the term end leaves nothing unused to prorate.'
SET
  @SubscriberScope_813918e7 = N'Either'
SET
  @StartMode_813918e7 = N'CalendarAnchored'
SET
  @AnchorMonth_813918e7 = 1
SET
  @AnchorDay_813918e7 = 1
SET
  @PartialPeriodMode_813918e7 = N'Prorate'
SET
  @DefaultTermMonths_813918e7 = 12
SET
  @BillingCadence_813918e7 = N'Annual'
SET
  @RecognitionCadence_813918e7 = N'Monthly'
SET
  @TrialDays_813918e7 = 0
SET
  @ConcurrencyMode_813918e7 = N'ExtendExisting'
SET
  @ReactivationMode_813918e7 = N'ReactivateWithinWindow'
SET
  @ReactivationWindowDays_813918e7 = 90
SET
  @AutoRenewDefault_813918e7 = 1
SET
  @RenewalLeadDays_813918e7 = 90
SET
  @CancellationMode_813918e7 = N'Immediate'
SET
  @CancellationRefundMode_813918e7 = N'ProrateUnused'
SET
  @GracePeriodDays_813918e7 = 30
SET
  @Sequence_813918e7 = 20
SET
  @IsActive_813918e7 = 1
SET
  @ID_813918e7 = 'C5E1A870-9B24-4D63-8E17-5A6B7C8D9E02' EXEC [__mj_BizAppsOrders].spUpdateSubscriptionType @Code = @Code_813918e7,
  @Name = @Name_813918e7,
  @Description = @Description_813918e7,
  @DriverClass = @DriverClass_813918e7,
  @DriverClass_Clear = 1,
  @SubscriberScope = @SubscriberScope_813918e7,
  @StartMode = @StartMode_813918e7,
  @DeferredStartDays = @DeferredStartDays_813918e7,
  @DeferredStartDays_Clear = 1,
  @AnchorMonth = @AnchorMonth_813918e7,
  @AnchorDay = @AnchorDay_813918e7,
  @PartialPeriodMode = @PartialPeriodMode_813918e7,
  @DefaultTermMonths = @DefaultTermMonths_813918e7,
  @BillingCadence = @BillingCadence_813918e7,
  @RecognitionCadence = @RecognitionCadence_813918e7,
  @CustomCycleDays = @CustomCycleDays_813918e7,
  @CustomCycleDays_Clear = 1,
  @TrialDays = @TrialDays_813918e7,
  @ConcurrencyMode = @ConcurrencyMode_813918e7,
  @ReactivationMode = @ReactivationMode_813918e7,
  @ReactivationWindowDays = @ReactivationWindowDays_813918e7,
  @AutoRenewDefault = @AutoRenewDefault_813918e7,
  @RenewalLeadDays = @RenewalLeadDays_813918e7,
  @CancellationMode = @CancellationMode_813918e7,
  @CancellationRefundMode = @CancellationRefundMode_813918e7,
  @CancellationWindowDays = @CancellationWindowDays_813918e7,
  @CancellationWindowDays_Clear = 1,
  @GracePeriodDays = @GracePeriodDays_813918e7,
  @Sequence = @Sequence_813918e7,
  @IsActive = @IsActive_813918e7,
  @ID = @ID_813918e7;

GO

-- Save MJ_BizApps_Orders: Subscription Types (core SP call only)
DECLARE @Code_6dfb2865 NVARCHAR(40),
@Name_6dfb2865 NVARCHAR(200),
@Description_6dfb2865 NVARCHAR(MAX),
@DriverClass_6dfb2865 NVARCHAR(200),
@SubscriberScope_6dfb2865 NVARCHAR(20),
@StartMode_6dfb2865 NVARCHAR(20),
@DeferredStartDays_6dfb2865 INT,
@AnchorMonth_6dfb2865 TINYINT,
@AnchorDay_6dfb2865 TINYINT,
@PartialPeriodMode_6dfb2865 NVARCHAR(20),
@DefaultTermMonths_6dfb2865 INT,
@BillingCadence_6dfb2865 NVARCHAR(20),
@RecognitionCadence_6dfb2865 NVARCHAR(20),
@CustomCycleDays_6dfb2865 INT,
@TrialDays_6dfb2865 INT,
@ConcurrencyMode_6dfb2865 NVARCHAR(20),
@ReactivationMode_6dfb2865 NVARCHAR(30),
@ReactivationWindowDays_6dfb2865 INT,
@AutoRenewDefault_6dfb2865 BIT,
@RenewalLeadDays_6dfb2865 INT,
@CancellationMode_6dfb2865 NVARCHAR(20),
@CancellationRefundMode_6dfb2865 NVARCHAR(30),
@CancellationWindowDays_6dfb2865 INT,
@GracePeriodDays_6dfb2865 INT,
@Sequence_6dfb2865 INT,
@IsActive_6dfb2865 BIT,
@ID_6dfb2865 UNIQUEIDENTIFIER
SET
  @Code_6dfb2865 = N'MonthlyRolling'
SET
  @Name_6dfb2865 = N'Monthly — Rolling'
SET
  @Description_6dfb2865 = N'Month-to-month subscription. Bills and recognizes monthly, cancellable at the end of the current billing period, no grace.'
SET
  @SubscriberScope_6dfb2865 = N'Either'
SET
  @StartMode_6dfb2865 = N'Immediate'
SET
  @DefaultTermMonths_6dfb2865 = 1
SET
  @BillingCadence_6dfb2865 = N'Monthly'
SET
  @RecognitionCadence_6dfb2865 = N'MatchBilling'
SET
  @TrialDays_6dfb2865 = 0
SET
  @ConcurrencyMode_6dfb2865 = N'ExtendExisting'
SET
  @ReactivationMode_6dfb2865 = N'AlwaysCreateNew'
SET
  @AutoRenewDefault_6dfb2865 = 1
SET
  @RenewalLeadDays_6dfb2865 = 15
SET
  @CancellationMode_6dfb2865 = N'EndOfBillingPeriod'
SET
  @CancellationRefundMode_6dfb2865 = N'FullRefundWithinWindow'
SET
  @CancellationWindowDays_6dfb2865 = 14
SET
  @GracePeriodDays_6dfb2865 = 0
SET
  @Sequence_6dfb2865 = 40
SET
  @IsActive_6dfb2865 = 1
SET
  @ID_6dfb2865 = 'C5E1A870-9B24-4D63-8E17-5A6B7C8D9E04' EXEC [__mj_BizAppsOrders].spUpdateSubscriptionType @Code = @Code_6dfb2865,
  @Name = @Name_6dfb2865,
  @Description = @Description_6dfb2865,
  @DriverClass = @DriverClass_6dfb2865,
  @DriverClass_Clear = 1,
  @SubscriberScope = @SubscriberScope_6dfb2865,
  @StartMode = @StartMode_6dfb2865,
  @DeferredStartDays = @DeferredStartDays_6dfb2865,
  @DeferredStartDays_Clear = 1,
  @AnchorMonth = @AnchorMonth_6dfb2865,
  @AnchorMonth_Clear = 1,
  @AnchorDay = @AnchorDay_6dfb2865,
  @AnchorDay_Clear = 1,
  @PartialPeriodMode = @PartialPeriodMode_6dfb2865,
  @PartialPeriodMode_Clear = 1,
  @DefaultTermMonths = @DefaultTermMonths_6dfb2865,
  @BillingCadence = @BillingCadence_6dfb2865,
  @RecognitionCadence = @RecognitionCadence_6dfb2865,
  @CustomCycleDays = @CustomCycleDays_6dfb2865,
  @CustomCycleDays_Clear = 1,
  @TrialDays = @TrialDays_6dfb2865,
  @ConcurrencyMode = @ConcurrencyMode_6dfb2865,
  @ReactivationMode = @ReactivationMode_6dfb2865,
  @ReactivationWindowDays = @ReactivationWindowDays_6dfb2865,
  @ReactivationWindowDays_Clear = 1,
  @AutoRenewDefault = @AutoRenewDefault_6dfb2865,
  @RenewalLeadDays = @RenewalLeadDays_6dfb2865,
  @CancellationMode = @CancellationMode_6dfb2865,
  @CancellationRefundMode = @CancellationRefundMode_6dfb2865,
  @CancellationWindowDays = @CancellationWindowDays_6dfb2865,
  @GracePeriodDays = @GracePeriodDays_6dfb2865,
  @Sequence = @Sequence_6dfb2865,
  @IsActive = @IsActive_6dfb2865,
  @ID = @ID_6dfb2865;

GO


-- End of SQL Logging Session
-- Session ID: 8f6a5e31-7fe0-42c9-873f-9bef59db5065
-- Completed: 2026-07-26T03:15:08.608Z
-- Duration: 630ms
-- Total Statements: 2
