-- SQL Logging Session
-- Session ID: 1e0c38a9-ce90-491c-96fa-62aa150faf02
-- Started: 2026-07-26T02:26:49.094Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_7a5d0aea UNIQUEIDENTIFIER,
@Code_7a5d0aea NVARCHAR(40),
@Name_7a5d0aea NVARCHAR(200),
@Description_7a5d0aea NVARCHAR(MAX),
@DriverClass_7a5d0aea NVARCHAR(200),
@IsDeferred_7a5d0aea BIT,
@RequiresServicePeriod_7a5d0aea BIT,
@Sequence_7a5d0aea INT,
@IsActive_7a5d0aea BIT
SET
  @ID_7a5d0aea = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F01'
SET
  @Code_7a5d0aea = N'UpFront'
SET
  @Name_7a5d0aea = N'Up Front'
SET
  @Description_7a5d0aea = N'100% recognized when the order is booked. One-time goods and services — the booking entry credits Sales directly, with no deferral round-trip.'
SET
  @DriverClass_7a5d0aea = N'UpFront'
SET
  @IsDeferred_7a5d0aea = 0
SET
  @RequiresServicePeriod_7a5d0aea = 0
SET
  @Sequence_7a5d0aea = 10
SET
  @IsActive_7a5d0aea = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_7a5d0aea,
  @Code = @Code_7a5d0aea,
  @Name = @Name_7a5d0aea,
  @Description = @Description_7a5d0aea,
  @DriverClass = @DriverClass_7a5d0aea,
  @IsDeferred = @IsDeferred_7a5d0aea,
  @RequiresServicePeriod = @RequiresServicePeriod_7a5d0aea,
  @Sequence = @Sequence_7a5d0aea,
  @IsActive = @IsActive_7a5d0aea;

GO

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_1e59c3a0 UNIQUEIDENTIFIER,
@Code_1e59c3a0 NVARCHAR(40),
@Name_1e59c3a0 NVARCHAR(200),
@Description_1e59c3a0 NVARCHAR(MAX),
@DriverClass_1e59c3a0 NVARCHAR(200),
@IsDeferred_1e59c3a0 BIT,
@RequiresServicePeriod_1e59c3a0 BIT,
@Sequence_1e59c3a0 INT,
@IsActive_1e59c3a0 BIT
SET
  @ID_1e59c3a0 = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F02'
SET
  @Code_1e59c3a0 = N'EvenOverTime'
SET
  @Name_1e59c3a0 = N'Even Over Time (Straight Line)'
SET
  @Description_1e59c3a0 = N'Straight-line across the line''s service period — most subscriptions. A 12-month $1,200 line books to Deferred Revenue and releases 12 dated $100 entries. Rounding remainder is front-loaded into the first period.'
SET
  @DriverClass_1e59c3a0 = N'EvenOverTime'
SET
  @IsDeferred_1e59c3a0 = 1
SET
  @RequiresServicePeriod_1e59c3a0 = 1
SET
  @Sequence_1e59c3a0 = 20
SET
  @IsActive_1e59c3a0 = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_1e59c3a0,
  @Code = @Code_1e59c3a0,
  @Name = @Name_1e59c3a0,
  @Description = @Description_1e59c3a0,
  @DriverClass = @DriverClass_1e59c3a0,
  @IsDeferred = @IsDeferred_1e59c3a0,
  @RequiresServicePeriod = @RequiresServicePeriod_1e59c3a0,
  @Sequence = @Sequence_1e59c3a0,
  @IsActive = @IsActive_1e59c3a0;

GO

-- Save MJ_BizApps_Orders: Revenue Recognition Types (core SP call only)
DECLARE @ID_cd6d342f UNIQUEIDENTIFIER,
@Code_cd6d342f NVARCHAR(40),
@Name_cd6d342f NVARCHAR(200),
@Description_cd6d342f NVARCHAR(MAX),
@DriverClass_cd6d342f NVARCHAR(200),
@IsDeferred_cd6d342f BIT,
@RequiresServicePeriod_cd6d342f BIT,
@Sequence_cd6d342f INT,
@IsActive_cd6d342f BIT
SET
  @ID_cd6d342f = 'A1D4E7B0-3C62-4F85-9A17-2B3C4D5E6F03'
SET
  @Code_cd6d342f = N'AllBackEnd'
SET
  @Name_cd6d342f = N'All Back End (On Completion)'
SET
  @Description_cd6d342f = N'100% recognized on the service period END date — events and milestone deliverables, where nothing is earned until delivery. Cash sits in Deferred Revenue until the event date.'
SET
  @DriverClass_cd6d342f = N'AllBackEnd'
SET
  @IsDeferred_cd6d342f = 1
SET
  @RequiresServicePeriod_cd6d342f = 1
SET
  @Sequence_cd6d342f = 30
SET
  @IsActive_cd6d342f = 1
EXEC [__mj_BizAppsOrders].spCreateRevenueRecognitionType @ID = @ID_cd6d342f,
  @Code = @Code_cd6d342f,
  @Name = @Name_cd6d342f,
  @Description = @Description_cd6d342f,
  @DriverClass = @DriverClass_cd6d342f,
  @IsDeferred = @IsDeferred_cd6d342f,
  @RequiresServicePeriod = @RequiresServicePeriod_cd6d342f,
  @Sequence = @Sequence_cd6d342f,
  @IsActive = @IsActive_cd6d342f;

GO

-- Save MJ_BizApps_Orders: Subscription Types (core SP call only)
DECLARE @ID_d11529dc UNIQUEIDENTIFIER,
@Code_d11529dc NVARCHAR(40),
@Name_d11529dc NVARCHAR(200),
@Description_d11529dc NVARCHAR(MAX),
@DriverClass_d11529dc NVARCHAR(200),
@SubscriberScope_d11529dc NVARCHAR(20),
@StartMode_d11529dc NVARCHAR(20),
@DeferredStartDays_d11529dc INT,
@AnchorMonth_d11529dc TINYINT,
@AnchorDay_d11529dc TINYINT,
@PartialPeriodMode_d11529dc NVARCHAR(20),
@DefaultTermMonths_d11529dc INT,
@BillingCadence_d11529dc NVARCHAR(20),
@RecognitionCadence_d11529dc NVARCHAR(20),
@CustomCycleDays_d11529dc INT,
@TrialDays_d11529dc INT,
@ConcurrencyMode_d11529dc NVARCHAR(20),
@ReactivationMode_d11529dc NVARCHAR(30),
@ReactivationWindowDays_d11529dc INT,
@AutoRenewDefault_d11529dc BIT,
@RenewalLeadDays_d11529dc INT,
@CancellationMode_d11529dc NVARCHAR(20),
@CancellationRefundMode_d11529dc NVARCHAR(30),
@CancellationWindowDays_d11529dc INT,
@GracePeriodDays_d11529dc INT,
@Sequence_d11529dc INT,
@IsActive_d11529dc BIT
SET
  @ID_d11529dc = 'C5E1A870-9B24-4D63-8E17-5A6B7C8D9E01'
SET
  @Code_d11529dc = N'AnnualRolling'
SET
  @Name_d11529dc = N'Annual — Rolling'
SET
  @Description_d11529dc = N'Standard annual subscription starting the day it is purchased. Bills annually, recognizes monthly. A repeat purchase extends the existing term rather than creating a second concurrent subscription.'
SET
  @SubscriberScope_d11529dc = N'Either'
SET
  @StartMode_d11529dc = N'Immediate'
SET
  @DefaultTermMonths_d11529dc = 12
SET
  @BillingCadence_d11529dc = N'Annual'
SET
  @RecognitionCadence_d11529dc = N'Monthly'
SET
  @TrialDays_d11529dc = 0
SET
  @ConcurrencyMode_d11529dc = N'ExtendExisting'
SET
  @ReactivationMode_d11529dc = N'ReactivateWithinWindow'
SET
  @ReactivationWindowDays_d11529dc = 90
SET
  @AutoRenewDefault_d11529dc = 1
SET
  @RenewalLeadDays_d11529dc = 90
SET
  @CancellationMode_d11529dc = N'EndOfTerm'
SET
  @CancellationRefundMode_d11529dc = N'NoRefund'
SET
  @GracePeriodDays_d11529dc = 30
SET
  @Sequence_d11529dc = 10
SET
  @IsActive_d11529dc = 1
EXEC [__mj_BizAppsOrders].spCreateSubscriptionType @ID = @ID_d11529dc,
  @Code = @Code_d11529dc,
  @Name = @Name_d11529dc,
  @Description = @Description_d11529dc,
  @DriverClass = @DriverClass_d11529dc,
  @DriverClass_Clear = 1,
  @SubscriberScope = @SubscriberScope_d11529dc,
  @StartMode = @StartMode_d11529dc,
  @DeferredStartDays = @DeferredStartDays_d11529dc,
  @DeferredStartDays_Clear = 1,
  @AnchorMonth = @AnchorMonth_d11529dc,
  @AnchorMonth_Clear = 1,
  @AnchorDay = @AnchorDay_d11529dc,
  @AnchorDay_Clear = 1,
  @PartialPeriodMode = @PartialPeriodMode_d11529dc,
  @PartialPeriodMode_Clear = 1,
  @DefaultTermMonths = @DefaultTermMonths_d11529dc,
  @BillingCadence = @BillingCadence_d11529dc,
  @RecognitionCadence = @RecognitionCadence_d11529dc,
  @CustomCycleDays = @CustomCycleDays_d11529dc,
  @CustomCycleDays_Clear = 1,
  @TrialDays = @TrialDays_d11529dc,
  @ConcurrencyMode = @ConcurrencyMode_d11529dc,
  @ReactivationMode = @ReactivationMode_d11529dc,
  @ReactivationWindowDays = @ReactivationWindowDays_d11529dc,
  @AutoRenewDefault = @AutoRenewDefault_d11529dc,
  @RenewalLeadDays = @RenewalLeadDays_d11529dc,
  @CancellationMode = @CancellationMode_d11529dc,
  @CancellationRefundMode = @CancellationRefundMode_d11529dc,
  @CancellationWindowDays = @CancellationWindowDays_d11529dc,
  @CancellationWindowDays_Clear = 1,
  @GracePeriodDays = @GracePeriodDays_d11529dc,
  @Sequence = @Sequence_d11529dc,
  @IsActive = @IsActive_d11529dc;

GO

-- Save MJ_BizApps_Orders: Subscription Types (core SP call only)
DECLARE @ID_8f15f78f UNIQUEIDENTIFIER,
@Code_8f15f78f NVARCHAR(40),
@Name_8f15f78f NVARCHAR(200),
@Description_8f15f78f NVARCHAR(MAX),
@DriverClass_8f15f78f NVARCHAR(200),
@SubscriberScope_8f15f78f NVARCHAR(20),
@StartMode_8f15f78f NVARCHAR(20),
@DeferredStartDays_8f15f78f INT,
@AnchorMonth_8f15f78f TINYINT,
@AnchorDay_8f15f78f TINYINT,
@PartialPeriodMode_8f15f78f NVARCHAR(20),
@DefaultTermMonths_8f15f78f INT,
@BillingCadence_8f15f78f NVARCHAR(20),
@RecognitionCadence_8f15f78f NVARCHAR(20),
@CustomCycleDays_8f15f78f INT,
@TrialDays_8f15f78f INT,
@ConcurrencyMode_8f15f78f NVARCHAR(20),
@ReactivationMode_8f15f78f NVARCHAR(30),
@ReactivationWindowDays_8f15f78f INT,
@AutoRenewDefault_8f15f78f BIT,
@RenewalLeadDays_8f15f78f INT,
@CancellationMode_8f15f78f NVARCHAR(20),
@CancellationRefundMode_8f15f78f NVARCHAR(30),
@CancellationWindowDays_8f15f78f INT,
@GracePeriodDays_8f15f78f INT,
@Sequence_8f15f78f INT,
@IsActive_8f15f78f BIT
SET
  @ID_8f15f78f = 'C5E1A870-9B24-4D63-8E17-5A6B7C8D9E02'
SET
  @Code_8f15f78f = N'CalendarYear'
SET
  @Name_8f15f78f = N'Calendar Year (Jan 1 anchor)'
SET
  @Description_8f15f78f = N'Membership year runs 1/1-12/31 for everyone. A mid-year join is PRORATED to the next anchor, so all members renew together. Bills annually, recognizes monthly.'
SET
  @SubscriberScope_8f15f78f = N'Either'
SET
  @StartMode_8f15f78f = N'CalendarAnchored'
SET
  @AnchorMonth_8f15f78f = 1
SET
  @AnchorDay_8f15f78f = 1
SET
  @PartialPeriodMode_8f15f78f = N'Prorate'
SET
  @DefaultTermMonths_8f15f78f = 12
SET
  @BillingCadence_8f15f78f = N'Annual'
SET
  @RecognitionCadence_8f15f78f = N'Monthly'
SET
  @TrialDays_8f15f78f = 0
SET
  @ConcurrencyMode_8f15f78f = N'ExtendExisting'
SET
  @ReactivationMode_8f15f78f = N'ReactivateWithinWindow'
SET
  @ReactivationWindowDays_8f15f78f = 90
SET
  @AutoRenewDefault_8f15f78f = 1
SET
  @RenewalLeadDays_8f15f78f = 90
SET
  @CancellationMode_8f15f78f = N'EndOfTerm'
SET
  @CancellationRefundMode_8f15f78f = N'ProrateUnused'
SET
  @GracePeriodDays_8f15f78f = 30
SET
  @Sequence_8f15f78f = 20
SET
  @IsActive_8f15f78f = 1
EXEC [__mj_BizAppsOrders].spCreateSubscriptionType @ID = @ID_8f15f78f,
  @Code = @Code_8f15f78f,
  @Name = @Name_8f15f78f,
  @Description = @Description_8f15f78f,
  @DriverClass = @DriverClass_8f15f78f,
  @DriverClass_Clear = 1,
  @SubscriberScope = @SubscriberScope_8f15f78f,
  @StartMode = @StartMode_8f15f78f,
  @DeferredStartDays = @DeferredStartDays_8f15f78f,
  @DeferredStartDays_Clear = 1,
  @AnchorMonth = @AnchorMonth_8f15f78f,
  @AnchorDay = @AnchorDay_8f15f78f,
  @PartialPeriodMode = @PartialPeriodMode_8f15f78f,
  @DefaultTermMonths = @DefaultTermMonths_8f15f78f,
  @BillingCadence = @BillingCadence_8f15f78f,
  @RecognitionCadence = @RecognitionCadence_8f15f78f,
  @CustomCycleDays = @CustomCycleDays_8f15f78f,
  @CustomCycleDays_Clear = 1,
  @TrialDays = @TrialDays_8f15f78f,
  @ConcurrencyMode = @ConcurrencyMode_8f15f78f,
  @ReactivationMode = @ReactivationMode_8f15f78f,
  @ReactivationWindowDays = @ReactivationWindowDays_8f15f78f,
  @AutoRenewDefault = @AutoRenewDefault_8f15f78f,
  @RenewalLeadDays = @RenewalLeadDays_8f15f78f,
  @CancellationMode = @CancellationMode_8f15f78f,
  @CancellationRefundMode = @CancellationRefundMode_8f15f78f,
  @CancellationWindowDays = @CancellationWindowDays_8f15f78f,
  @CancellationWindowDays_Clear = 1,
  @GracePeriodDays = @GracePeriodDays_8f15f78f,
  @Sequence = @Sequence_8f15f78f,
  @IsActive = @IsActive_8f15f78f;

GO

-- Save MJ_BizApps_Orders: Subscription Types (core SP call only)
DECLARE @ID_03dc9742 UNIQUEIDENTIFIER,
@Code_03dc9742 NVARCHAR(40),
@Name_03dc9742 NVARCHAR(200),
@Description_03dc9742 NVARCHAR(MAX),
@DriverClass_03dc9742 NVARCHAR(200),
@SubscriberScope_03dc9742 NVARCHAR(20),
@StartMode_03dc9742 NVARCHAR(20),
@DeferredStartDays_03dc9742 INT,
@AnchorMonth_03dc9742 TINYINT,
@AnchorDay_03dc9742 TINYINT,
@PartialPeriodMode_03dc9742 NVARCHAR(20),
@DefaultTermMonths_03dc9742 INT,
@BillingCadence_03dc9742 NVARCHAR(20),
@RecognitionCadence_03dc9742 NVARCHAR(20),
@CustomCycleDays_03dc9742 INT,
@TrialDays_03dc9742 INT,
@ConcurrencyMode_03dc9742 NVARCHAR(20),
@ReactivationMode_03dc9742 NVARCHAR(30),
@ReactivationWindowDays_03dc9742 INT,
@AutoRenewDefault_03dc9742 BIT,
@RenewalLeadDays_03dc9742 INT,
@CancellationMode_03dc9742 NVARCHAR(20),
@CancellationRefundMode_03dc9742 NVARCHAR(30),
@CancellationWindowDays_03dc9742 INT,
@GracePeriodDays_03dc9742 INT,
@Sequence_03dc9742 INT,
@IsActive_03dc9742 BIT
SET
  @ID_03dc9742 = 'C5E1A870-9B24-4D63-8E17-5A6B7C8D9E03'
SET
  @Code_03dc9742 = N'FiscalYearJul'
SET
  @Name_03dc9742 = N'Fiscal Year (Jul 1 anchor, charge full)'
SET
  @Description_03dc9742 = N'Fiscal-year membership anchored 7/1. A mid-year join is charged the FULL year rather than prorated (the alternative policy to CalendarYear). Recognizes quarterly.'
SET
  @SubscriberScope_03dc9742 = N'Organization'
SET
  @StartMode_03dc9742 = N'CalendarAnchored'
SET
  @AnchorMonth_03dc9742 = 7
SET
  @AnchorDay_03dc9742 = 1
SET
  @PartialPeriodMode_03dc9742 = N'ChargeFull'
SET
  @DefaultTermMonths_03dc9742 = 12
SET
  @BillingCadence_03dc9742 = N'Annual'
SET
  @RecognitionCadence_03dc9742 = N'Quarterly'
SET
  @TrialDays_03dc9742 = 0
SET
  @ConcurrencyMode_03dc9742 = N'RejectDuplicate'
SET
  @ReactivationMode_03dc9742 = N'ReactivateExisting'
SET
  @AutoRenewDefault_03dc9742 = 1
SET
  @RenewalLeadDays_03dc9742 = 120
SET
  @CancellationMode_03dc9742 = N'EndOfTerm'
SET
  @CancellationRefundMode_03dc9742 = N'NoRefund'
SET
  @GracePeriodDays_03dc9742 = 60
SET
  @Sequence_03dc9742 = 30
SET
  @IsActive_03dc9742 = 1
EXEC [__mj_BizAppsOrders].spCreateSubscriptionType @ID = @ID_03dc9742,
  @Code = @Code_03dc9742,
  @Name = @Name_03dc9742,
  @Description = @Description_03dc9742,
  @DriverClass = @DriverClass_03dc9742,
  @DriverClass_Clear = 1,
  @SubscriberScope = @SubscriberScope_03dc9742,
  @StartMode = @StartMode_03dc9742,
  @DeferredStartDays = @DeferredStartDays_03dc9742,
  @DeferredStartDays_Clear = 1,
  @AnchorMonth = @AnchorMonth_03dc9742,
  @AnchorDay = @AnchorDay_03dc9742,
  @PartialPeriodMode = @PartialPeriodMode_03dc9742,
  @DefaultTermMonths = @DefaultTermMonths_03dc9742,
  @BillingCadence = @BillingCadence_03dc9742,
  @RecognitionCadence = @RecognitionCadence_03dc9742,
  @CustomCycleDays = @CustomCycleDays_03dc9742,
  @CustomCycleDays_Clear = 1,
  @TrialDays = @TrialDays_03dc9742,
  @ConcurrencyMode = @ConcurrencyMode_03dc9742,
  @ReactivationMode = @ReactivationMode_03dc9742,
  @ReactivationWindowDays = @ReactivationWindowDays_03dc9742,
  @ReactivationWindowDays_Clear = 1,
  @AutoRenewDefault = @AutoRenewDefault_03dc9742,
  @RenewalLeadDays = @RenewalLeadDays_03dc9742,
  @CancellationMode = @CancellationMode_03dc9742,
  @CancellationRefundMode = @CancellationRefundMode_03dc9742,
  @CancellationWindowDays = @CancellationWindowDays_03dc9742,
  @CancellationWindowDays_Clear = 1,
  @GracePeriodDays = @GracePeriodDays_03dc9742,
  @Sequence = @Sequence_03dc9742,
  @IsActive = @IsActive_03dc9742;

GO

-- Save MJ_BizApps_Orders: Subscription Types (core SP call only)
DECLARE @ID_a4da9114 UNIQUEIDENTIFIER,
@Code_a4da9114 NVARCHAR(40),
@Name_a4da9114 NVARCHAR(200),
@Description_a4da9114 NVARCHAR(MAX),
@DriverClass_a4da9114 NVARCHAR(200),
@SubscriberScope_a4da9114 NVARCHAR(20),
@StartMode_a4da9114 NVARCHAR(20),
@DeferredStartDays_a4da9114 INT,
@AnchorMonth_a4da9114 TINYINT,
@AnchorDay_a4da9114 TINYINT,
@PartialPeriodMode_a4da9114 NVARCHAR(20),
@DefaultTermMonths_a4da9114 INT,
@BillingCadence_a4da9114 NVARCHAR(20),
@RecognitionCadence_a4da9114 NVARCHAR(20),
@CustomCycleDays_a4da9114 INT,
@TrialDays_a4da9114 INT,
@ConcurrencyMode_a4da9114 NVARCHAR(20),
@ReactivationMode_a4da9114 NVARCHAR(30),
@ReactivationWindowDays_a4da9114 INT,
@AutoRenewDefault_a4da9114 BIT,
@RenewalLeadDays_a4da9114 INT,
@CancellationMode_a4da9114 NVARCHAR(20),
@CancellationRefundMode_a4da9114 NVARCHAR(30),
@CancellationWindowDays_a4da9114 INT,
@GracePeriodDays_a4da9114 INT,
@Sequence_a4da9114 INT,
@IsActive_a4da9114 BIT
SET
  @ID_a4da9114 = 'C5E1A870-9B24-4D63-8E17-5A6B7C8D9E04'
SET
  @Code_a4da9114 = N'MonthlyRolling'
SET
  @Name_a4da9114 = N'Monthly — Rolling'
SET
  @Description_a4da9114 = N'Month-to-month subscription. Bills and recognizes monthly, cancellable at the end of the current billing period, no grace.'
SET
  @SubscriberScope_a4da9114 = N'Either'
SET
  @StartMode_a4da9114 = N'Immediate'
SET
  @DefaultTermMonths_a4da9114 = 1
SET
  @BillingCadence_a4da9114 = N'Monthly'
SET
  @RecognitionCadence_a4da9114 = N'MatchBilling'
SET
  @TrialDays_a4da9114 = 0
SET
  @ConcurrencyMode_a4da9114 = N'ExtendExisting'
SET
  @ReactivationMode_a4da9114 = N'AlwaysCreateNew'
SET
  @AutoRenewDefault_a4da9114 = 1
SET
  @RenewalLeadDays_a4da9114 = 15
SET
  @CancellationMode_a4da9114 = N'EndOfBillingPeriod'
SET
  @CancellationRefundMode_a4da9114 = N'NoRefund'
SET
  @GracePeriodDays_a4da9114 = 0
SET
  @Sequence_a4da9114 = 40
SET
  @IsActive_a4da9114 = 1
EXEC [__mj_BizAppsOrders].spCreateSubscriptionType @ID = @ID_a4da9114,
  @Code = @Code_a4da9114,
  @Name = @Name_a4da9114,
  @Description = @Description_a4da9114,
  @DriverClass = @DriverClass_a4da9114,
  @DriverClass_Clear = 1,
  @SubscriberScope = @SubscriberScope_a4da9114,
  @StartMode = @StartMode_a4da9114,
  @DeferredStartDays = @DeferredStartDays_a4da9114,
  @DeferredStartDays_Clear = 1,
  @AnchorMonth = @AnchorMonth_a4da9114,
  @AnchorMonth_Clear = 1,
  @AnchorDay = @AnchorDay_a4da9114,
  @AnchorDay_Clear = 1,
  @PartialPeriodMode = @PartialPeriodMode_a4da9114,
  @PartialPeriodMode_Clear = 1,
  @DefaultTermMonths = @DefaultTermMonths_a4da9114,
  @BillingCadence = @BillingCadence_a4da9114,
  @RecognitionCadence = @RecognitionCadence_a4da9114,
  @CustomCycleDays = @CustomCycleDays_a4da9114,
  @CustomCycleDays_Clear = 1,
  @TrialDays = @TrialDays_a4da9114,
  @ConcurrencyMode = @ConcurrencyMode_a4da9114,
  @ReactivationMode = @ReactivationMode_a4da9114,
  @ReactivationWindowDays = @ReactivationWindowDays_a4da9114,
  @ReactivationWindowDays_Clear = 1,
  @AutoRenewDefault = @AutoRenewDefault_a4da9114,
  @RenewalLeadDays = @RenewalLeadDays_a4da9114,
  @CancellationMode = @CancellationMode_a4da9114,
  @CancellationRefundMode = @CancellationRefundMode_a4da9114,
  @CancellationWindowDays = @CancellationWindowDays_a4da9114,
  @CancellationWindowDays_Clear = 1,
  @GracePeriodDays = @GracePeriodDays_a4da9114,
  @Sequence = @Sequence_a4da9114,
  @IsActive = @IsActive_a4da9114;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_fa8d6563 UNIQUEIDENTIFIER,
@Code_fa8d6563 NVARCHAR(40),
@Name_fa8d6563 NVARCHAR(200),
@Description_fa8d6563 NVARCHAR(MAX),
@DriverClass_fa8d6563 NVARCHAR(200),
@SupportsTokenization_fa8d6563 BIT,
@SupportsRefund_fa8d6563 BIT,
@SupportsWebhooks_fa8d6563 BIT,
@Sequence_fa8d6563 INT,
@IsActive_fa8d6563 BIT
SET
  @ID_fa8d6563 = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C01'
SET
  @Code_fa8d6563 = N'Stripe'
SET
  @Name_fa8d6563 = N'Stripe'
SET
  @Description_fa8d6563 = N'Stripe payments — cards, wallets, hosted checkout.'
SET
  @DriverClass_fa8d6563 = N'StripePaymentProvider'
SET
  @SupportsTokenization_fa8d6563 = 1
SET
  @SupportsRefund_fa8d6563 = 1
SET
  @SupportsWebhooks_fa8d6563 = 1
SET
  @Sequence_fa8d6563 = 10
SET
  @IsActive_fa8d6563 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_fa8d6563,
  @Code = @Code_fa8d6563,
  @Name = @Name_fa8d6563,
  @Description = @Description_fa8d6563,
  @DriverClass = @DriverClass_fa8d6563,
  @SupportsTokenization = @SupportsTokenization_fa8d6563,
  @SupportsRefund = @SupportsRefund_fa8d6563,
  @SupportsWebhooks = @SupportsWebhooks_fa8d6563,
  @Sequence = @Sequence_fa8d6563,
  @IsActive = @IsActive_fa8d6563;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_8849daa8 UNIQUEIDENTIFIER,
@Code_8849daa8 NVARCHAR(40),
@Name_8849daa8 NVARCHAR(200),
@Description_8849daa8 NVARCHAR(MAX),
@DriverClass_8849daa8 NVARCHAR(200),
@SupportsTokenization_8849daa8 BIT,
@SupportsRefund_8849daa8 BIT,
@SupportsWebhooks_8849daa8 BIT,
@Sequence_8849daa8 INT,
@IsActive_8849daa8 BIT
SET
  @ID_8849daa8 = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C02'
SET
  @Code_8849daa8 = N'Manual'
SET
  @Name_8849daa8 = N'Manual'
SET
  @Description_8849daa8 = N'Finance records the money movement by hand (check, wire, cash). Always available.'
SET
  @DriverClass_8849daa8 = N'ManualPaymentProvider'
SET
  @SupportsTokenization_8849daa8 = 0
SET
  @SupportsRefund_8849daa8 = 1
SET
  @SupportsWebhooks_8849daa8 = 0
SET
  @Sequence_8849daa8 = 20
SET
  @IsActive_8849daa8 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_8849daa8,
  @Code = @Code_8849daa8,
  @Name = @Name_8849daa8,
  @Description = @Description_8849daa8,
  @DriverClass = @DriverClass_8849daa8,
  @SupportsTokenization = @SupportsTokenization_8849daa8,
  @SupportsRefund = @SupportsRefund_8849daa8,
  @SupportsWebhooks = @SupportsWebhooks_8849daa8,
  @Sequence = @Sequence_8849daa8,
  @IsActive = @IsActive_8849daa8;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_82aa26be UNIQUEIDENTIFIER,
@Code_82aa26be NVARCHAR(40),
@Name_82aa26be NVARCHAR(200),
@Description_82aa26be NVARCHAR(MAX),
@IsReversal_82aa26be BIT,
@RequiresProvider_82aa26be BIT,
@RequiresInstrument_82aa26be BIT,
@RequiresReference_82aa26be BIT,
@DetailExtensionEntity_82aa26be NVARCHAR(255),
@Sequence_82aa26be INT,
@IsActive_82aa26be BIT
SET
  @ID_82aa26be = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E01'
SET
  @Code_82aa26be = N'CreditCard'
SET
  @Name_82aa26be = N'Credit Card'
SET
  @Description_82aa26be = N'Card payment through a gateway; the instrument is a provider token, never a PAN.'
SET
  @IsReversal_82aa26be = 0
SET
  @RequiresProvider_82aa26be = 1
SET
  @RequiresInstrument_82aa26be = 1
SET
  @RequiresReference_82aa26be = 0
SET
  @Sequence_82aa26be = 10
SET
  @IsActive_82aa26be = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_82aa26be,
  @Code = @Code_82aa26be,
  @Name = @Name_82aa26be,
  @Description = @Description_82aa26be,
  @IsReversal = @IsReversal_82aa26be,
  @RequiresProvider = @RequiresProvider_82aa26be,
  @RequiresInstrument = @RequiresInstrument_82aa26be,
  @RequiresReference = @RequiresReference_82aa26be,
  @DetailExtensionEntity = @DetailExtensionEntity_82aa26be,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_82aa26be,
  @IsActive = @IsActive_82aa26be;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_ecb2374f UNIQUEIDENTIFIER,
@Code_ecb2374f NVARCHAR(40),
@Name_ecb2374f NVARCHAR(200),
@Description_ecb2374f NVARCHAR(MAX),
@IsReversal_ecb2374f BIT,
@RequiresProvider_ecb2374f BIT,
@RequiresInstrument_ecb2374f BIT,
@RequiresReference_ecb2374f BIT,
@DetailExtensionEntity_ecb2374f NVARCHAR(255),
@Sequence_ecb2374f INT,
@IsActive_ecb2374f BIT
SET
  @ID_ecb2374f = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E02'
SET
  @Code_ecb2374f = N'ACH'
SET
  @Name_ecb2374f = N'ACH / Bank Transfer'
SET
  @Description_ecb2374f = N'Bank debit through a gateway; instrument carries routing/account last-4 only.'
SET
  @IsReversal_ecb2374f = 0
SET
  @RequiresProvider_ecb2374f = 1
SET
  @RequiresInstrument_ecb2374f = 1
SET
  @RequiresReference_ecb2374f = 0
SET
  @Sequence_ecb2374f = 20
SET
  @IsActive_ecb2374f = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_ecb2374f,
  @Code = @Code_ecb2374f,
  @Name = @Name_ecb2374f,
  @Description = @Description_ecb2374f,
  @IsReversal = @IsReversal_ecb2374f,
  @RequiresProvider = @RequiresProvider_ecb2374f,
  @RequiresInstrument = @RequiresInstrument_ecb2374f,
  @RequiresReference = @RequiresReference_ecb2374f,
  @DetailExtensionEntity = @DetailExtensionEntity_ecb2374f,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_ecb2374f,
  @IsActive = @IsActive_ecb2374f;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_4271c213 UNIQUEIDENTIFIER,
@Code_4271c213 NVARCHAR(40),
@Name_4271c213 NVARCHAR(200),
@Description_4271c213 NVARCHAR(MAX),
@IsReversal_4271c213 BIT,
@RequiresProvider_4271c213 BIT,
@RequiresInstrument_4271c213 BIT,
@RequiresReference_4271c213 BIT,
@DetailExtensionEntity_4271c213 NVARCHAR(255),
@Sequence_4271c213 INT,
@IsActive_4271c213 BIT
SET
  @ID_4271c213 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E03'
SET
  @Code_4271c213 = N'Wire'
SET
  @Name_4271c213 = N'Wire Transfer'
SET
  @Description_4271c213 = N'Wire received; the confirmation number is captured as the instrument reference.'
SET
  @IsReversal_4271c213 = 0
SET
  @RequiresProvider_4271c213 = 0
SET
  @RequiresInstrument_4271c213 = 0
SET
  @RequiresReference_4271c213 = 1
SET
  @Sequence_4271c213 = 30
SET
  @IsActive_4271c213 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_4271c213,
  @Code = @Code_4271c213,
  @Name = @Name_4271c213,
  @Description = @Description_4271c213,
  @IsReversal = @IsReversal_4271c213,
  @RequiresProvider = @RequiresProvider_4271c213,
  @RequiresInstrument = @RequiresInstrument_4271c213,
  @RequiresReference = @RequiresReference_4271c213,
  @DetailExtensionEntity = @DetailExtensionEntity_4271c213,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_4271c213,
  @IsActive = @IsActive_4271c213;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_7d25bb44 UNIQUEIDENTIFIER,
@Code_7d25bb44 NVARCHAR(40),
@Name_7d25bb44 NVARCHAR(200),
@Description_7d25bb44 NVARCHAR(MAX),
@IsReversal_7d25bb44 BIT,
@RequiresProvider_7d25bb44 BIT,
@RequiresInstrument_7d25bb44 BIT,
@RequiresReference_7d25bb44 BIT,
@DetailExtensionEntity_7d25bb44 NVARCHAR(255),
@Sequence_7d25bb44 INT,
@IsActive_7d25bb44 BIT
SET
  @ID_7d25bb44 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E04'
SET
  @Code_7d25bb44 = N'Check'
SET
  @Name_7d25bb44 = N'Check'
SET
  @Description_7d25bb44 = N'Paper check; the check number is captured as the instrument reference.'
SET
  @IsReversal_7d25bb44 = 0
SET
  @RequiresProvider_7d25bb44 = 0
SET
  @RequiresInstrument_7d25bb44 = 1
SET
  @RequiresReference_7d25bb44 = 1
SET
  @Sequence_7d25bb44 = 40
SET
  @IsActive_7d25bb44 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_7d25bb44,
  @Code = @Code_7d25bb44,
  @Name = @Name_7d25bb44,
  @Description = @Description_7d25bb44,
  @IsReversal = @IsReversal_7d25bb44,
  @RequiresProvider = @RequiresProvider_7d25bb44,
  @RequiresInstrument = @RequiresInstrument_7d25bb44,
  @RequiresReference = @RequiresReference_7d25bb44,
  @DetailExtensionEntity = @DetailExtensionEntity_7d25bb44,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_7d25bb44,
  @IsActive = @IsActive_7d25bb44;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_db2d0ff5 UNIQUEIDENTIFIER,
@Code_db2d0ff5 NVARCHAR(40),
@Name_db2d0ff5 NVARCHAR(200),
@Description_db2d0ff5 NVARCHAR(MAX),
@IsReversal_db2d0ff5 BIT,
@RequiresProvider_db2d0ff5 BIT,
@RequiresInstrument_db2d0ff5 BIT,
@RequiresReference_db2d0ff5 BIT,
@DetailExtensionEntity_db2d0ff5 NVARCHAR(255),
@Sequence_db2d0ff5 INT,
@IsActive_db2d0ff5 BIT
SET
  @ID_db2d0ff5 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E05'
SET
  @Code_db2d0ff5 = N'Cash'
SET
  @Name_db2d0ff5 = N'Cash'
SET
  @Description_db2d0ff5 = N'Cash received. No instrument, no reference.'
SET
  @IsReversal_db2d0ff5 = 0
SET
  @RequiresProvider_db2d0ff5 = 0
SET
  @RequiresInstrument_db2d0ff5 = 0
SET
  @RequiresReference_db2d0ff5 = 0
SET
  @Sequence_db2d0ff5 = 50
SET
  @IsActive_db2d0ff5 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_db2d0ff5,
  @Code = @Code_db2d0ff5,
  @Name = @Name_db2d0ff5,
  @Description = @Description_db2d0ff5,
  @IsReversal = @IsReversal_db2d0ff5,
  @RequiresProvider = @RequiresProvider_db2d0ff5,
  @RequiresInstrument = @RequiresInstrument_db2d0ff5,
  @RequiresReference = @RequiresReference_db2d0ff5,
  @DetailExtensionEntity = @DetailExtensionEntity_db2d0ff5,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_db2d0ff5,
  @IsActive = @IsActive_db2d0ff5;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_ba4428f6 UNIQUEIDENTIFIER,
@Code_ba4428f6 NVARCHAR(40),
@Name_ba4428f6 NVARCHAR(200),
@Description_ba4428f6 NVARCHAR(MAX),
@IsReversal_ba4428f6 BIT,
@RequiresProvider_ba4428f6 BIT,
@RequiresInstrument_ba4428f6 BIT,
@RequiresReference_ba4428f6 BIT,
@DetailExtensionEntity_ba4428f6 NVARCHAR(255),
@Sequence_ba4428f6 INT,
@IsActive_ba4428f6 BIT
SET
  @ID_ba4428f6 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E06'
SET
  @Code_ba4428f6 = N'InternalTransfer'
SET
  @Name_ba4428f6 = N'Internal Transfer'
SET
  @Description_ba4428f6 = N'Movement between our own companies or accounts; reference identifies the transfer.'
SET
  @IsReversal_ba4428f6 = 0
SET
  @RequiresProvider_ba4428f6 = 0
SET
  @RequiresInstrument_ba4428f6 = 0
SET
  @RequiresReference_ba4428f6 = 1
SET
  @Sequence_ba4428f6 = 60
SET
  @IsActive_ba4428f6 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_ba4428f6,
  @Code = @Code_ba4428f6,
  @Name = @Name_ba4428f6,
  @Description = @Description_ba4428f6,
  @IsReversal = @IsReversal_ba4428f6,
  @RequiresProvider = @RequiresProvider_ba4428f6,
  @RequiresInstrument = @RequiresInstrument_ba4428f6,
  @RequiresReference = @RequiresReference_ba4428f6,
  @DetailExtensionEntity = @DetailExtensionEntity_ba4428f6,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_ba4428f6,
  @IsActive = @IsActive_ba4428f6;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_69d18d97 UNIQUEIDENTIFIER,
@Code_69d18d97 NVARCHAR(40),
@Name_69d18d97 NVARCHAR(200),
@Description_69d18d97 NVARCHAR(MAX),
@IsReversal_69d18d97 BIT,
@RequiresProvider_69d18d97 BIT,
@RequiresInstrument_69d18d97 BIT,
@RequiresReference_69d18d97 BIT,
@DetailExtensionEntity_69d18d97 NVARCHAR(255),
@Sequence_69d18d97 INT,
@IsActive_69d18d97 BIT
SET
  @ID_69d18d97 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E07'
SET
  @Code_69d18d97 = N'GiftCard'
SET
  @Name_69d18d97 = N'Gift Card / Stored Value'
SET
  @Description_69d18d97 = N'Redemption against a StoredValueAccount; books liability relief, not revenue.'
SET
  @IsReversal_69d18d97 = 0
SET
  @RequiresProvider_69d18d97 = 0
SET
  @RequiresInstrument_69d18d97 = 1
SET
  @RequiresReference_69d18d97 = 0
SET
  @Sequence_69d18d97 = 70
SET
  @IsActive_69d18d97 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_69d18d97,
  @Code = @Code_69d18d97,
  @Name = @Name_69d18d97,
  @Description = @Description_69d18d97,
  @IsReversal = @IsReversal_69d18d97,
  @RequiresProvider = @RequiresProvider_69d18d97,
  @RequiresInstrument = @RequiresInstrument_69d18d97,
  @RequiresReference = @RequiresReference_69d18d97,
  @DetailExtensionEntity = @DetailExtensionEntity_69d18d97,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_69d18d97,
  @IsActive = @IsActive_69d18d97;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_94c76549 UNIQUEIDENTIFIER,
@Code_94c76549 NVARCHAR(40),
@Name_94c76549 NVARCHAR(200),
@Description_94c76549 NVARCHAR(MAX),
@IsReversal_94c76549 BIT,
@RequiresProvider_94c76549 BIT,
@RequiresInstrument_94c76549 BIT,
@RequiresReference_94c76549 BIT,
@DetailExtensionEntity_94c76549 NVARCHAR(255),
@Sequence_94c76549 INT,
@IsActive_94c76549 BIT
SET
  @ID_94c76549 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E08'
SET
  @Code_94c76549 = N'Refund'
SET
  @Name_94c76549 = N'Refund'
SET
  @Description_94c76549 = N'REVERSAL — money returned to the customer. Never offered as an initial payment.'
SET
  @IsReversal_94c76549 = 1
SET
  @RequiresProvider_94c76549 = 0
SET
  @RequiresInstrument_94c76549 = 0
SET
  @RequiresReference_94c76549 = 0
SET
  @Sequence_94c76549 = 80
SET
  @IsActive_94c76549 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_94c76549,
  @Code = @Code_94c76549,
  @Name = @Name_94c76549,
  @Description = @Description_94c76549,
  @IsReversal = @IsReversal_94c76549,
  @RequiresProvider = @RequiresProvider_94c76549,
  @RequiresInstrument = @RequiresInstrument_94c76549,
  @RequiresReference = @RequiresReference_94c76549,
  @DetailExtensionEntity = @DetailExtensionEntity_94c76549,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_94c76549,
  @IsActive = @IsActive_94c76549;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_d7242524 UNIQUEIDENTIFIER,
@Code_d7242524 NVARCHAR(40),
@Name_d7242524 NVARCHAR(200),
@Description_d7242524 NVARCHAR(MAX),
@IsReversal_d7242524 BIT,
@RequiresProvider_d7242524 BIT,
@RequiresInstrument_d7242524 BIT,
@RequiresReference_d7242524 BIT,
@DetailExtensionEntity_d7242524 NVARCHAR(255),
@Sequence_d7242524 INT,
@IsActive_d7242524 BIT
SET
  @ID_d7242524 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E09'
SET
  @Code_d7242524 = N'Chargeback'
SET
  @Name_d7242524 = N'Chargeback'
SET
  @Description_d7242524 = N'REVERSAL — funds pulled back by the card network. Never an initial payment.'
SET
  @IsReversal_d7242524 = 1
SET
  @RequiresProvider_d7242524 = 0
SET
  @RequiresInstrument_d7242524 = 0
SET
  @RequiresReference_d7242524 = 0
SET
  @Sequence_d7242524 = 90
SET
  @IsActive_d7242524 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_d7242524,
  @Code = @Code_d7242524,
  @Name = @Name_d7242524,
  @Description = @Description_d7242524,
  @IsReversal = @IsReversal_d7242524,
  @RequiresProvider = @RequiresProvider_d7242524,
  @RequiresInstrument = @RequiresInstrument_d7242524,
  @RequiresReference = @RequiresReference_d7242524,
  @DetailExtensionEntity = @DetailExtensionEntity_d7242524,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_d7242524,
  @IsActive = @IsActive_d7242524;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_26adc52d UNIQUEIDENTIFIER,
@Code_26adc52d NVARCHAR(40),
@Name_26adc52d NVARCHAR(200),
@Description_26adc52d NVARCHAR(MAX),
@IsReversal_26adc52d BIT,
@RequiresProvider_26adc52d BIT,
@RequiresInstrument_26adc52d BIT,
@RequiresReference_26adc52d BIT,
@DetailExtensionEntity_26adc52d NVARCHAR(255),
@Sequence_26adc52d INT,
@IsActive_26adc52d BIT
SET
  @ID_26adc52d = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E0A'
SET
  @Code_26adc52d = N'BankReturn'
SET
  @Name_26adc52d = N'Bank Return'
SET
  @Description_26adc52d = N'REVERSAL — bank returned the debit (NSF etc.). Never an initial payment.'
SET
  @IsReversal_26adc52d = 1
SET
  @RequiresProvider_26adc52d = 0
SET
  @RequiresInstrument_26adc52d = 0
SET
  @RequiresReference_26adc52d = 0
SET
  @Sequence_26adc52d = 100
SET
  @IsActive_26adc52d = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_26adc52d,
  @Code = @Code_26adc52d,
  @Name = @Name_26adc52d,
  @Description = @Description_26adc52d,
  @IsReversal = @IsReversal_26adc52d,
  @RequiresProvider = @RequiresProvider_26adc52d,
  @RequiresInstrument = @RequiresInstrument_26adc52d,
  @RequiresReference = @RequiresReference_26adc52d,
  @DetailExtensionEntity = @DetailExtensionEntity_26adc52d,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_26adc52d,
  @IsActive = @IsActive_26adc52d;

GO


-- End of SQL Logging Session
-- Session ID: 1e0c38a9-ce90-491c-96fa-62aa150faf02
-- Completed: 2026-07-26T02:26:50.225Z
-- Duration: 1131ms
-- Total Statements: 19
