-- SQL Logging Session
-- Session ID: 26d3990d-c08e-4539-86b0-1ede0de9c940
-- Started: 2026-07-25T17:55:22.563Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_461e6cc9 UNIQUEIDENTIFIER,
@Code_461e6cc9 NVARCHAR(40),
@Name_461e6cc9 NVARCHAR(200),
@Description_461e6cc9 NVARCHAR(MAX),
@DriverClass_461e6cc9 NVARCHAR(200),
@SupportsTokenization_461e6cc9 BIT,
@SupportsRefund_461e6cc9 BIT,
@SupportsWebhooks_461e6cc9 BIT,
@Sequence_461e6cc9 INT,
@IsActive_461e6cc9 BIT
SET
  @ID_461e6cc9 = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C01'
SET
  @Code_461e6cc9 = N'Stripe'
SET
  @Name_461e6cc9 = N'Stripe'
SET
  @Description_461e6cc9 = N'Stripe payments — cards, wallets, hosted checkout.'
SET
  @DriverClass_461e6cc9 = N'StripePaymentProvider'
SET
  @SupportsTokenization_461e6cc9 = 1
SET
  @SupportsRefund_461e6cc9 = 1
SET
  @SupportsWebhooks_461e6cc9 = 1
SET
  @Sequence_461e6cc9 = 10
SET
  @IsActive_461e6cc9 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_461e6cc9,
  @Code = @Code_461e6cc9,
  @Name = @Name_461e6cc9,
  @Description = @Description_461e6cc9,
  @DriverClass = @DriverClass_461e6cc9,
  @SupportsTokenization = @SupportsTokenization_461e6cc9,
  @SupportsRefund = @SupportsRefund_461e6cc9,
  @SupportsWebhooks = @SupportsWebhooks_461e6cc9,
  @Sequence = @Sequence_461e6cc9,
  @IsActive = @IsActive_461e6cc9;

GO

-- Save MJ_BizApps_Orders: Payment Provider Types (core SP call only)
DECLARE @ID_b1d33a9d UNIQUEIDENTIFIER,
@Code_b1d33a9d NVARCHAR(40),
@Name_b1d33a9d NVARCHAR(200),
@Description_b1d33a9d NVARCHAR(MAX),
@DriverClass_b1d33a9d NVARCHAR(200),
@SupportsTokenization_b1d33a9d BIT,
@SupportsRefund_b1d33a9d BIT,
@SupportsWebhooks_b1d33a9d BIT,
@Sequence_b1d33a9d INT,
@IsActive_b1d33a9d BIT
SET
  @ID_b1d33a9d = '8B4C2E10-5D93-4A6F-B7C8-1E2F3A4B5C02'
SET
  @Code_b1d33a9d = N'Manual'
SET
  @Name_b1d33a9d = N'Manual'
SET
  @Description_b1d33a9d = N'Finance records the money movement by hand (check, wire, cash). Always available.'
SET
  @DriverClass_b1d33a9d = N'ManualPaymentProvider'
SET
  @SupportsTokenization_b1d33a9d = 0
SET
  @SupportsRefund_b1d33a9d = 1
SET
  @SupportsWebhooks_b1d33a9d = 0
SET
  @Sequence_b1d33a9d = 20
SET
  @IsActive_b1d33a9d = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentProviderType @ID = @ID_b1d33a9d,
  @Code = @Code_b1d33a9d,
  @Name = @Name_b1d33a9d,
  @Description = @Description_b1d33a9d,
  @DriverClass = @DriverClass_b1d33a9d,
  @SupportsTokenization = @SupportsTokenization_b1d33a9d,
  @SupportsRefund = @SupportsRefund_b1d33a9d,
  @SupportsWebhooks = @SupportsWebhooks_b1d33a9d,
  @Sequence = @Sequence_b1d33a9d,
  @IsActive = @IsActive_b1d33a9d;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_7af5d37c UNIQUEIDENTIFIER,
@Code_7af5d37c NVARCHAR(40),
@Name_7af5d37c NVARCHAR(200),
@Description_7af5d37c NVARCHAR(MAX),
@IsReversal_7af5d37c BIT,
@RequiresProvider_7af5d37c BIT,
@RequiresInstrument_7af5d37c BIT,
@RequiresReference_7af5d37c BIT,
@DetailExtensionEntity_7af5d37c NVARCHAR(255),
@Sequence_7af5d37c INT,
@IsActive_7af5d37c BIT
SET
  @ID_7af5d37c = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E01'
SET
  @Code_7af5d37c = N'CreditCard'
SET
  @Name_7af5d37c = N'Credit Card'
SET
  @Description_7af5d37c = N'Card payment through a gateway; the instrument is a provider token, never a PAN.'
SET
  @IsReversal_7af5d37c = 0
SET
  @RequiresProvider_7af5d37c = 1
SET
  @RequiresInstrument_7af5d37c = 1
SET
  @RequiresReference_7af5d37c = 0
SET
  @Sequence_7af5d37c = 10
SET
  @IsActive_7af5d37c = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_7af5d37c,
  @Code = @Code_7af5d37c,
  @Name = @Name_7af5d37c,
  @Description = @Description_7af5d37c,
  @IsReversal = @IsReversal_7af5d37c,
  @RequiresProvider = @RequiresProvider_7af5d37c,
  @RequiresInstrument = @RequiresInstrument_7af5d37c,
  @RequiresReference = @RequiresReference_7af5d37c,
  @DetailExtensionEntity = @DetailExtensionEntity_7af5d37c,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_7af5d37c,
  @IsActive = @IsActive_7af5d37c;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_76e6466d UNIQUEIDENTIFIER,
@Code_76e6466d NVARCHAR(40),
@Name_76e6466d NVARCHAR(200),
@Description_76e6466d NVARCHAR(MAX),
@IsReversal_76e6466d BIT,
@RequiresProvider_76e6466d BIT,
@RequiresInstrument_76e6466d BIT,
@RequiresReference_76e6466d BIT,
@DetailExtensionEntity_76e6466d NVARCHAR(255),
@Sequence_76e6466d INT,
@IsActive_76e6466d BIT
SET
  @ID_76e6466d = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E02'
SET
  @Code_76e6466d = N'ACH'
SET
  @Name_76e6466d = N'ACH / Bank Transfer'
SET
  @Description_76e6466d = N'Bank debit through a gateway; instrument carries routing/account last-4 only.'
SET
  @IsReversal_76e6466d = 0
SET
  @RequiresProvider_76e6466d = 1
SET
  @RequiresInstrument_76e6466d = 1
SET
  @RequiresReference_76e6466d = 0
SET
  @Sequence_76e6466d = 20
SET
  @IsActive_76e6466d = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_76e6466d,
  @Code = @Code_76e6466d,
  @Name = @Name_76e6466d,
  @Description = @Description_76e6466d,
  @IsReversal = @IsReversal_76e6466d,
  @RequiresProvider = @RequiresProvider_76e6466d,
  @RequiresInstrument = @RequiresInstrument_76e6466d,
  @RequiresReference = @RequiresReference_76e6466d,
  @DetailExtensionEntity = @DetailExtensionEntity_76e6466d,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_76e6466d,
  @IsActive = @IsActive_76e6466d;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_778487b2 UNIQUEIDENTIFIER,
@Code_778487b2 NVARCHAR(40),
@Name_778487b2 NVARCHAR(200),
@Description_778487b2 NVARCHAR(MAX),
@IsReversal_778487b2 BIT,
@RequiresProvider_778487b2 BIT,
@RequiresInstrument_778487b2 BIT,
@RequiresReference_778487b2 BIT,
@DetailExtensionEntity_778487b2 NVARCHAR(255),
@Sequence_778487b2 INT,
@IsActive_778487b2 BIT
SET
  @ID_778487b2 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E03'
SET
  @Code_778487b2 = N'Wire'
SET
  @Name_778487b2 = N'Wire Transfer'
SET
  @Description_778487b2 = N'Wire received; the confirmation number is captured as the instrument reference.'
SET
  @IsReversal_778487b2 = 0
SET
  @RequiresProvider_778487b2 = 0
SET
  @RequiresInstrument_778487b2 = 0
SET
  @RequiresReference_778487b2 = 1
SET
  @Sequence_778487b2 = 30
SET
  @IsActive_778487b2 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_778487b2,
  @Code = @Code_778487b2,
  @Name = @Name_778487b2,
  @Description = @Description_778487b2,
  @IsReversal = @IsReversal_778487b2,
  @RequiresProvider = @RequiresProvider_778487b2,
  @RequiresInstrument = @RequiresInstrument_778487b2,
  @RequiresReference = @RequiresReference_778487b2,
  @DetailExtensionEntity = @DetailExtensionEntity_778487b2,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_778487b2,
  @IsActive = @IsActive_778487b2;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_67c218db UNIQUEIDENTIFIER,
@Code_67c218db NVARCHAR(40),
@Name_67c218db NVARCHAR(200),
@Description_67c218db NVARCHAR(MAX),
@IsReversal_67c218db BIT,
@RequiresProvider_67c218db BIT,
@RequiresInstrument_67c218db BIT,
@RequiresReference_67c218db BIT,
@DetailExtensionEntity_67c218db NVARCHAR(255),
@Sequence_67c218db INT,
@IsActive_67c218db BIT
SET
  @ID_67c218db = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E04'
SET
  @Code_67c218db = N'Check'
SET
  @Name_67c218db = N'Check'
SET
  @Description_67c218db = N'Paper check; the check number is captured as the instrument reference.'
SET
  @IsReversal_67c218db = 0
SET
  @RequiresProvider_67c218db = 0
SET
  @RequiresInstrument_67c218db = 1
SET
  @RequiresReference_67c218db = 1
SET
  @Sequence_67c218db = 40
SET
  @IsActive_67c218db = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_67c218db,
  @Code = @Code_67c218db,
  @Name = @Name_67c218db,
  @Description = @Description_67c218db,
  @IsReversal = @IsReversal_67c218db,
  @RequiresProvider = @RequiresProvider_67c218db,
  @RequiresInstrument = @RequiresInstrument_67c218db,
  @RequiresReference = @RequiresReference_67c218db,
  @DetailExtensionEntity = @DetailExtensionEntity_67c218db,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_67c218db,
  @IsActive = @IsActive_67c218db;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_c59432fc UNIQUEIDENTIFIER,
@Code_c59432fc NVARCHAR(40),
@Name_c59432fc NVARCHAR(200),
@Description_c59432fc NVARCHAR(MAX),
@IsReversal_c59432fc BIT,
@RequiresProvider_c59432fc BIT,
@RequiresInstrument_c59432fc BIT,
@RequiresReference_c59432fc BIT,
@DetailExtensionEntity_c59432fc NVARCHAR(255),
@Sequence_c59432fc INT,
@IsActive_c59432fc BIT
SET
  @ID_c59432fc = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E05'
SET
  @Code_c59432fc = N'Cash'
SET
  @Name_c59432fc = N'Cash'
SET
  @Description_c59432fc = N'Cash received. No instrument, no reference.'
SET
  @IsReversal_c59432fc = 0
SET
  @RequiresProvider_c59432fc = 0
SET
  @RequiresInstrument_c59432fc = 0
SET
  @RequiresReference_c59432fc = 0
SET
  @Sequence_c59432fc = 50
SET
  @IsActive_c59432fc = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_c59432fc,
  @Code = @Code_c59432fc,
  @Name = @Name_c59432fc,
  @Description = @Description_c59432fc,
  @IsReversal = @IsReversal_c59432fc,
  @RequiresProvider = @RequiresProvider_c59432fc,
  @RequiresInstrument = @RequiresInstrument_c59432fc,
  @RequiresReference = @RequiresReference_c59432fc,
  @DetailExtensionEntity = @DetailExtensionEntity_c59432fc,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_c59432fc,
  @IsActive = @IsActive_c59432fc;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_eb3d4c84 UNIQUEIDENTIFIER,
@Code_eb3d4c84 NVARCHAR(40),
@Name_eb3d4c84 NVARCHAR(200),
@Description_eb3d4c84 NVARCHAR(MAX),
@IsReversal_eb3d4c84 BIT,
@RequiresProvider_eb3d4c84 BIT,
@RequiresInstrument_eb3d4c84 BIT,
@RequiresReference_eb3d4c84 BIT,
@DetailExtensionEntity_eb3d4c84 NVARCHAR(255),
@Sequence_eb3d4c84 INT,
@IsActive_eb3d4c84 BIT
SET
  @ID_eb3d4c84 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E06'
SET
  @Code_eb3d4c84 = N'InternalTransfer'
SET
  @Name_eb3d4c84 = N'Internal Transfer'
SET
  @Description_eb3d4c84 = N'Movement between our own companies or accounts; reference identifies the transfer.'
SET
  @IsReversal_eb3d4c84 = 0
SET
  @RequiresProvider_eb3d4c84 = 0
SET
  @RequiresInstrument_eb3d4c84 = 0
SET
  @RequiresReference_eb3d4c84 = 1
SET
  @Sequence_eb3d4c84 = 60
SET
  @IsActive_eb3d4c84 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_eb3d4c84,
  @Code = @Code_eb3d4c84,
  @Name = @Name_eb3d4c84,
  @Description = @Description_eb3d4c84,
  @IsReversal = @IsReversal_eb3d4c84,
  @RequiresProvider = @RequiresProvider_eb3d4c84,
  @RequiresInstrument = @RequiresInstrument_eb3d4c84,
  @RequiresReference = @RequiresReference_eb3d4c84,
  @DetailExtensionEntity = @DetailExtensionEntity_eb3d4c84,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_eb3d4c84,
  @IsActive = @IsActive_eb3d4c84;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_761677e9 UNIQUEIDENTIFIER,
@Code_761677e9 NVARCHAR(40),
@Name_761677e9 NVARCHAR(200),
@Description_761677e9 NVARCHAR(MAX),
@IsReversal_761677e9 BIT,
@RequiresProvider_761677e9 BIT,
@RequiresInstrument_761677e9 BIT,
@RequiresReference_761677e9 BIT,
@DetailExtensionEntity_761677e9 NVARCHAR(255),
@Sequence_761677e9 INT,
@IsActive_761677e9 BIT
SET
  @ID_761677e9 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E07'
SET
  @Code_761677e9 = N'GiftCard'
SET
  @Name_761677e9 = N'Gift Card / Stored Value'
SET
  @Description_761677e9 = N'Redemption against a StoredValueAccount; books liability relief, not revenue.'
SET
  @IsReversal_761677e9 = 0
SET
  @RequiresProvider_761677e9 = 0
SET
  @RequiresInstrument_761677e9 = 1
SET
  @RequiresReference_761677e9 = 0
SET
  @Sequence_761677e9 = 70
SET
  @IsActive_761677e9 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_761677e9,
  @Code = @Code_761677e9,
  @Name = @Name_761677e9,
  @Description = @Description_761677e9,
  @IsReversal = @IsReversal_761677e9,
  @RequiresProvider = @RequiresProvider_761677e9,
  @RequiresInstrument = @RequiresInstrument_761677e9,
  @RequiresReference = @RequiresReference_761677e9,
  @DetailExtensionEntity = @DetailExtensionEntity_761677e9,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_761677e9,
  @IsActive = @IsActive_761677e9;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_a6be5acf UNIQUEIDENTIFIER,
@Code_a6be5acf NVARCHAR(40),
@Name_a6be5acf NVARCHAR(200),
@Description_a6be5acf NVARCHAR(MAX),
@IsReversal_a6be5acf BIT,
@RequiresProvider_a6be5acf BIT,
@RequiresInstrument_a6be5acf BIT,
@RequiresReference_a6be5acf BIT,
@DetailExtensionEntity_a6be5acf NVARCHAR(255),
@Sequence_a6be5acf INT,
@IsActive_a6be5acf BIT
SET
  @ID_a6be5acf = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E08'
SET
  @Code_a6be5acf = N'Refund'
SET
  @Name_a6be5acf = N'Refund'
SET
  @Description_a6be5acf = N'REVERSAL — money returned to the customer. Never offered as an initial payment.'
SET
  @IsReversal_a6be5acf = 1
SET
  @RequiresProvider_a6be5acf = 0
SET
  @RequiresInstrument_a6be5acf = 0
SET
  @RequiresReference_a6be5acf = 0
SET
  @Sequence_a6be5acf = 80
SET
  @IsActive_a6be5acf = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_a6be5acf,
  @Code = @Code_a6be5acf,
  @Name = @Name_a6be5acf,
  @Description = @Description_a6be5acf,
  @IsReversal = @IsReversal_a6be5acf,
  @RequiresProvider = @RequiresProvider_a6be5acf,
  @RequiresInstrument = @RequiresInstrument_a6be5acf,
  @RequiresReference = @RequiresReference_a6be5acf,
  @DetailExtensionEntity = @DetailExtensionEntity_a6be5acf,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_a6be5acf,
  @IsActive = @IsActive_a6be5acf;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_a3b98e79 UNIQUEIDENTIFIER,
@Code_a3b98e79 NVARCHAR(40),
@Name_a3b98e79 NVARCHAR(200),
@Description_a3b98e79 NVARCHAR(MAX),
@IsReversal_a3b98e79 BIT,
@RequiresProvider_a3b98e79 BIT,
@RequiresInstrument_a3b98e79 BIT,
@RequiresReference_a3b98e79 BIT,
@DetailExtensionEntity_a3b98e79 NVARCHAR(255),
@Sequence_a3b98e79 INT,
@IsActive_a3b98e79 BIT
SET
  @ID_a3b98e79 = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E09'
SET
  @Code_a3b98e79 = N'Chargeback'
SET
  @Name_a3b98e79 = N'Chargeback'
SET
  @Description_a3b98e79 = N'REVERSAL — funds pulled back by the card network. Never an initial payment.'
SET
  @IsReversal_a3b98e79 = 1
SET
  @RequiresProvider_a3b98e79 = 0
SET
  @RequiresInstrument_a3b98e79 = 0
SET
  @RequiresReference_a3b98e79 = 0
SET
  @Sequence_a3b98e79 = 90
SET
  @IsActive_a3b98e79 = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_a3b98e79,
  @Code = @Code_a3b98e79,
  @Name = @Name_a3b98e79,
  @Description = @Description_a3b98e79,
  @IsReversal = @IsReversal_a3b98e79,
  @RequiresProvider = @RequiresProvider_a3b98e79,
  @RequiresInstrument = @RequiresInstrument_a3b98e79,
  @RequiresReference = @RequiresReference_a3b98e79,
  @DetailExtensionEntity = @DetailExtensionEntity_a3b98e79,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_a3b98e79,
  @IsActive = @IsActive_a3b98e79;

GO

-- Save MJ_BizApps_Orders: Payment Types (core SP call only)
DECLARE @ID_94e4d37b UNIQUEIDENTIFIER,
@Code_94e4d37b NVARCHAR(40),
@Name_94e4d37b NVARCHAR(200),
@Description_94e4d37b NVARCHAR(MAX),
@IsReversal_94e4d37b BIT,
@RequiresProvider_94e4d37b BIT,
@RequiresInstrument_94e4d37b BIT,
@RequiresReference_94e4d37b BIT,
@DetailExtensionEntity_94e4d37b NVARCHAR(255),
@Sequence_94e4d37b INT,
@IsActive_94e4d37b BIT
SET
  @ID_94e4d37b = '2F1A6D30-0C41-4E7B-9E51-0A1B7C2D3E0A'
SET
  @Code_94e4d37b = N'BankReturn'
SET
  @Name_94e4d37b = N'Bank Return'
SET
  @Description_94e4d37b = N'REVERSAL — bank returned the debit (NSF etc.). Never an initial payment.'
SET
  @IsReversal_94e4d37b = 1
SET
  @RequiresProvider_94e4d37b = 0
SET
  @RequiresInstrument_94e4d37b = 0
SET
  @RequiresReference_94e4d37b = 0
SET
  @Sequence_94e4d37b = 100
SET
  @IsActive_94e4d37b = 1
EXEC [__mj_BizAppsOrders].spCreatePaymentType @ID = @ID_94e4d37b,
  @Code = @Code_94e4d37b,
  @Name = @Name_94e4d37b,
  @Description = @Description_94e4d37b,
  @IsReversal = @IsReversal_94e4d37b,
  @RequiresProvider = @RequiresProvider_94e4d37b,
  @RequiresInstrument = @RequiresInstrument_94e4d37b,
  @RequiresReference = @RequiresReference_94e4d37b,
  @DetailExtensionEntity = @DetailExtensionEntity_94e4d37b,
  @DetailExtensionEntity_Clear = 1,
  @Sequence = @Sequence_94e4d37b,
  @IsActive = @IsActive_94e4d37b;

GO


-- End of SQL Logging Session
-- Session ID: 26d3990d-c08e-4539-86b0-1ede0de9c940
-- Completed: 2026-07-25T17:55:23.628Z
-- Duration: 1065ms
-- Total Statements: 12
