-- =============================================================================================
-- BizApps Orders v5.27.x -- Metadata_Sync (one per release)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --ci` (MJ CLI 6.1.4) against a database built from
-- migrations ONLY: MJ core 6.1.4, bizapps-common v5.50.1, bizapps-tasks v1.6.2, bizapps-accounting
-- v0.20.0, then this app's migrations at `next`. Push result: 18 created, 4 updated, 442
-- unchanged, 0 errors. All 18 creates are the ML bench (below); this file carries the 4 updates.
--
-- UPDATED (4), each checked column by column against a copy of the database taken before the
-- push; only Description changes, every change traces to metadata/actions, none reverts a migration:
--   * Action Generate Invoice (one document per order, from the order's company)
--   * Its params CompanyID, HTML and DocumentCount
--
-- NOT INCLUDED: the ML bench output (ml-models, ml-training-pipelines, ml-model-scoring-bindings,
-- record-processes) and the scheduled jobs its record processes create, as in 5.20-5.26.
--
-- TRANSFORMS: `EXEC [__mj]` -> `EXEC [${mjSchema}]`; string values are untouched. The Action's ID
-- is resolved on the host by DriverClass, each param's by its Action and Name. Idempotent.
-- =============================================================================================
-- Save MJ: Actions (core SP call only)
DECLARE @CategoryID_799112d1ecb2 UNIQUEIDENTIFIER,
@Name_799112d1ecb2 NVARCHAR(425),
@Description_799112d1ecb2 NVARCHAR(MAX),
@Type_799112d1ecb2 NVARCHAR(20),
@UserPrompt_799112d1ecb2 NVARCHAR(MAX),
@UserComments_799112d1ecb2 NVARCHAR(MAX),
@Code_799112d1ecb2 NVARCHAR(MAX),
@CodeComments_799112d1ecb2 NVARCHAR(MAX),
@CodeApprovalStatus_799112d1ecb2 NVARCHAR(20),
@CodeApprovalComments_799112d1ecb2 NVARCHAR(MAX),
@CodeApprovedByUserID_799112d1ecb2 UNIQUEIDENTIFIER,
@CodeApprovedAt_799112d1ecb2 DATETIMEOFFSET,
@CodeLocked_799112d1ecb2 BIT,
@ForceCodeGeneration_799112d1ecb2 BIT,
@RetentionPeriod_799112d1ecb2 INT,
@Status_799112d1ecb2 NVARCHAR(20),
@DriverClass_799112d1ecb2 NVARCHAR(255),
@ParentID_799112d1ecb2 UNIQUEIDENTIFIER,
@IconClass_799112d1ecb2 NVARCHAR(100),
@DefaultCompactPromptID_799112d1ecb2 UNIQUEIDENTIFIER,
@Config_799112d1ecb2 NVARCHAR(MAX),
@RuntimeActionConfiguration_799112d1ecb2 NVARCHAR(MAX),
@MaxExecutionTimeMS_799112d1ecb2 INT,
@CreatedByAgentID_799112d1ecb2 UNIQUEIDENTIFIER,
@ID_799112d1ecb2 UNIQUEIDENTIFIER
SET
  @CategoryID_799112d1ecb2 = '359F5241-25D1-4949-A74F-C20CA3EECC3A'
SET
  @Name_799112d1ecb2 = N'Generate Invoice'
SET
  @Description_799112d1ecb2 = N'Render an order as the document you send a customer: an invoice, a quote (for a draft or quoted order) or a credit memo (for a reversal). Returns self-contained HTML ready for a PDF renderer or an email body, plus the underlying figures so a caller can reconcile without parsing markup. Writes nothing. An order produces one document, from the order''s company, listing every line whatever company owns each product.'
SET
  @Type_799112d1ecb2 = N'Custom'
SET
  @UserPrompt_799112d1ecb2 = N'Given an order, produce the customer-facing document for it using the ''Orders: Standard Invoice'' template.'
SET
  @CodeApprovalStatus_799112d1ecb2 = N'Approved'
SET
  @CodeLocked_799112d1ecb2 = 0
SET
  @ForceCodeGeneration_799112d1ecb2 = 0
SET
  @Status_799112d1ecb2 = N'Active'
SET
  @DriverClass_799112d1ecb2 = N'Orders.GenerateInvoice'
SET
  @IconClass_799112d1ecb2 = N'fa-regular fa-file-lines'
SET
  @ID_799112d1ecb2 = '896B0F83-AD89-4FC5-BDB9-330DE95AB3E4'
SELECT TOP 1 @ID_799112d1ecb2 = [ID] FROM [${mjSchema}].[Action] WHERE [DriverClass] = N'Orders.GenerateInvoice' ORDER BY CASE WHEN [ID] = @ID_799112d1ecb2 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateAction @CategoryID = @CategoryID_799112d1ecb2,
  @Name = @Name_799112d1ecb2,
  @Description = @Description_799112d1ecb2,
  @Type = @Type_799112d1ecb2,
  @UserPrompt = @UserPrompt_799112d1ecb2,
  @UserComments = @UserComments_799112d1ecb2,
  @UserComments_Clear = 1,
  @Code = @Code_799112d1ecb2,
  @Code_Clear = 1,
  @CodeComments = @CodeComments_799112d1ecb2,
  @CodeComments_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_799112d1ecb2,
  @CodeApprovalComments = @CodeApprovalComments_799112d1ecb2,
  @CodeApprovalComments_Clear = 1,
  @CodeApprovedByUserID = @CodeApprovedByUserID_799112d1ecb2,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_799112d1ecb2,
  @CodeApprovedAt_Clear = 1,
  @CodeLocked = @CodeLocked_799112d1ecb2,
  @ForceCodeGeneration = @ForceCodeGeneration_799112d1ecb2,
  @RetentionPeriod = @RetentionPeriod_799112d1ecb2,
  @RetentionPeriod_Clear = 1,
  @Status = @Status_799112d1ecb2,
  @DriverClass = @DriverClass_799112d1ecb2,
  @ParentID = @ParentID_799112d1ecb2,
  @ParentID_Clear = 1,
  @IconClass = @IconClass_799112d1ecb2,
  @DefaultCompactPromptID = @DefaultCompactPromptID_799112d1ecb2,
  @DefaultCompactPromptID_Clear = 1,
  @Config = @Config_799112d1ecb2,
  @Config_Clear = 1,
  @RuntimeActionConfiguration = @RuntimeActionConfiguration_799112d1ecb2,
  @RuntimeActionConfiguration_Clear = 1,
  @MaxExecutionTimeMS = @MaxExecutionTimeMS_799112d1ecb2,
  @MaxExecutionTimeMS_Clear = 1,
  @CreatedByAgentID = @CreatedByAgentID_799112d1ecb2,
  @CreatedByAgentID_Clear = 1,
  @ID = @ID_799112d1ecb2;

GO
-- Save MJ: Action Params (core SP call only)
DECLARE @ActionID_2e77e76a5cac UNIQUEIDENTIFIER,
@Name_2e77e76a5cac NVARCHAR(255),
@DefaultValue_2e77e76a5cac NVARCHAR(MAX),
@Type_2e77e76a5cac NCHAR(10),
@ValueType_2e77e76a5cac NVARCHAR(30),
@IsArray_2e77e76a5cac BIT,
@Description_2e77e76a5cac NVARCHAR(MAX),
@IsRequired_2e77e76a5cac BIT,
@MediaModality_2e77e76a5cac NVARCHAR(20),
@LogValue_2e77e76a5cac BIT,
@ID_2e77e76a5cac UNIQUEIDENTIFIER
SET
  @ActionID_2e77e76a5cac = '896B0F83-AD89-4FC5-BDB9-330DE95AB3E4'
SET
  @Name_2e77e76a5cac = N'CompanyID'
SET
  @Type_2e77e76a5cac = N'Input'
SET
  @ValueType_2e77e76a5cac = N'Scalar'
SET
  @IsArray_2e77e76a5cac = 0
SET
  @Description_2e77e76a5cac = N'The order''s company, which issues its document. Naming any other company is refused with NOT_ORDER_COMPANY. Omit to render the order''s document.'
SET
  @IsRequired_2e77e76a5cac = 0
SET
  @LogValue_2e77e76a5cac = 1
SET
  @ID_2e77e76a5cac = '6F3C65E4-890A-446A-986F-3BCD857999C3'
SELECT TOP 1 @ActionID_2e77e76a5cac = [ID] FROM [${mjSchema}].[Action] WHERE [DriverClass] = N'Orders.GenerateInvoice' ORDER BY CASE WHEN [ID] = @ActionID_2e77e76a5cac THEN 0 ELSE 1 END
SELECT TOP 1 @ID_2e77e76a5cac = [ID] FROM [${mjSchema}].[ActionParam] WHERE [ActionID] = @ActionID_2e77e76a5cac AND [Name] = @Name_2e77e76a5cac ORDER BY CASE WHEN [ID] = @ID_2e77e76a5cac THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateActionParam @ActionID = @ActionID_2e77e76a5cac,
  @Name = @Name_2e77e76a5cac,
  @DefaultValue = @DefaultValue_2e77e76a5cac,
  @DefaultValue_Clear = 1,
  @Type = @Type_2e77e76a5cac,
  @ValueType = @ValueType_2e77e76a5cac,
  @IsArray = @IsArray_2e77e76a5cac,
  @Description = @Description_2e77e76a5cac,
  @IsRequired = @IsRequired_2e77e76a5cac,
  @MediaModality = @MediaModality_2e77e76a5cac,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_2e77e76a5cac,
  @ID = @ID_2e77e76a5cac;

GO
-- Save MJ: Action Params (core SP call only)
DECLARE @ActionID_1c00c91de327 UNIQUEIDENTIFIER,
@Name_1c00c91de327 NVARCHAR(255),
@DefaultValue_1c00c91de327 NVARCHAR(MAX),
@Type_1c00c91de327 NCHAR(10),
@ValueType_1c00c91de327 NVARCHAR(30),
@IsArray_1c00c91de327 BIT,
@Description_1c00c91de327 NVARCHAR(MAX),
@IsRequired_1c00c91de327 BIT,
@MediaModality_1c00c91de327 NVARCHAR(20),
@LogValue_1c00c91de327 BIT,
@ID_1c00c91de327 UNIQUEIDENTIFIER
SET
  @ActionID_1c00c91de327 = '896B0F83-AD89-4FC5-BDB9-330DE95AB3E4'
SET
  @Name_1c00c91de327 = N'HTML'
SET
  @Type_1c00c91de327 = N'Output'
SET
  @ValueType_1c00c91de327 = N'Scalar'
SET
  @IsArray_1c00c91de327 = 0
SET
  @Description_1c00c91de327 = N'The rendered document. NULL if a render ever produced more than one, rather than handing back the first as though it were the whole bill.'
SET
  @IsRequired_1c00c91de327 = 0
SET
  @LogValue_1c00c91de327 = 1
SET
  @ID_1c00c91de327 = '8E24A600-C4AE-42BE-A392-8FBA8731B565'
SELECT TOP 1 @ActionID_1c00c91de327 = [ID] FROM [${mjSchema}].[Action] WHERE [DriverClass] = N'Orders.GenerateInvoice' ORDER BY CASE WHEN [ID] = @ActionID_1c00c91de327 THEN 0 ELSE 1 END
SELECT TOP 1 @ID_1c00c91de327 = [ID] FROM [${mjSchema}].[ActionParam] WHERE [ActionID] = @ActionID_1c00c91de327 AND [Name] = @Name_1c00c91de327 ORDER BY CASE WHEN [ID] = @ID_1c00c91de327 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateActionParam @ActionID = @ActionID_1c00c91de327,
  @Name = @Name_1c00c91de327,
  @DefaultValue = @DefaultValue_1c00c91de327,
  @DefaultValue_Clear = 1,
  @Type = @Type_1c00c91de327,
  @ValueType = @ValueType_1c00c91de327,
  @IsArray = @IsArray_1c00c91de327,
  @Description = @Description_1c00c91de327,
  @IsRequired = @IsRequired_1c00c91de327,
  @MediaModality = @MediaModality_1c00c91de327,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_1c00c91de327,
  @ID = @ID_1c00c91de327;

GO
-- Save MJ: Action Params (core SP call only)
DECLARE @ActionID_cb5b012e8d9c UNIQUEIDENTIFIER,
@Name_cb5b012e8d9c NVARCHAR(255),
@DefaultValue_cb5b012e8d9c NVARCHAR(MAX),
@Type_cb5b012e8d9c NCHAR(10),
@ValueType_cb5b012e8d9c NVARCHAR(30),
@IsArray_cb5b012e8d9c BIT,
@Description_cb5b012e8d9c NVARCHAR(MAX),
@IsRequired_cb5b012e8d9c BIT,
@MediaModality_cb5b012e8d9c NVARCHAR(20),
@LogValue_cb5b012e8d9c BIT,
@ID_cb5b012e8d9c UNIQUEIDENTIFIER
SET
  @ActionID_cb5b012e8d9c = '896B0F83-AD89-4FC5-BDB9-330DE95AB3E4'
SET
  @Name_cb5b012e8d9c = N'DocumentCount'
SET
  @Type_cb5b012e8d9c = N'Output'
SET
  @ValueType_cb5b012e8d9c = N'Scalar'
SET
  @IsArray_cb5b012e8d9c = 0
SET
  @Description_cb5b012e8d9c = N'How many documents this order produced: one, from the order''s company.'
SET
  @IsRequired_cb5b012e8d9c = 0
SET
  @LogValue_cb5b012e8d9c = 1
SET
  @ID_cb5b012e8d9c = '2BABEA0E-C323-453F-89DD-F0F3ED292998'
SELECT TOP 1 @ActionID_cb5b012e8d9c = [ID] FROM [${mjSchema}].[Action] WHERE [DriverClass] = N'Orders.GenerateInvoice' ORDER BY CASE WHEN [ID] = @ActionID_cb5b012e8d9c THEN 0 ELSE 1 END
SELECT TOP 1 @ID_cb5b012e8d9c = [ID] FROM [${mjSchema}].[ActionParam] WHERE [ActionID] = @ActionID_cb5b012e8d9c AND [Name] = @Name_cb5b012e8d9c ORDER BY CASE WHEN [ID] = @ID_cb5b012e8d9c THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateActionParam @ActionID = @ActionID_cb5b012e8d9c,
  @Name = @Name_cb5b012e8d9c,
  @DefaultValue = @DefaultValue_cb5b012e8d9c,
  @DefaultValue_Clear = 1,
  @Type = @Type_cb5b012e8d9c,
  @ValueType = @ValueType_cb5b012e8d9c,
  @IsArray = @IsArray_cb5b012e8d9c,
  @Description = @Description_cb5b012e8d9c,
  @IsRequired = @IsRequired_cb5b012e8d9c,
  @MediaModality = @MediaModality_cb5b012e8d9c,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_cb5b012e8d9c,
  @ID = @ID_cb5b012e8d9c;

GO
