-- ProductPrice: required Name, hang on Product XOR Product Category, JSON applicability.
-- RUN CODEGEN AFTER THIS.
--
-- Applicability JSON (NULL = always applies) is a CompositeFilterDescriptor:
--   { "logic": "and", "filters": [
--       { "field": "BillToOrganization.Type", "operator": "eq", "value": "Member" }
--   ]}
-- Dotted field names are Source.Field. Bare names (legacy) are still readable.

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice] ADD [Name] NVARCHAR(100) NULL;
GO

UPDATE [__mj_BizAppsOrders].[ProductPrice]
SET [Name] = LEFT(
    COALESCE(
        NULLIF(LTRIM(RTRIM([Description])), ''),
        CONCAT('Price ', CONVERT(varchar(24), [Amount]))
    ),
    100
);
GO

;WITH d AS (
    SELECT
        ID,
        Name,
        ROW_NUMBER() OVER (PARTITION BY ProductID, Name ORDER BY Priority DESC, ID) AS rn
    FROM [__mj_BizAppsOrders].[ProductPrice]
)
UPDATE p
SET Name = LEFT(CONCAT(d.Name, ' (', d.rn, ')'), 100)
FROM [__mj_BizAppsOrders].[ProductPrice] p
INNER JOIN d ON d.ID = p.ID
WHERE d.rn > 1;
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice]
    ALTER COLUMN [Name] NVARCHAR(100) NOT NULL;
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice] ADD [ProductCategoryID] UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice]
    ALTER COLUMN [ProductID] UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice]
    ADD CONSTRAINT CK_ProductPrice_Scope CHECK (
        ([ProductID] IS NOT NULL AND [ProductCategoryID] IS NULL)
        OR
        ([ProductID] IS NULL AND [ProductCategoryID] IS NOT NULL)
    );
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice]
    ADD CONSTRAINT FK_ProductPrice_ProductCategory
    FOREIGN KEY ([ProductCategoryID]) REFERENCES [__mj_BizAppsOrders].[ProductCategory]([ID]);
GO

CREATE UNIQUE INDEX UX_ProductPrice_Product_Name
    ON [__mj_BizAppsOrders].[ProductPrice] ([ProductID], [Name])
    WHERE [ProductID] IS NOT NULL;
GO

CREATE UNIQUE INDEX UX_ProductPrice_Category_Name
    ON [__mj_BizAppsOrders].[ProductPrice] ([ProductCategoryID], [Name])
    WHERE [ProductCategoryID] IS NOT NULL;
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice] ADD [Applicability] NVARCHAR(MAX) NULL;
GO

ALTER TABLE [__mj_BizAppsOrders].[ProductPrice]
    ADD CONSTRAINT CK_ProductPrice_Applicability_JSON CHECK (
        [Applicability] IS NULL OR ISJSON([Applicability]) = 1
    );
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Staff-facing name of this price (Member, Non-member, Early bird). Unique per product or per category.',
    @level0type = N'SCHEMA', @level0name = N'__mj_BizAppsOrders',
    @level1type = N'TABLE',  @level1name = N'ProductPrice',
    @level2type = N'COLUMN', @level2name = N'Name';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'When set, this price hangs on a Product Category and is inherited by products in that tree unless a same-Name row exists on the product. Exactly one of ProductID or ProductCategoryID.',
    @level0type = N'SCHEMA', @level0name = N'__mj_BizAppsOrders',
    @level1type = N'TABLE',  @level1name = N'ProductPrice',
    @level2type = N'COLUMN', @level2name = N'ProductCategoryID';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'CompositeFilterDescriptor JSON (Kendo / mj-filter-builder). Null = always applies. Field names are Source.Field (e.g. BillToOrganization.Type). Evaluated in memory against Order, Product, bill-to/ship-to Person/Organization/Address.',
    @level0type = N'SCHEMA', @level0name = N'__mj_BizAppsOrders',
    @level1type = N'TABLE',  @level1name = N'ProductPrice',
    @level2type = N'COLUMN', @level2name = N'Applicability';
GO

-- CodeGen output (Product Prices view, FKs, SPs)
/* Index for Foreign Keys for ProductPrice */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Prices
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ProductID in table ProductPrice
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ProductPrice_ProductID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ProductPrice]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ProductPrice_ProductID ON [${flyway:defaultSchema}].[ProductPrice] ([ProductID]);

-- Index for foreign key PriceListID in table ProductPrice
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ProductPrice_PriceListID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ProductPrice]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ProductPrice_PriceListID ON [${flyway:defaultSchema}].[ProductPrice] ([PriceListID]);

-- Index for foreign key ProductCategoryID in table ProductPrice
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ProductPrice_ProductCategoryID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ProductPrice]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ProductPrice_ProductCategoryID ON [${flyway:defaultSchema}].[ProductPrice] ([ProductCategoryID]);

/* SQL text to update entity field related entity name field map for entity field ID F76B9D6E-5C2E-44CA-AA68-17E4922E8E47 */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='F76B9D6E-5C2E-44CA-AA68-17E4922E8E47', @RelatedEntityNameFieldMap='ProductCategory';

/* Base View SQL for MJ_BizApps_Orders: Product Categories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Categories
-- Item: vwProductCategories
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Orders: Product Categories
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ProductCategory
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwProductCategories]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwProductCategories];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwProductCategories]
AS
SELECT
    p.*,
    MJCompany_CompanyID.[Name] AS [Company],
    mjBizAppsOrdersProductCategory_ParentProductCategoryID.[Name] AS [ParentProductCategory]
FROM
    [${flyway:defaultSchema}].[ProductCategory] AS p
INNER JOIN
    [${mjSchema}].[Company] AS MJCompany_CompanyID
  ON
    [p].[CompanyID] = MJCompany_CompanyID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ProductCategory] AS mjBizAppsOrdersProductCategory_ParentProductCategoryID
  ON
    [p].[ParentProductCategoryID] = mjBizAppsOrdersProductCategory_ParentProductCategoryID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwProductCategories] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Orders: Product Categories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Categories
-- Item: Permissions for vwProductCategories
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwProductCategories] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Orders: Product Categories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Categories
-- Item: spCreateProductCategory
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ProductCategory
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateProductCategory]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateProductCategory];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateProductCategory]
    @ID uniqueidentifier = NULL,
    @CompanyID uniqueidentifier,
    @Code_Clear bit = 0,
    @Code nvarchar(40) = NULL,
    @Name nvarchar(200),
    @ParentProductCategoryID_Clear bit = 0,
    @ParentProductCategoryID uniqueidentifier = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @IsActive bit = NULL,
    @DefaultIsTaxable_Clear bit = 0,
    @DefaultIsTaxable bit = NULL,
    @DefaultTaxCategory_Clear bit = 0,
    @DefaultTaxCategory nvarchar(50) = NULL,
    @DefaultEntitlementGrantTiming_Clear bit = 0,
    @DefaultEntitlementGrantTiming nvarchar(20) = NULL,
    @DefaultEntitlementQuantityMode_Clear bit = 0,
    @DefaultEntitlementQuantityMode nvarchar(20) = NULL,
    @DefaultEntitlementValidityMode_Clear bit = 0,
    @DefaultEntitlementValidityMode nvarchar(20) = NULL,
    @PricingDriverClass_Clear bit = 0,
    @PricingDriverClass nvarchar(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ProductCategory]
            (
                [ID],
                [CompanyID],
                [Code],
                [Name],
                [ParentProductCategoryID],
                [Description],
                [IsActive],
                [DefaultIsTaxable],
                [DefaultTaxCategory],
                [DefaultEntitlementGrantTiming],
                [DefaultEntitlementQuantityMode],
                [DefaultEntitlementValidityMode],
                [PricingDriverClass]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @CompanyID,
                CASE WHEN @Code_Clear = 1 THEN NULL ELSE ISNULL(@Code, NULL) END,
                @Name,
                CASE WHEN @ParentProductCategoryID_Clear = 1 THEN NULL ELSE ISNULL(@ParentProductCategoryID, NULL) END,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                ISNULL(@IsActive, 1),
                CASE WHEN @DefaultIsTaxable_Clear = 1 THEN NULL ELSE ISNULL(@DefaultIsTaxable, NULL) END,
                CASE WHEN @DefaultTaxCategory_Clear = 1 THEN NULL ELSE ISNULL(@DefaultTaxCategory, NULL) END,
                CASE WHEN @DefaultEntitlementGrantTiming_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementGrantTiming, NULL) END,
                CASE WHEN @DefaultEntitlementQuantityMode_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementQuantityMode, NULL) END,
                CASE WHEN @DefaultEntitlementValidityMode_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementValidityMode, NULL) END,
                CASE WHEN @PricingDriverClass_Clear = 1 THEN NULL ELSE ISNULL(@PricingDriverClass, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ProductCategory]
            (
                [CompanyID],
                [Code],
                [Name],
                [ParentProductCategoryID],
                [Description],
                [IsActive],
                [DefaultIsTaxable],
                [DefaultTaxCategory],
                [DefaultEntitlementGrantTiming],
                [DefaultEntitlementQuantityMode],
                [DefaultEntitlementValidityMode],
                [PricingDriverClass]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @CompanyID,
                CASE WHEN @Code_Clear = 1 THEN NULL ELSE ISNULL(@Code, NULL) END,
                @Name,
                CASE WHEN @ParentProductCategoryID_Clear = 1 THEN NULL ELSE ISNULL(@ParentProductCategoryID, NULL) END,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                ISNULL(@IsActive, 1),
                CASE WHEN @DefaultIsTaxable_Clear = 1 THEN NULL ELSE ISNULL(@DefaultIsTaxable, NULL) END,
                CASE WHEN @DefaultTaxCategory_Clear = 1 THEN NULL ELSE ISNULL(@DefaultTaxCategory, NULL) END,
                CASE WHEN @DefaultEntitlementGrantTiming_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementGrantTiming, NULL) END,
                CASE WHEN @DefaultEntitlementQuantityMode_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementQuantityMode, NULL) END,
                CASE WHEN @DefaultEntitlementValidityMode_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementValidityMode, NULL) END,
                CASE WHEN @PricingDriverClass_Clear = 1 THEN NULL ELSE ISNULL(@PricingDriverClass, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwProductCategories] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateProductCategory] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Orders: Product Categories */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateProductCategory] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Orders: Product Categories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Categories
-- Item: spUpdateProductCategory
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ProductCategory
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateProductCategory]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateProductCategory];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateProductCategory]
    @ID uniqueidentifier,
    @CompanyID uniqueidentifier = NULL,
    @Code_Clear bit = 0,
    @Code nvarchar(40) = NULL,
    @Name nvarchar(200) = NULL,
    @ParentProductCategoryID_Clear bit = 0,
    @ParentProductCategoryID uniqueidentifier = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @IsActive bit = NULL,
    @DefaultIsTaxable_Clear bit = 0,
    @DefaultIsTaxable bit = NULL,
    @DefaultTaxCategory_Clear bit = 0,
    @DefaultTaxCategory nvarchar(50) = NULL,
    @DefaultEntitlementGrantTiming_Clear bit = 0,
    @DefaultEntitlementGrantTiming nvarchar(20) = NULL,
    @DefaultEntitlementQuantityMode_Clear bit = 0,
    @DefaultEntitlementQuantityMode nvarchar(20) = NULL,
    @DefaultEntitlementValidityMode_Clear bit = 0,
    @DefaultEntitlementValidityMode nvarchar(20) = NULL,
    @PricingDriverClass_Clear bit = 0,
    @PricingDriverClass nvarchar(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ProductCategory]
    SET
        [CompanyID] = ISNULL(@CompanyID, [CompanyID]),
        [Code] = CASE WHEN @Code_Clear = 1 THEN NULL ELSE ISNULL(@Code, [Code]) END,
        [Name] = ISNULL(@Name, [Name]),
        [ParentProductCategoryID] = CASE WHEN @ParentProductCategoryID_Clear = 1 THEN NULL ELSE ISNULL(@ParentProductCategoryID, [ParentProductCategoryID]) END,
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [IsActive] = ISNULL(@IsActive, [IsActive]),
        [DefaultIsTaxable] = CASE WHEN @DefaultIsTaxable_Clear = 1 THEN NULL ELSE ISNULL(@DefaultIsTaxable, [DefaultIsTaxable]) END,
        [DefaultTaxCategory] = CASE WHEN @DefaultTaxCategory_Clear = 1 THEN NULL ELSE ISNULL(@DefaultTaxCategory, [DefaultTaxCategory]) END,
        [DefaultEntitlementGrantTiming] = CASE WHEN @DefaultEntitlementGrantTiming_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementGrantTiming, [DefaultEntitlementGrantTiming]) END,
        [DefaultEntitlementQuantityMode] = CASE WHEN @DefaultEntitlementQuantityMode_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementQuantityMode, [DefaultEntitlementQuantityMode]) END,
        [DefaultEntitlementValidityMode] = CASE WHEN @DefaultEntitlementValidityMode_Clear = 1 THEN NULL ELSE ISNULL(@DefaultEntitlementValidityMode, [DefaultEntitlementValidityMode]) END,
        [PricingDriverClass] = CASE WHEN @PricingDriverClass_Clear = 1 THEN NULL ELSE ISNULL(@PricingDriverClass, [PricingDriverClass]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwProductCategories] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwProductCategories]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateProductCategory] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ProductCategory table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateProductCategory]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateProductCategory];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateProductCategory
ON [${flyway:defaultSchema}].[ProductCategory]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ProductCategory]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ProductCategory] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Orders: Product Categories */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateProductCategory] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Orders: Product Categories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Categories
-- Item: spDeleteProductCategory
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ProductCategory
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteProductCategory]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteProductCategory];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteProductCategory]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ProductCategory]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteProductCategory] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Orders: Product Categories */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteProductCategory] TO [cdp_Developer], [cdp_Integration];

/* Base View SQL for MJ_BizApps_Orders: Product Prices */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Prices
-- Item: vwProductPrices
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Orders: Product Prices
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ProductPrice
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwProductPrices]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwProductPrices];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwProductPrices]
AS
SELECT
    p.*,
    mjBizAppsOrdersProduct_ProductID.[Name] AS [Product],
    mjBizAppsOrdersPriceList_PriceListID.[Name] AS [PriceList],
    mjBizAppsOrdersProductCategory_ProductCategoryID.[Name] AS [ProductCategory]
FROM
    [${flyway:defaultSchema}].[ProductPrice] AS p
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Product] AS mjBizAppsOrdersProduct_ProductID
  ON
    [p].[ProductID] = mjBizAppsOrdersProduct_ProductID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[PriceList] AS mjBizAppsOrdersPriceList_PriceListID
  ON
    [p].[PriceListID] = mjBizAppsOrdersPriceList_PriceListID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ProductCategory] AS mjBizAppsOrdersProductCategory_ProductCategoryID
  ON
    [p].[ProductCategoryID] = mjBizAppsOrdersProductCategory_ProductCategoryID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwProductPrices] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Orders: Product Prices */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Prices
-- Item: Permissions for vwProductPrices
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwProductPrices] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Orders: Product Prices */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Prices
-- Item: spCreateProductPrice
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ProductPrice
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateProductPrice]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateProductPrice];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateProductPrice]
    @ID uniqueidentifier = NULL,
    @ProductID_Clear bit = 0,
    @ProductID uniqueidentifier = NULL,
    @PriceListID_Clear bit = 0,
    @PriceListID uniqueidentifier = NULL,
    @PricingModel nvarchar(20) = NULL,
    @FeeType nvarchar(20) = NULL,
    @Amount decimal(19, 4),
    @UnitOfMeasure_Clear bit = 0,
    @UnitOfMeasure nvarchar(40) = NULL,
    @PackageQuantity_Clear bit = 0,
    @PackageQuantity decimal(18, 4) = NULL,
    @MinQuantity_Clear bit = 0,
    @MinQuantity decimal(18, 4) = NULL,
    @MaxQuantity_Clear bit = 0,
    @MaxQuantity decimal(18, 4) = NULL,
    @EffectiveFrom date,
    @EffectiveTo_Clear bit = 0,
    @EffectiveTo date = NULL,
    @RecurrenceMonths_Clear bit = 0,
    @RecurrenceMonths nvarchar(40) = NULL,
    @RecurrenceDaysOfWeek_Clear bit = 0,
    @RecurrenceDaysOfWeek nvarchar(20) = NULL,
    @RecurrenceDayOfMonthMin_Clear bit = 0,
    @RecurrenceDayOfMonthMin tinyint = NULL,
    @RecurrenceDayOfMonthMax_Clear bit = 0,
    @RecurrenceDayOfMonthMax tinyint = NULL,
    @TimeOfDayStart_Clear bit = 0,
    @TimeOfDayStart time = NULL,
    @TimeOfDayEnd_Clear bit = 0,
    @TimeOfDayEnd time = NULL,
    @Priority int = NULL,
    @Status nvarchar(10) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @Name nvarchar(100),
    @ProductCategoryID_Clear bit = 0,
    @ProductCategoryID uniqueidentifier = NULL,
    @Applicability_Clear bit = 0,
    @Applicability nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ProductPrice]
            (
                [ID],
                [ProductID],
                [PriceListID],
                [PricingModel],
                [FeeType],
                [Amount],
                [UnitOfMeasure],
                [PackageQuantity],
                [MinQuantity],
                [MaxQuantity],
                [EffectiveFrom],
                [EffectiveTo],
                [RecurrenceMonths],
                [RecurrenceDaysOfWeek],
                [RecurrenceDayOfMonthMin],
                [RecurrenceDayOfMonthMax],
                [TimeOfDayStart],
                [TimeOfDayEnd],
                [Priority],
                [Status],
                [Description],
                [Name],
                [ProductCategoryID],
                [Applicability]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                CASE WHEN @ProductID_Clear = 1 THEN NULL ELSE ISNULL(@ProductID, NULL) END,
                CASE WHEN @PriceListID_Clear = 1 THEN NULL ELSE ISNULL(@PriceListID, NULL) END,
                ISNULL(@PricingModel, 'Flat'),
                ISNULL(@FeeType, 'Standard'),
                @Amount,
                CASE WHEN @UnitOfMeasure_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfMeasure, NULL) END,
                CASE WHEN @PackageQuantity_Clear = 1 THEN NULL ELSE ISNULL(@PackageQuantity, NULL) END,
                CASE WHEN @MinQuantity_Clear = 1 THEN NULL ELSE ISNULL(@MinQuantity, NULL) END,
                CASE WHEN @MaxQuantity_Clear = 1 THEN NULL ELSE ISNULL(@MaxQuantity, NULL) END,
                @EffectiveFrom,
                CASE WHEN @EffectiveTo_Clear = 1 THEN NULL ELSE ISNULL(@EffectiveTo, NULL) END,
                CASE WHEN @RecurrenceMonths_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceMonths, NULL) END,
                CASE WHEN @RecurrenceDaysOfWeek_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDaysOfWeek, NULL) END,
                CASE WHEN @RecurrenceDayOfMonthMin_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDayOfMonthMin, NULL) END,
                CASE WHEN @RecurrenceDayOfMonthMax_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDayOfMonthMax, NULL) END,
                CASE WHEN @TimeOfDayStart_Clear = 1 THEN NULL ELSE ISNULL(@TimeOfDayStart, NULL) END,
                CASE WHEN @TimeOfDayEnd_Clear = 1 THEN NULL ELSE ISNULL(@TimeOfDayEnd, NULL) END,
                ISNULL(@Priority, 0),
                ISNULL(@Status, 'Active'),
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @Name,
                CASE WHEN @ProductCategoryID_Clear = 1 THEN NULL ELSE ISNULL(@ProductCategoryID, NULL) END,
                CASE WHEN @Applicability_Clear = 1 THEN NULL ELSE ISNULL(@Applicability, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ProductPrice]
            (
                [ProductID],
                [PriceListID],
                [PricingModel],
                [FeeType],
                [Amount],
                [UnitOfMeasure],
                [PackageQuantity],
                [MinQuantity],
                [MaxQuantity],
                [EffectiveFrom],
                [EffectiveTo],
                [RecurrenceMonths],
                [RecurrenceDaysOfWeek],
                [RecurrenceDayOfMonthMin],
                [RecurrenceDayOfMonthMax],
                [TimeOfDayStart],
                [TimeOfDayEnd],
                [Priority],
                [Status],
                [Description],
                [Name],
                [ProductCategoryID],
                [Applicability]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                CASE WHEN @ProductID_Clear = 1 THEN NULL ELSE ISNULL(@ProductID, NULL) END,
                CASE WHEN @PriceListID_Clear = 1 THEN NULL ELSE ISNULL(@PriceListID, NULL) END,
                ISNULL(@PricingModel, 'Flat'),
                ISNULL(@FeeType, 'Standard'),
                @Amount,
                CASE WHEN @UnitOfMeasure_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfMeasure, NULL) END,
                CASE WHEN @PackageQuantity_Clear = 1 THEN NULL ELSE ISNULL(@PackageQuantity, NULL) END,
                CASE WHEN @MinQuantity_Clear = 1 THEN NULL ELSE ISNULL(@MinQuantity, NULL) END,
                CASE WHEN @MaxQuantity_Clear = 1 THEN NULL ELSE ISNULL(@MaxQuantity, NULL) END,
                @EffectiveFrom,
                CASE WHEN @EffectiveTo_Clear = 1 THEN NULL ELSE ISNULL(@EffectiveTo, NULL) END,
                CASE WHEN @RecurrenceMonths_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceMonths, NULL) END,
                CASE WHEN @RecurrenceDaysOfWeek_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDaysOfWeek, NULL) END,
                CASE WHEN @RecurrenceDayOfMonthMin_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDayOfMonthMin, NULL) END,
                CASE WHEN @RecurrenceDayOfMonthMax_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDayOfMonthMax, NULL) END,
                CASE WHEN @TimeOfDayStart_Clear = 1 THEN NULL ELSE ISNULL(@TimeOfDayStart, NULL) END,
                CASE WHEN @TimeOfDayEnd_Clear = 1 THEN NULL ELSE ISNULL(@TimeOfDayEnd, NULL) END,
                ISNULL(@Priority, 0),
                ISNULL(@Status, 'Active'),
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @Name,
                CASE WHEN @ProductCategoryID_Clear = 1 THEN NULL ELSE ISNULL(@ProductCategoryID, NULL) END,
                CASE WHEN @Applicability_Clear = 1 THEN NULL ELSE ISNULL(@Applicability, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwProductPrices] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateProductPrice] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Orders: Product Prices */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateProductPrice] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Orders: Product Prices */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Prices
-- Item: spUpdateProductPrice
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ProductPrice
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateProductPrice]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateProductPrice];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateProductPrice]
    @ID uniqueidentifier,
    @ProductID_Clear bit = 0,
    @ProductID uniqueidentifier = NULL,
    @PriceListID_Clear bit = 0,
    @PriceListID uniqueidentifier = NULL,
    @PricingModel nvarchar(20) = NULL,
    @FeeType nvarchar(20) = NULL,
    @Amount decimal(19, 4) = NULL,
    @UnitOfMeasure_Clear bit = 0,
    @UnitOfMeasure nvarchar(40) = NULL,
    @PackageQuantity_Clear bit = 0,
    @PackageQuantity decimal(18, 4) = NULL,
    @MinQuantity_Clear bit = 0,
    @MinQuantity decimal(18, 4) = NULL,
    @MaxQuantity_Clear bit = 0,
    @MaxQuantity decimal(18, 4) = NULL,
    @EffectiveFrom date = NULL,
    @EffectiveTo_Clear bit = 0,
    @EffectiveTo date = NULL,
    @RecurrenceMonths_Clear bit = 0,
    @RecurrenceMonths nvarchar(40) = NULL,
    @RecurrenceDaysOfWeek_Clear bit = 0,
    @RecurrenceDaysOfWeek nvarchar(20) = NULL,
    @RecurrenceDayOfMonthMin_Clear bit = 0,
    @RecurrenceDayOfMonthMin tinyint = NULL,
    @RecurrenceDayOfMonthMax_Clear bit = 0,
    @RecurrenceDayOfMonthMax tinyint = NULL,
    @TimeOfDayStart_Clear bit = 0,
    @TimeOfDayStart time = NULL,
    @TimeOfDayEnd_Clear bit = 0,
    @TimeOfDayEnd time = NULL,
    @Priority int = NULL,
    @Status nvarchar(10) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @Name nvarchar(100) = NULL,
    @ProductCategoryID_Clear bit = 0,
    @ProductCategoryID uniqueidentifier = NULL,
    @Applicability_Clear bit = 0,
    @Applicability nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ProductPrice]
    SET
        [ProductID] = CASE WHEN @ProductID_Clear = 1 THEN NULL ELSE ISNULL(@ProductID, [ProductID]) END,
        [PriceListID] = CASE WHEN @PriceListID_Clear = 1 THEN NULL ELSE ISNULL(@PriceListID, [PriceListID]) END,
        [PricingModel] = ISNULL(@PricingModel, [PricingModel]),
        [FeeType] = ISNULL(@FeeType, [FeeType]),
        [Amount] = ISNULL(@Amount, [Amount]),
        [UnitOfMeasure] = CASE WHEN @UnitOfMeasure_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfMeasure, [UnitOfMeasure]) END,
        [PackageQuantity] = CASE WHEN @PackageQuantity_Clear = 1 THEN NULL ELSE ISNULL(@PackageQuantity, [PackageQuantity]) END,
        [MinQuantity] = CASE WHEN @MinQuantity_Clear = 1 THEN NULL ELSE ISNULL(@MinQuantity, [MinQuantity]) END,
        [MaxQuantity] = CASE WHEN @MaxQuantity_Clear = 1 THEN NULL ELSE ISNULL(@MaxQuantity, [MaxQuantity]) END,
        [EffectiveFrom] = ISNULL(@EffectiveFrom, [EffectiveFrom]),
        [EffectiveTo] = CASE WHEN @EffectiveTo_Clear = 1 THEN NULL ELSE ISNULL(@EffectiveTo, [EffectiveTo]) END,
        [RecurrenceMonths] = CASE WHEN @RecurrenceMonths_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceMonths, [RecurrenceMonths]) END,
        [RecurrenceDaysOfWeek] = CASE WHEN @RecurrenceDaysOfWeek_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDaysOfWeek, [RecurrenceDaysOfWeek]) END,
        [RecurrenceDayOfMonthMin] = CASE WHEN @RecurrenceDayOfMonthMin_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDayOfMonthMin, [RecurrenceDayOfMonthMin]) END,
        [RecurrenceDayOfMonthMax] = CASE WHEN @RecurrenceDayOfMonthMax_Clear = 1 THEN NULL ELSE ISNULL(@RecurrenceDayOfMonthMax, [RecurrenceDayOfMonthMax]) END,
        [TimeOfDayStart] = CASE WHEN @TimeOfDayStart_Clear = 1 THEN NULL ELSE ISNULL(@TimeOfDayStart, [TimeOfDayStart]) END,
        [TimeOfDayEnd] = CASE WHEN @TimeOfDayEnd_Clear = 1 THEN NULL ELSE ISNULL(@TimeOfDayEnd, [TimeOfDayEnd]) END,
        [Priority] = ISNULL(@Priority, [Priority]),
        [Status] = ISNULL(@Status, [Status]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [Name] = ISNULL(@Name, [Name]),
        [ProductCategoryID] = CASE WHEN @ProductCategoryID_Clear = 1 THEN NULL ELSE ISNULL(@ProductCategoryID, [ProductCategoryID]) END,
        [Applicability] = CASE WHEN @Applicability_Clear = 1 THEN NULL ELSE ISNULL(@Applicability, [Applicability]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwProductPrices] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwProductPrices]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateProductPrice] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ProductPrice table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateProductPrice]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateProductPrice];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateProductPrice
ON [${flyway:defaultSchema}].[ProductPrice]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ProductPrice]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ProductPrice] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Orders: Product Prices */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateProductPrice] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Orders: Product Prices */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Product Prices
-- Item: spDeleteProductPrice
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ProductPrice
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteProductPrice]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteProductPrice];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteProductPrice]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ProductPrice]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteProductPrice] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Orders: Product Prices */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteProductPrice] TO [cdp_Developer], [cdp_Integration];
