-- =============================================================================
-- V202609291303 — Foreign key from OrderLine.ShipToAddressID to Address
-- (bizapps-orders#261)
-- =============================================================================
-- OrderLine.ShipToAddressID names a __mj_BizAppsCommon.Address row but had no
-- constraint, unlike OrderHeader.BillToAddressID / ShipToAddressID and the line's
-- other ship-to columns. With no constraint there was also no entity
-- relationship, so a dependency check on an Address did not see the lines that
-- use it: the Address could be deleted and the line left naming a row that no
-- longer exists.
--
-- No ON DELETE action, the same as FK_OrderHeader_ShipToAddress: an Address a
-- line still names cannot be deleted. SET NULL is not an option in any case,
-- because trg_OrderLine_ImmutableAfterConfirm (51016) refuses clearing a
-- Confirmed order's line address.
--
-- The constraint is created WITH CHECK, so this migration fails on a database
-- that already has a line naming a missing Address. Such a line has to be
-- repaired before this runs.
--
-- EntityField.RelatedEntityID for the column is set from the constraint by the
-- metadata refresh that runs after migrations. CodeGen's entity relationship
-- and foreign-key index are folded below the banner at the end of this file.
-- =============================================================================

ALTER TABLE [${flyway:defaultSchema}].[OrderLine]
    ADD CONSTRAINT [FK_OrderLine_ShipToAddress]
    FOREIGN KEY ([ShipToAddressID]) REFERENCES [__mj_BizAppsCommon].[Address]([ID]);
GO


















































-- =============================================================================
-- CODEGEN OUTPUT — GENERATED CODE BELOW THIS LINE. DO NOT EDIT BY HAND.
-- This app's own CodeGen SQL for FK_OrderLine_ShipToAddress: the Addresses ->
-- Order Lines entity relationship and the foreign-key index.
-- =============================================================================
/* Create Entity Relationship: MJ_BizApps_Common: Addresses -> MJ_BizApps_Orders: Order Lines (One To Many via ShipToAddressID) */
   IF NOT EXISTS (
      SELECT 1 FROM [${mjSchema}].[EntityRelationship] WHERE [ID] = 'e8a74d06-51f1-4983-a2fc-d8fcd6399f1e'
   )
   BEGIN
      INSERT INTO [${mjSchema}].[EntityRelationship] ([ID], [EntityID], [RelatedEntityID], [RelatedEntityJoinField], [Type], [BundleInAPI], [DisplayInForm], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt])
                    VALUES ('e8a74d06-51f1-4983-a2fc-d8fcd6399f1e', '61B5C6FB-7317-46D1-8E05-F669B7BC6F3E', '66D82C24-9C9F-4CD6-B019-53C20274AB00', 'ShipToAddressID', 'One To Many', 1, 1, 6, GETUTCDATE(), GETUTCDATE())
   END;

/* Index for Foreign Keys for OrderLine */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Orders: Order Lines
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ShipToAddressID in table OrderLine
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_OrderLine_ShipToAddressID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[OrderLine]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_OrderLine_ShipToAddressID ON [${flyway:defaultSchema}].[OrderLine] ([ShipToAddressID]);
