-- =============================================================================================
-- BizApps Orders v5.29.x -- Metadata_Sync (one per release)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --ci` (MJ CLI 6.1.5) against a database built from
-- migrations ONLY: MJ core 6.1.5, bizapps-common v5.51.0, bizapps-tasks v1.6.2, bizapps-accounting
-- v0.21.1, then this app's migrations at `next`. Push result: 28 created, 6 updated, 447
-- unchanged, 0 errors. 18 of the creates are the ML bench (below).
--
-- CREATED (metadata/api-scopes, metadata/api-application-scopes): API scopes orders:read,
-- orders:write, orders:payments:refund, orders:payments:write and orders:subscriptions:write, each
-- a child of `orders`, and for each one an MJAPI application scope (`*`, Include).
--
-- UPDATED (6), checked column by column against a copy of the database taken before the push;
-- only RequiredScope changed:
--   * Orders.RefundPayment -> orders:payments:refund
--   * Orders.ApplyAccountCredit -> orders:payments:write
--   * Orders.CancelSubscription, Orders.SpawnRenewals, Orders.AmendArrangement and
--     Orders.DetectOverlappingSubscriptions -> orders:subscriptions:write
--
-- NOT INCLUDED: the ML bench output (ml-models, ml-training-pipelines, ml-model-scoring-bindings,
-- record-processes) and the scheduled jobs its record processes create, as in 5.20-5.28.
--
-- TRANSFORMS: `EXEC [__mj]` -> `EXEC [${mjSchema}]`; string values are untouched. IDs resolve on
-- the host: RemoteOperation by OperationKey, the parent scope and each scope by FullPath, the
-- MJAPI application by Name. Creates are guarded on ID or their key. Idempotent.
-- =============================================================================================
-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_e6e1f1776a4c NVARCHAR(255),
@OperationKey_e6e1f1776a4c NVARCHAR(255),
@CategoryID_e6e1f1776a4c UNIQUEIDENTIFIER,
@Description_e6e1f1776a4c NVARCHAR(MAX),
@InputTypeName_e6e1f1776a4c NVARCHAR(255),
@InputTypeDefinition_e6e1f1776a4c NVARCHAR(MAX),
@InputTypeIsArray_e6e1f1776a4c BIT,
@OutputTypeName_e6e1f1776a4c NVARCHAR(255),
@OutputTypeDefinition_e6e1f1776a4c NVARCHAR(MAX),
@OutputTypeIsArray_e6e1f1776a4c BIT,
@ExecutionMode_e6e1f1776a4c NVARCHAR(20),
@RequiredScope_e6e1f1776a4c NVARCHAR(255),
@RequiresSystemUser_e6e1f1776a4c BIT,
@GenerationType_e6e1f1776a4c NVARCHAR(20),
@Code_e6e1f1776a4c NVARCHAR(MAX),
@CodeApprovalStatus_e6e1f1776a4c NVARCHAR(20),
@CodeApprovedByUserID_e6e1f1776a4c UNIQUEIDENTIFIER,
@CodeApprovedAt_e6e1f1776a4c DATETIMEOFFSET,
@ContractFingerprint_e6e1f1776a4c NVARCHAR(100),
@Status_e6e1f1776a4c NVARCHAR(20),
@CacheTTLSeconds_e6e1f1776a4c INT,
@TimeoutMS_e6e1f1776a4c INT,
@MaxConcurrency_e6e1f1776a4c INT,
@CodeLocked_e6e1f1776a4c BIT,
@CodeComments_e6e1f1776a4c NVARCHAR(MAX),
@Libraries_e6e1f1776a4c NVARCHAR(MAX),
@ID_e6e1f1776a4c UNIQUEIDENTIFIER
SET
  @Name_e6e1f1776a4c = N'Detect Overlapping Subscriptions'
SET
  @OperationKey_e6e1f1776a4c = N'Orders.DetectOverlappingSubscriptions'
SET
  @CategoryID_e6e1f1776a4c = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B304'
SET
  @Description_e6e1f1776a4c = N'Raise a finance exception for each pair of live subscriptions for one holder whose terms overlap: the same product, or (when the exception type''s IncludeSameCategory setting is on) products in the same category with the same subscription type. Each overlap is billed and recognized twice unless one is cancelled. Reads its settings from the OVERLAPPING_SUBSCRIPTION exception type and does nothing when that type is missing or inactive. The source record is the later subscription and the creator is whoever confirmed the order that booked it; when no confirmer is recorded (an order confirmed before that was recorded, or no order), the exception has no creator restriction. Re-running is safe: a pair that already has an exception raises nothing new.'
SET
  @InputTypeName_e6e1f1776a4c = N'OrdersDetectOverlappingSubscriptionsInput'
SET
  @InputTypeDefinition_e6e1f1776a4c = N'/**
 * Input for `Orders.DetectOverlappingSubscriptions`.
 *
 * The nightly check behind finance exception type OVERLAPPING_SUBSCRIPTION: one exception per
 * pair of live subscriptions for one holder whose terms overlap, raised through accounting''s
 * `Accounting.RaiseFinanceExceptions`. Re-running is safe — an exception already raised for a
 * pair is left as it is.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface OrdersDetectOverlappingSubscriptionsInput {
    /**
     * The business day the exceptions are dated to (YYYY-MM-DD). Omit for today in the business
     * time zone, which is what the schedule uses.
     */
    AsOfDate?: string;
}
'
SET
  @InputTypeIsArray_e6e1f1776a4c = 0
SET
  @OutputTypeName_e6e1f1776a4c = N'OrdersDetectOverlappingSubscriptionsOutput'
SET
  @OutputTypeDefinition_e6e1f1776a4c = N'/**
 * Output for `Orders.DetectOverlappingSubscriptions`.
 *
 * Counts, plus every error, so an unattended run that raised nothing can be told apart from one
 * that found nothing.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface OverlappingSubscriptionsDetectionError {
    /** `<EarlierSubscriptionID>|<LaterSubscriptionID>` when the error belongs to one pair. */
    DedupeKey?: string;
    Code: string;
    Message: string;
}

export interface OrdersDetectOverlappingSubscriptionsOutput {
    /** False when any pair could not be raised; every reason is in Errors. */
    Success: boolean;
    Message?: string;
    /**
     * False when the OVERLAPPING_SUBSCRIPTION exception type is missing or inactive. The check then
     * does not run: the type''s configuration is the only source of its settings.
     */
    TypeActive: boolean;
    /** The business day the exceptions were dated to (YYYY-MM-DD). */
    ExceptionDate: string;
    /** Pairs the "Overlapping Subscriptions" query returned. */
    PairsFound: number;
    /** Pairs left after the IncludeSameCategory setting: the ones an exception was raised for. */
    PairsConsidered: number;
    /** Exceptions created by this run. */
    Created: number;
    /** Pairs that already had an exception, in any status. Left unchanged. */
    AlreadyRaised: number;
    /** Pairs accounting skipped. */
    Skipped: number;
    Errors: OverlappingSubscriptionsDetectionError[];
}
'
SET
  @OutputTypeIsArray_e6e1f1776a4c = 0
SET
  @ExecutionMode_e6e1f1776a4c = N'LongRunning'
SET
  @RequiredScope_e6e1f1776a4c = N'orders:subscriptions:write'
SET
  @RequiresSystemUser_e6e1f1776a4c = 0
SET
  @GenerationType_e6e1f1776a4c = N'Manual'
SET
  @CodeApprovalStatus_e6e1f1776a4c = N'Approved'
SET
  @Status_e6e1f1776a4c = N'Active'
SET
  @CodeLocked_e6e1f1776a4c = 0
SET
  @ID_e6e1f1776a4c = '3F4B9D9E-1084-4C7C-A883-21D3DC014D68'
SELECT TOP 1 @ID_e6e1f1776a4c = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = N'Orders.DetectOverlappingSubscriptions' ORDER BY CASE WHEN [ID] = @ID_e6e1f1776a4c THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_e6e1f1776a4c,
  @OperationKey = @OperationKey_e6e1f1776a4c,
  @CategoryID = @CategoryID_e6e1f1776a4c,
  @Description = @Description_e6e1f1776a4c,
  @InputTypeName = @InputTypeName_e6e1f1776a4c,
  @InputTypeDefinition = @InputTypeDefinition_e6e1f1776a4c,
  @InputTypeIsArray = @InputTypeIsArray_e6e1f1776a4c,
  @OutputTypeName = @OutputTypeName_e6e1f1776a4c,
  @OutputTypeDefinition = @OutputTypeDefinition_e6e1f1776a4c,
  @OutputTypeIsArray = @OutputTypeIsArray_e6e1f1776a4c,
  @ExecutionMode = @ExecutionMode_e6e1f1776a4c,
  @RequiredScope = @RequiredScope_e6e1f1776a4c,
  @RequiresSystemUser = @RequiresSystemUser_e6e1f1776a4c,
  @GenerationType = @GenerationType_e6e1f1776a4c,
  @Code = @Code_e6e1f1776a4c,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_e6e1f1776a4c,
  @CodeApprovedByUserID = @CodeApprovedByUserID_e6e1f1776a4c,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_e6e1f1776a4c,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_e6e1f1776a4c,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_e6e1f1776a4c,
  @CacheTTLSeconds = @CacheTTLSeconds_e6e1f1776a4c,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_e6e1f1776a4c,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_e6e1f1776a4c,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_e6e1f1776a4c,
  @CodeComments = @CodeComments_e6e1f1776a4c,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_e6e1f1776a4c,
  @Libraries_Clear = 1,
  @ID = @ID_e6e1f1776a4c;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_f0f51aae6a78 NVARCHAR(255),
@OperationKey_f0f51aae6a78 NVARCHAR(255),
@CategoryID_f0f51aae6a78 UNIQUEIDENTIFIER,
@Description_f0f51aae6a78 NVARCHAR(MAX),
@InputTypeName_f0f51aae6a78 NVARCHAR(255),
@InputTypeDefinition_f0f51aae6a78 NVARCHAR(MAX),
@InputTypeIsArray_f0f51aae6a78 BIT,
@OutputTypeName_f0f51aae6a78 NVARCHAR(255),
@OutputTypeDefinition_f0f51aae6a78 NVARCHAR(MAX),
@OutputTypeIsArray_f0f51aae6a78 BIT,
@ExecutionMode_f0f51aae6a78 NVARCHAR(20),
@RequiredScope_f0f51aae6a78 NVARCHAR(255),
@RequiresSystemUser_f0f51aae6a78 BIT,
@GenerationType_f0f51aae6a78 NVARCHAR(20),
@Code_f0f51aae6a78 NVARCHAR(MAX),
@CodeApprovalStatus_f0f51aae6a78 NVARCHAR(20),
@CodeApprovedByUserID_f0f51aae6a78 UNIQUEIDENTIFIER,
@CodeApprovedAt_f0f51aae6a78 DATETIMEOFFSET,
@ContractFingerprint_f0f51aae6a78 NVARCHAR(100),
@Status_f0f51aae6a78 NVARCHAR(20),
@CacheTTLSeconds_f0f51aae6a78 INT,
@TimeoutMS_f0f51aae6a78 INT,
@MaxConcurrency_f0f51aae6a78 INT,
@CodeLocked_f0f51aae6a78 BIT,
@CodeComments_f0f51aae6a78 NVARCHAR(MAX),
@Libraries_f0f51aae6a78 NVARCHAR(MAX),
@ID_f0f51aae6a78 UNIQUEIDENTIFIER
SET
  @Name_f0f51aae6a78 = N'Refund Payment'
SET
  @OperationKey_f0f51aae6a78 = N'Orders.RefundPayment'
SET
  @CategoryID_f0f51aae6a78 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B303'
SET
  @Description_f0f51aae6a78 = N'Issue a refund against a captured payment. A refund is a NEW payment, never an edit: the reversal carries its own instrument snapshot and negative allocation lines that un-apply proportionally to how the original was applied. The processing fee is not reversed — the processor kept it. Guards: must be captured, never more than remains, never twice.'
SET
  @InputTypeName_f0f51aae6a78 = N'RefundPaymentInput'
SET
  @InputTypeDefinition_f0f51aae6a78 = N'/**
 * Input for `Orders.RefundPayment`.
 *
 * A refund is a NEW payment, never an edit of the capture — the capture happened,
 * it has an entry, and rewriting it would destroy the trail of money that moved.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface RefundPaymentInput {
    PaymentHeaderID: string;
    /** Omit for a full refund of whatever remains refundable. */
    Amount?: number;
    Reason?: string;
    /** Provider''s refund id, when the money moved through one. */
    ProviderRefundID?: string;
    /** Compute and validate without writing — for a confirmation screen. */
    Preview?: boolean;
}
'
SET
  @InputTypeIsArray_f0f51aae6a78 = 0
SET
  @OutputTypeName_f0f51aae6a78 = N'RefundPaymentOutput'
SET
  @OutputTypeDefinition_f0f51aae6a78 = N'/**
 * Output for `Orders.RefundPayment`.
 *
 * The processing fee is deliberately NOT reversed — the processor kept its cut.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface RefundPaymentOutput {
    Success: boolean;
    Message?: string;
    /** What was (or would be) refunded. */
    RefundAmount?: number;
    /** Still refundable AFTER this refund. */
    RemainingRefundable?: number;
    RefundPaymentHeaderID?: string;
    RefundPaymentNumber?: string;
    /** The reversing journal entry, when one was booked. */
    JournalEntryID?: string;
    /**
     * How the refund un-applied across the orders the original settled — proportional
     * to how it was applied, because that decision was already made once.
     */
    Unapplications?: Array<{
        OrderHeaderID: string;
        OrderNumber: string;
        OriginalAmount: number;
        UnappliedAmount: number;
        BalanceAfter: number;
    }>;
}
'
SET
  @OutputTypeIsArray_f0f51aae6a78 = 0
SET
  @ExecutionMode_f0f51aae6a78 = N'Sync'
SET
  @RequiredScope_f0f51aae6a78 = N'orders:payments:refund'
SET
  @RequiresSystemUser_f0f51aae6a78 = 0
SET
  @GenerationType_f0f51aae6a78 = N'Manual'
SET
  @CodeApprovalStatus_f0f51aae6a78 = N'Approved'
SET
  @Status_f0f51aae6a78 = N'Active'
SET
  @CodeLocked_f0f51aae6a78 = 0
SET
  @ID_f0f51aae6a78 = 'C2D5F3B1-7E4A-4B29-8F63-1D2E6B92C406'
SELECT TOP 1 @ID_f0f51aae6a78 = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = N'Orders.RefundPayment' ORDER BY CASE WHEN [ID] = @ID_f0f51aae6a78 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_f0f51aae6a78,
  @OperationKey = @OperationKey_f0f51aae6a78,
  @CategoryID = @CategoryID_f0f51aae6a78,
  @Description = @Description_f0f51aae6a78,
  @InputTypeName = @InputTypeName_f0f51aae6a78,
  @InputTypeDefinition = @InputTypeDefinition_f0f51aae6a78,
  @InputTypeIsArray = @InputTypeIsArray_f0f51aae6a78,
  @OutputTypeName = @OutputTypeName_f0f51aae6a78,
  @OutputTypeDefinition = @OutputTypeDefinition_f0f51aae6a78,
  @OutputTypeIsArray = @OutputTypeIsArray_f0f51aae6a78,
  @ExecutionMode = @ExecutionMode_f0f51aae6a78,
  @RequiredScope = @RequiredScope_f0f51aae6a78,
  @RequiresSystemUser = @RequiresSystemUser_f0f51aae6a78,
  @GenerationType = @GenerationType_f0f51aae6a78,
  @Code = @Code_f0f51aae6a78,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_f0f51aae6a78,
  @CodeApprovedByUserID = @CodeApprovedByUserID_f0f51aae6a78,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_f0f51aae6a78,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_f0f51aae6a78,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_f0f51aae6a78,
  @CacheTTLSeconds = @CacheTTLSeconds_f0f51aae6a78,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_f0f51aae6a78,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_f0f51aae6a78,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_f0f51aae6a78,
  @CodeComments = @CodeComments_f0f51aae6a78,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_f0f51aae6a78,
  @Libraries_Clear = 1,
  @ID = @ID_f0f51aae6a78;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_76d660d76055 NVARCHAR(255),
@OperationKey_76d660d76055 NVARCHAR(255),
@CategoryID_76d660d76055 UNIQUEIDENTIFIER,
@Description_76d660d76055 NVARCHAR(MAX),
@InputTypeName_76d660d76055 NVARCHAR(255),
@InputTypeDefinition_76d660d76055 NVARCHAR(MAX),
@InputTypeIsArray_76d660d76055 BIT,
@OutputTypeName_76d660d76055 NVARCHAR(255),
@OutputTypeDefinition_76d660d76055 NVARCHAR(MAX),
@OutputTypeIsArray_76d660d76055 BIT,
@ExecutionMode_76d660d76055 NVARCHAR(20),
@RequiredScope_76d660d76055 NVARCHAR(255),
@RequiresSystemUser_76d660d76055 BIT,
@GenerationType_76d660d76055 NVARCHAR(20),
@Code_76d660d76055 NVARCHAR(MAX),
@CodeApprovalStatus_76d660d76055 NVARCHAR(20),
@CodeApprovedByUserID_76d660d76055 UNIQUEIDENTIFIER,
@CodeApprovedAt_76d660d76055 DATETIMEOFFSET,
@ContractFingerprint_76d660d76055 NVARCHAR(100),
@Status_76d660d76055 NVARCHAR(20),
@CacheTTLSeconds_76d660d76055 INT,
@TimeoutMS_76d660d76055 INT,
@MaxConcurrency_76d660d76055 INT,
@CodeLocked_76d660d76055 BIT,
@CodeComments_76d660d76055 NVARCHAR(MAX),
@Libraries_76d660d76055 NVARCHAR(MAX),
@ID_76d660d76055 UNIQUEIDENTIFIER
SET
  @Name_76d660d76055 = N'Apply Account Credit'
SET
  @OperationKey_76d660d76055 = N'Orders.ApplyAccountCredit'
SET
  @CategoryID_76d660d76055 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B303'
SET
  @Description_76d660d76055 = N'Spend a customer''s credit on another order. Writes a zero-amount payment with two offsetting lines — no new cash entered the business, so this only re-attributes money already received. A credit IS a negative order balance; there is no separate instrument to fall out of sync with it. Cross-company applications raise the intercompany legs through the ordinary allocation path, which is required rather than convenient.'
SET
  @InputTypeName_76d660d76055 = N'ApplyAccountCreditInput'
SET
  @InputTypeDefinition_76d660d76055 = N'/**
 * Input for `Orders.ApplyAccountCredit`.
 *
 * Spending a credit writes a ZERO-amount payment with two offsetting lines: no new
 * cash entered the business, so this only re-attributes money already received.
 * The credit itself is a negative order balance — there is no separate instrument,
 * because a second record holding the same number is a second thing that can
 * disagree with it.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface ApplyAccountCreditInput {
    /** The order carrying the credit (its Balance is negative). */
    SourceOrderHeaderID: string;
    /** The order to spend it on. */
    TargetOrderHeaderID: string;
    /** Omit to apply as much as both sides allow. */
    Amount?: number;
    Reason?: string;
    /** Compute and validate without writing — for a confirmation screen. */
    Preview?: boolean;
}
'
SET
  @InputTypeIsArray_76d660d76055 = 0
SET
  @OutputTypeName_76d660d76055 = N'ApplyAccountCreditOutput'
SET
  @OutputTypeDefinition_76d660d76055 = N'/**
 * Output for `Orders.ApplyAccountCredit`.
 *
 * When source and target belong to different companies the intercompany legs are
 * REQUIRED rather than convenient: a single Dr A/R / Cr A/R spanning two legal
 * entities could not be booked at all, since a resolved account must belong to its
 * own company.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface ApplyAccountCreditOutput {
    Success: boolean;
    Message?: string;
    /** What was (or would be) applied. */
    AppliedAmount?: number;
    /** The source order''s credit still available AFTER this application. */
    RemainingCredit?: number;
    /** The target order''s balance AFTER this application. */
    TargetBalanceAfter?: number;
    PaymentHeaderID?: string;
    PaymentNumber?: string;
    /** True when the two orders belong to different companies, so intercompany legs were raised. */
    CrossCompany?: boolean;
}
'
SET
  @OutputTypeIsArray_76d660d76055 = 0
SET
  @ExecutionMode_76d660d76055 = N'Sync'
SET
  @RequiredScope_76d660d76055 = N'orders:payments:write'
SET
  @RequiresSystemUser_76d660d76055 = 0
SET
  @GenerationType_76d660d76055 = N'Manual'
SET
  @CodeApprovalStatus_76d660d76055 = N'Approved'
SET
  @Status_76d660d76055 = N'Active'
SET
  @CodeLocked_76d660d76055 = 0
SET
  @ID_76d660d76055 = 'C2D5F3B1-7E4A-4B29-8F63-1D2E6B92C407'
SELECT TOP 1 @ID_76d660d76055 = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = N'Orders.ApplyAccountCredit' ORDER BY CASE WHEN [ID] = @ID_76d660d76055 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_76d660d76055,
  @OperationKey = @OperationKey_76d660d76055,
  @CategoryID = @CategoryID_76d660d76055,
  @Description = @Description_76d660d76055,
  @InputTypeName = @InputTypeName_76d660d76055,
  @InputTypeDefinition = @InputTypeDefinition_76d660d76055,
  @InputTypeIsArray = @InputTypeIsArray_76d660d76055,
  @OutputTypeName = @OutputTypeName_76d660d76055,
  @OutputTypeDefinition = @OutputTypeDefinition_76d660d76055,
  @OutputTypeIsArray = @OutputTypeIsArray_76d660d76055,
  @ExecutionMode = @ExecutionMode_76d660d76055,
  @RequiredScope = @RequiredScope_76d660d76055,
  @RequiresSystemUser = @RequiresSystemUser_76d660d76055,
  @GenerationType = @GenerationType_76d660d76055,
  @Code = @Code_76d660d76055,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_76d660d76055,
  @CodeApprovedByUserID = @CodeApprovedByUserID_76d660d76055,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_76d660d76055,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_76d660d76055,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_76d660d76055,
  @CacheTTLSeconds = @CacheTTLSeconds_76d660d76055,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_76d660d76055,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_76d660d76055,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_76d660d76055,
  @CodeComments = @CodeComments_76d660d76055,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_76d660d76055,
  @Libraries_Clear = 1,
  @ID = @ID_76d660d76055;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_4bc6c477fd41 NVARCHAR(255),
@OperationKey_4bc6c477fd41 NVARCHAR(255),
@CategoryID_4bc6c477fd41 UNIQUEIDENTIFIER,
@Description_4bc6c477fd41 NVARCHAR(MAX),
@InputTypeName_4bc6c477fd41 NVARCHAR(255),
@InputTypeDefinition_4bc6c477fd41 NVARCHAR(MAX),
@InputTypeIsArray_4bc6c477fd41 BIT,
@OutputTypeName_4bc6c477fd41 NVARCHAR(255),
@OutputTypeDefinition_4bc6c477fd41 NVARCHAR(MAX),
@OutputTypeIsArray_4bc6c477fd41 BIT,
@ExecutionMode_4bc6c477fd41 NVARCHAR(20),
@RequiredScope_4bc6c477fd41 NVARCHAR(255),
@RequiresSystemUser_4bc6c477fd41 BIT,
@GenerationType_4bc6c477fd41 NVARCHAR(20),
@Code_4bc6c477fd41 NVARCHAR(MAX),
@CodeApprovalStatus_4bc6c477fd41 NVARCHAR(20),
@CodeApprovedByUserID_4bc6c477fd41 UNIQUEIDENTIFIER,
@CodeApprovedAt_4bc6c477fd41 DATETIMEOFFSET,
@ContractFingerprint_4bc6c477fd41 NVARCHAR(100),
@Status_4bc6c477fd41 NVARCHAR(20),
@CacheTTLSeconds_4bc6c477fd41 INT,
@TimeoutMS_4bc6c477fd41 INT,
@MaxConcurrency_4bc6c477fd41 INT,
@CodeLocked_4bc6c477fd41 BIT,
@CodeComments_4bc6c477fd41 NVARCHAR(MAX),
@Libraries_4bc6c477fd41 NVARCHAR(MAX),
@ID_4bc6c477fd41 UNIQUEIDENTIFIER
SET
  @Name_4bc6c477fd41 = N'Cancel Subscription'
SET
  @OperationKey_4bc6c477fd41 = N'Orders.CancelSubscription'
SET
  @CategoryID_4bc6c477fd41 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B304'
SET
  @Description_4bc6c477fd41 = N'Cancel a subscription: policy in, reversal out. The subscription type''s cancellation mode, refund mode and grace period decide when coverage ends, when access ends and what is refunded; the operation emits the reversal order, stamps the term and logs the lifecycle event in one transaction. Grace extends ACCESS, never revenue — storing one in place of the other silently revokes access early.'
SET
  @InputTypeName_4bc6c477fd41 = N'CancelSubscriptionInput'
SET
  @InputTypeDefinition_4bc6c477fd41 = N'/**
 * Input for `Orders.CancelSubscription`.
 *
 * Policy in, reversal out. The caller supplies a subscription, a date and a reason;
 * the subscription type''s cancellation mode, refund mode and grace decide the rest.
 * The mechanic underneath is a negative-quantity order line — correct double-entry
 * and terrible data entry, which is exactly why it is computed from a date and a
 * policy rather than typed.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface CancelSubscriptionInput {
    SubscriptionID: string;
    /** When the customer asked. Defaults to today. The RULES decide when coverage actually ends. */
    RequestDate?: string;
    /** Free text, stored on the lifecycle event. */
    Reason?: string;
    /**
     * Return the decision WITHOUT writing anything — for a confirmation screen that shows
     * "you will be refunded $X, coverage ends Y" before the user commits.
     */
    Preview?: boolean;
}
'
SET
  @InputTypeIsArray_4bc6c477fd41 = 0
SET
  @OutputTypeName_4bc6c477fd41 = N'CancelSubscriptionOutput'
SET
  @OutputTypeDefinition_4bc6c477fd41 = N'/**
 * Output for `Orders.CancelSubscription`.
 *
 * `Decision` is the wire-safe projection of the engine''s decision: dates are ISO
 * strings rather than `Date`, because that is what crosses the transport anyway and
 * a contract that pretends otherwise lies to its client.
 *
 * NO import statements — definitions are emitted verbatim.
 */

/** What the subscription type''s rules decided. Present even on a preview. */
export interface CancellationDecisionResult {
    /** When coverage ends for revenue purposes. Never before the request, never after the term. */
    EffectiveDate: string;
    /** When ACCESS ends — effective date plus grace. Grace extends access, NOT revenue. */
    AccessThroughDate: string;
    /** What to give back. 0 under NoRefund, and never more than the term charged. */
    RefundAmount: number;
    /** Fraction of the term to reverse; the reversal line''s quantity is its negative. */
    ReversalFraction: number;
    /** `Canceled` when coverage is cut short, `Completed` when the term simply runs out. */
    TermStatus: ''Canceled'' | ''Completed'';
    /** Which rules produced this, in a sentence — surfaced to the user, so it names the policy. */
    Explanation: string;
}

export interface CancelSubscriptionOutput {
    Success: boolean;
    Message?: string;
    Decision?: CancellationDecisionResult;
    /** The term that was (or would be) cancelled. */
    SubscriptionTermID?: string;
    /**
     * Terms that start after coverage ends — a renewal already booked, say — and are (or would be)
     * cancelled and reversed with it. Empty when there are none. Present even on a preview.
     */
    LaterTerms?: CanceledLaterTermResult[];
    /** `Decision.RefundAmount` plus every later term''s refund — the whole refund the cancel gives. */
    TotalRefundAmount?: number;
    /** The reversal order, when one was needed. Absent when nothing was refunded. */
    ReversalOrderID?: string;
    ReversalOrderNumber?: string;
}

/** A later term cancelled alongside the affected one. */
export interface CanceledLaterTermResult {
    SubscriptionTermID: string;
    TermNumber: number;
    Decision: CancellationDecisionResult;
}
'
SET
  @OutputTypeIsArray_4bc6c477fd41 = 0
SET
  @ExecutionMode_4bc6c477fd41 = N'Sync'
SET
  @RequiredScope_4bc6c477fd41 = N'orders:subscriptions:write'
SET
  @RequiresSystemUser_4bc6c477fd41 = 0
SET
  @GenerationType_4bc6c477fd41 = N'Manual'
SET
  @CodeApprovalStatus_4bc6c477fd41 = N'Approved'
SET
  @Status_4bc6c477fd41 = N'Active'
SET
  @CodeLocked_4bc6c477fd41 = 0
SET
  @ID_4bc6c477fd41 = 'C2D5F3B1-7E4A-4B29-8F63-1D2E6B92C408'
SELECT TOP 1 @ID_4bc6c477fd41 = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = N'Orders.CancelSubscription' ORDER BY CASE WHEN [ID] = @ID_4bc6c477fd41 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_4bc6c477fd41,
  @OperationKey = @OperationKey_4bc6c477fd41,
  @CategoryID = @CategoryID_4bc6c477fd41,
  @Description = @Description_4bc6c477fd41,
  @InputTypeName = @InputTypeName_4bc6c477fd41,
  @InputTypeDefinition = @InputTypeDefinition_4bc6c477fd41,
  @InputTypeIsArray = @InputTypeIsArray_4bc6c477fd41,
  @OutputTypeName = @OutputTypeName_4bc6c477fd41,
  @OutputTypeDefinition = @OutputTypeDefinition_4bc6c477fd41,
  @OutputTypeIsArray = @OutputTypeIsArray_4bc6c477fd41,
  @ExecutionMode = @ExecutionMode_4bc6c477fd41,
  @RequiredScope = @RequiredScope_4bc6c477fd41,
  @RequiresSystemUser = @RequiresSystemUser_4bc6c477fd41,
  @GenerationType = @GenerationType_4bc6c477fd41,
  @Code = @Code_4bc6c477fd41,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_4bc6c477fd41,
  @CodeApprovedByUserID = @CodeApprovedByUserID_4bc6c477fd41,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_4bc6c477fd41,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_4bc6c477fd41,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_4bc6c477fd41,
  @CacheTTLSeconds = @CacheTTLSeconds_4bc6c477fd41,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_4bc6c477fd41,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_4bc6c477fd41,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_4bc6c477fd41,
  @CodeComments = @CodeComments_4bc6c477fd41,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_4bc6c477fd41,
  @Libraries_Clear = 1,
  @ID = @ID_4bc6c477fd41;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_ae7c80fb5431 NVARCHAR(255),
@OperationKey_ae7c80fb5431 NVARCHAR(255),
@CategoryID_ae7c80fb5431 UNIQUEIDENTIFIER,
@Description_ae7c80fb5431 NVARCHAR(MAX),
@InputTypeName_ae7c80fb5431 NVARCHAR(255),
@InputTypeDefinition_ae7c80fb5431 NVARCHAR(MAX),
@InputTypeIsArray_ae7c80fb5431 BIT,
@OutputTypeName_ae7c80fb5431 NVARCHAR(255),
@OutputTypeDefinition_ae7c80fb5431 NVARCHAR(MAX),
@OutputTypeIsArray_ae7c80fb5431 BIT,
@ExecutionMode_ae7c80fb5431 NVARCHAR(20),
@RequiredScope_ae7c80fb5431 NVARCHAR(255),
@RequiresSystemUser_ae7c80fb5431 BIT,
@GenerationType_ae7c80fb5431 NVARCHAR(20),
@Code_ae7c80fb5431 NVARCHAR(MAX),
@CodeApprovalStatus_ae7c80fb5431 NVARCHAR(20),
@CodeApprovedByUserID_ae7c80fb5431 UNIQUEIDENTIFIER,
@CodeApprovedAt_ae7c80fb5431 DATETIMEOFFSET,
@ContractFingerprint_ae7c80fb5431 NVARCHAR(100),
@Status_ae7c80fb5431 NVARCHAR(20),
@CacheTTLSeconds_ae7c80fb5431 INT,
@TimeoutMS_ae7c80fb5431 INT,
@MaxConcurrency_ae7c80fb5431 INT,
@CodeLocked_ae7c80fb5431 BIT,
@CodeComments_ae7c80fb5431 NVARCHAR(MAX),
@Libraries_ae7c80fb5431 NVARCHAR(MAX),
@ID_ae7c80fb5431 UNIQUEIDENTIFIER
SET
  @Name_ae7c80fb5431 = N'Spawn Renewals'
SET
  @OperationKey_ae7c80fb5431 = N'Orders.SpawnRenewals'
SET
  @CategoryID_ae7c80fb5431 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B304'
SET
  @Description_ae7c80fb5431 = N'Place renewal orders for subscriptions whose latest term expires inside their own lead window and whose holder consented via auto-renew. Two independent idempotency guards, because an unattended job that double-spawns double-bills: the selection only finds subscriptions whose LATEST term is expiring, plus an explicit check for an order already renewing that subscription. Renewals bypass the concurrency rule — a renewal is not a second subscription.'
SET
  @InputTypeName_ae7c80fb5431 = N'SpawnRenewalsInput'
SET
  @InputTypeDefinition_ae7c80fb5431 = N'/**
 * Input for `Orders.SpawnRenewals`.
 *
 * A renewal is a SCHEDULED CONTINUATION and auto-renew is the consent switch. This
 * finds subscriptions whose LATEST term expires inside their own lead window and
 * places a confirmed renewal order for each that consented.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface SpawnRenewalsInput {
    /** Treat this as "today". Defaults to now. */
    AsOfDate?: string;
    /** Restrict to one subscription — for a targeted retry, or for a test. */
    SubscriptionID?: string;
    /** Report what WOULD be placed, without placing anything. */
    Preview?: boolean;
    /**
     * Cap on orders placed in one pass. A safety valve for the first production run, where a
     * mis-set lead time could otherwise invoice an entire book of business at once.
     */
    MaxCount?: number;
}
'
SET
  @InputTypeIsArray_ae7c80fb5431 = 0
SET
  @OutputTypeName_ae7c80fb5431 = N'SpawnRenewalsOutput'
SET
  @OutputTypeDefinition_ae7c80fb5431 = N'/**
 * Output for `Orders.SpawnRenewals`.
 *
 * Every candidate comes back whether or not an order was placed, with the reason it
 * was skipped — an unattended job that silently does nothing is indistinguishable
 * from one that is broken.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface RenewalCandidate {
    SubscriptionID: string;
    SubscriptionNumber: string;
    ProductID: string;
    /** End of the term that is expiring. */
    CurrentTermEnd: string;
    /** Lead days actually applied, after the subscription''s override of the type''s default. */
    LeadDays: number;
    /** Set when the renewal was placed (absent on a preview, or when placing failed). */
    OrderID?: string;
    OrderNumber?: string;
    /** Set when this candidate was skipped, with the reason. */
    SkippedReason?: string;
    /** The product the renewal is placed on: the subscription''s own, or its successor. */
    RenewalProductID?: string;
    /** The renewal''s unit price before the increase. */
    BasePrice?: number;
    /** Where the base price came from: the prior term''s price, its list price, or the successor''s list. */
    BasePriceSource?: ''PriorPrice'' | ''PriorList'' | ''SuccessorList'';
    /** The increase applied, in percent: 0 when none is set or the new term crosses no anniversary. */
    IncreasePercent?: number;
    /** The level the increase was set at. */
    IncreaseSource?: ''Subscription'' | ''Product'' | ''Category'' | ''Company'' | ''None'';
    /** The renewal line''s unit price: the base plus the increase. */
    UnitPrice?: number;
    /** The renewal line''s discount, as a fraction: 0 unless the subscription carries its discount into renewals. */
    DiscountPct?: number;
}

export interface SpawnRenewalsOutput {
    Success: boolean;
    Message?: string;
    /** Every subscription considered due, whether or not an order was placed. */
    Candidates: RenewalCandidate[];
    Placed: number;
    Skipped: number;
}
'
SET
  @OutputTypeIsArray_ae7c80fb5431 = 0
SET
  @ExecutionMode_ae7c80fb5431 = N'LongRunning'
SET
  @RequiredScope_ae7c80fb5431 = N'orders:subscriptions:write'
SET
  @RequiresSystemUser_ae7c80fb5431 = 0
SET
  @GenerationType_ae7c80fb5431 = N'Manual'
SET
  @CodeApprovalStatus_ae7c80fb5431 = N'Approved'
SET
  @Status_ae7c80fb5431 = N'Active'
SET
  @CodeLocked_ae7c80fb5431 = 0
SET
  @ID_ae7c80fb5431 = 'C2D5F3B1-7E4A-4B29-8F63-1D2E6B92C409'
SELECT TOP 1 @ID_ae7c80fb5431 = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = N'Orders.SpawnRenewals' ORDER BY CASE WHEN [ID] = @ID_ae7c80fb5431 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_ae7c80fb5431,
  @OperationKey = @OperationKey_ae7c80fb5431,
  @CategoryID = @CategoryID_ae7c80fb5431,
  @Description = @Description_ae7c80fb5431,
  @InputTypeName = @InputTypeName_ae7c80fb5431,
  @InputTypeDefinition = @InputTypeDefinition_ae7c80fb5431,
  @InputTypeIsArray = @InputTypeIsArray_ae7c80fb5431,
  @OutputTypeName = @OutputTypeName_ae7c80fb5431,
  @OutputTypeDefinition = @OutputTypeDefinition_ae7c80fb5431,
  @OutputTypeIsArray = @OutputTypeIsArray_ae7c80fb5431,
  @ExecutionMode = @ExecutionMode_ae7c80fb5431,
  @RequiredScope = @RequiredScope_ae7c80fb5431,
  @RequiresSystemUser = @RequiresSystemUser_ae7c80fb5431,
  @GenerationType = @GenerationType_ae7c80fb5431,
  @Code = @Code_ae7c80fb5431,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_ae7c80fb5431,
  @CodeApprovedByUserID = @CodeApprovedByUserID_ae7c80fb5431,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_ae7c80fb5431,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_ae7c80fb5431,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_ae7c80fb5431,
  @CacheTTLSeconds = @CacheTTLSeconds_ae7c80fb5431,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_ae7c80fb5431,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_ae7c80fb5431,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_ae7c80fb5431,
  @CodeComments = @CodeComments_ae7c80fb5431,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_ae7c80fb5431,
  @Libraries_Clear = 1,
  @ID = @ID_ae7c80fb5431;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_98b03edd0f04 NVARCHAR(255),
@OperationKey_98b03edd0f04 NVARCHAR(255),
@CategoryID_98b03edd0f04 UNIQUEIDENTIFIER,
@Description_98b03edd0f04 NVARCHAR(MAX),
@InputTypeName_98b03edd0f04 NVARCHAR(255),
@InputTypeDefinition_98b03edd0f04 NVARCHAR(MAX),
@InputTypeIsArray_98b03edd0f04 BIT,
@OutputTypeName_98b03edd0f04 NVARCHAR(255),
@OutputTypeDefinition_98b03edd0f04 NVARCHAR(MAX),
@OutputTypeIsArray_98b03edd0f04 BIT,
@ExecutionMode_98b03edd0f04 NVARCHAR(20),
@RequiredScope_98b03edd0f04 NVARCHAR(255),
@RequiresSystemUser_98b03edd0f04 BIT,
@GenerationType_98b03edd0f04 NVARCHAR(20),
@Code_98b03edd0f04 NVARCHAR(MAX),
@CodeApprovalStatus_98b03edd0f04 NVARCHAR(20),
@CodeApprovedByUserID_98b03edd0f04 UNIQUEIDENTIFIER,
@CodeApprovedAt_98b03edd0f04 DATETIMEOFFSET,
@ContractFingerprint_98b03edd0f04 NVARCHAR(100),
@Status_98b03edd0f04 NVARCHAR(20),
@CacheTTLSeconds_98b03edd0f04 INT,
@TimeoutMS_98b03edd0f04 INT,
@MaxConcurrency_98b03edd0f04 INT,
@CodeLocked_98b03edd0f04 BIT,
@CodeComments_98b03edd0f04 NVARCHAR(MAX),
@Libraries_98b03edd0f04 NVARCHAR(MAX),
@ID_98b03edd0f04 UNIQUEIDENTIFIER
SET
  @Name_98b03edd0f04 = N'Amend Arrangement'
SET
  @OperationKey_98b03edd0f04 = N'Orders.AmendArrangement'
SET
  @CategoryID_98b03edd0f04 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B304'
SET
  @Description_98b03edd0f04 = N'Extend a booked subscription term at no charge. Preview returns the value given away, the staged recognition entries it offsets and the new schedule, and writes nothing. Otherwise it records a Duration concession, routed for approval like any other; the extension applies when the concession is approved: the term''s end, a prospective re-spread of recognition, access, and a task for accounting to confirm the re-cut. A change of amount is refused until its credit-memo path exists.'
SET
  @InputTypeName_98b03edd0f04 = N'AmendArrangementInput'
SET
  @InputTypeDefinition_98b03edd0f04 = N'/**
 * Input for `Orders.AmendArrangement`.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export type AmendmentReasonCategory = ''Retention'' | ''Referral'' | ''Other'';

export interface AmendArrangementInput {
    /** The booked term to amend. */
    SubscriptionTermID: string;
    /** The term''s new end date. Must be later than its current end. */
    NewEndDate: string;
    /** A change of amount. Not supported yet; refused. */
    NewAmount?: number;
    ReasonCategory: AmendmentReasonCategory;
    Reason: string;
    /** Return what the amendment would do without writing anything. */
    Preview?: boolean;
}

export interface AmendArrangementInput {
    /** The booked term to amend. */
    SubscriptionTermID: string;
    /** The term''s new end date. Must be later than its current end. */
    NewEndDate: string;
    /** A change of amount. Not supported yet; refused. */
    NewAmount?: number;
    ReasonCategory: AmendmentReasonCategory;
    Reason: string;
    /** Return what the amendment would do without writing anything. */
    Preview?: boolean;
}
'
SET
  @InputTypeIsArray_98b03edd0f04 = 0
SET
  @OutputTypeName_98b03edd0f04 = N'AmendArrangementOutput'
SET
  @OutputTypeDefinition_98b03edd0f04 = N'/**
 * Output of `Orders.AmendArrangement`.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface AmendArrangementEntry {
    EffectiveDate: string;
    Amount: number;
    /** For an offset, the staged entry it cancels. */
    Offsets?: string;
}

export interface AmendArrangementOutput {
    Success: boolean;
    Message?: string;
    CurrentEndDate?: string;
    NewEndDate?: string;
    /** The day the extension takes effect: staged entries from here on are replaced. */
    EffectiveDate?: string;
    /** What the added days are worth at the term''s own rate. */
    Value?: number;
    /** What the replaced entries were going to recognise, and the new schedule now does. */
    Respread?: number;
    Offsets?: AmendArrangementEntry[];
    NewSchedule?: AmendArrangementEntry[];
    /** Set when recorded: the concession, and whether it is Approved (applied) or Pending (awaiting approval). */
    OrderConcessionID?: string;
    Status?: string;
}
'
SET
  @OutputTypeIsArray_98b03edd0f04 = 0
SET
  @ExecutionMode_98b03edd0f04 = N'Sync'
SET
  @RequiredScope_98b03edd0f04 = N'orders:subscriptions:write'
SET
  @RequiresSystemUser_98b03edd0f04 = 0
SET
  @GenerationType_98b03edd0f04 = N'Manual'
SET
  @CodeApprovalStatus_98b03edd0f04 = N'Approved'
SET
  @Status_98b03edd0f04 = N'Active'
SET
  @CodeLocked_98b03edd0f04 = 0
SET
  @ID_98b03edd0f04 = '6B24D4FD-3DD2-4E28-841C-3B64535DADDC'
SELECT TOP 1 @ID_98b03edd0f04 = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = N'Orders.AmendArrangement' ORDER BY CASE WHEN [ID] = @ID_98b03edd0f04 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_98b03edd0f04,
  @OperationKey = @OperationKey_98b03edd0f04,
  @CategoryID = @CategoryID_98b03edd0f04,
  @Description = @Description_98b03edd0f04,
  @InputTypeName = @InputTypeName_98b03edd0f04,
  @InputTypeDefinition = @InputTypeDefinition_98b03edd0f04,
  @InputTypeIsArray = @InputTypeIsArray_98b03edd0f04,
  @OutputTypeName = @OutputTypeName_98b03edd0f04,
  @OutputTypeDefinition = @OutputTypeDefinition_98b03edd0f04,
  @OutputTypeIsArray = @OutputTypeIsArray_98b03edd0f04,
  @ExecutionMode = @ExecutionMode_98b03edd0f04,
  @RequiredScope = @RequiredScope_98b03edd0f04,
  @RequiresSystemUser = @RequiresSystemUser_98b03edd0f04,
  @GenerationType = @GenerationType_98b03edd0f04,
  @Code = @Code_98b03edd0f04,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_98b03edd0f04,
  @CodeApprovedByUserID = @CodeApprovedByUserID_98b03edd0f04,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_98b03edd0f04,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_98b03edd0f04,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_98b03edd0f04,
  @CacheTTLSeconds = @CacheTTLSeconds_98b03edd0f04,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_98b03edd0f04,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_98b03edd0f04,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_98b03edd0f04,
  @CodeComments = @CodeComments_98b03edd0f04,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_98b03edd0f04,
  @Libraries_Clear = 1,
  @ID = @ID_98b03edd0f04;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_8e3683363275 UNIQUEIDENTIFIER,
@Name_8e3683363275 NVARCHAR(100),
@Category_8e3683363275 NVARCHAR(100),
@Description_8e3683363275 NVARCHAR(500),
@ParentID_8e3683363275 UNIQUEIDENTIFIER,
@FullPath_8e3683363275 NVARCHAR(500),
@ResourceType_8e3683363275 NVARCHAR(50),
@IsActive_8e3683363275 BIT,
@UIConfig_8e3683363275 NVARCHAR(MAX)
SET
  @ID_8e3683363275 = '3599A29A-DB15-4AEE-89D3-2F19F5124BDC'
SET
  @Name_8e3683363275 = N'read'
SET
  @Category_8e3683363275 = N'Orders'
SET
  @Description_8e3683363275 = N'Read-only Orders operations: pricing, previews, worklists and queues'
SET
  @ParentID_8e3683363275 = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_8e3683363275 = N'orders:read'
SET
  @IsActive_8e3683363275 = 1

SELECT TOP 1 @ParentID_8e3683363275 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_8e3683363275 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_8e3683363275
                  OR ([FullPath] = @FullPath_8e3683363275)
                  OR (([ParentID] = @ParentID_8e3683363275 OR ([ParentID] IS NULL AND @ParentID_8e3683363275 IS NULL)) AND [Name] = @Name_8e3683363275))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_8e3683363275,
  @Name = @Name_8e3683363275,
  @Category = @Category_8e3683363275,
  @Description = @Description_8e3683363275,
  @ParentID = @ParentID_8e3683363275,
  @FullPath = @FullPath_8e3683363275,
  @ResourceType = @ResourceType_8e3683363275,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_8e3683363275,
  @UIConfig = @UIConfig_8e3683363275,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_c80604877afb UNIQUEIDENTIFIER,
@Name_c80604877afb NVARCHAR(100),
@Category_c80604877afb NVARCHAR(100),
@Description_c80604877afb NVARCHAR(500),
@ParentID_c80604877afb UNIQUEIDENTIFIER,
@FullPath_c80604877afb NVARCHAR(500),
@ResourceType_c80604877afb NVARCHAR(50),
@IsActive_c80604877afb BIT,
@UIConfig_c80604877afb NVARCHAR(MAX)
SET
  @ID_c80604877afb = 'D6071985-2297-4500-AC27-4F24210D0719'
SET
  @Name_c80604877afb = N'write'
SET
  @Category_c80604877afb = N'Orders'
SET
  @Description_c80604877afb = N'Orders operations that change orders: state, fulfilment, capture, invoicing and progress'
SET
  @ParentID_c80604877afb = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_c80604877afb = N'orders:write'
SET
  @IsActive_c80604877afb = 1

SELECT TOP 1 @ParentID_c80604877afb = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_c80604877afb THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_c80604877afb
                  OR ([FullPath] = @FullPath_c80604877afb)
                  OR (([ParentID] = @ParentID_c80604877afb OR ([ParentID] IS NULL AND @ParentID_c80604877afb IS NULL)) AND [Name] = @Name_c80604877afb))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_c80604877afb,
  @Name = @Name_c80604877afb,
  @Category = @Category_c80604877afb,
  @Description = @Description_c80604877afb,
  @ParentID = @ParentID_c80604877afb,
  @FullPath = @FullPath_c80604877afb,
  @ResourceType = @ResourceType_c80604877afb,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_c80604877afb,
  @UIConfig = @UIConfig_c80604877afb,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_3eaf344a6f2c UNIQUEIDENTIFIER,
@Name_3eaf344a6f2c NVARCHAR(100),
@Category_3eaf344a6f2c NVARCHAR(100),
@Description_3eaf344a6f2c NVARCHAR(500),
@ParentID_3eaf344a6f2c UNIQUEIDENTIFIER,
@FullPath_3eaf344a6f2c NVARCHAR(500),
@ResourceType_3eaf344a6f2c NVARCHAR(50),
@IsActive_3eaf344a6f2c BIT,
@UIConfig_3eaf344a6f2c NVARCHAR(MAX)
SET
  @ID_3eaf344a6f2c = '3F957084-0543-45E1-AD99-8BF56C1EC04E'
SET
  @Name_3eaf344a6f2c = N'payments:refund'
SET
  @Category_3eaf344a6f2c = N'Orders'
SET
  @Description_3eaf344a6f2c = N'Refund a payment (Orders.RefundPayment)'
SET
  @ParentID_3eaf344a6f2c = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_3eaf344a6f2c = N'orders:payments:refund'
SET
  @IsActive_3eaf344a6f2c = 1

SELECT TOP 1 @ParentID_3eaf344a6f2c = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_3eaf344a6f2c THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_3eaf344a6f2c
                  OR ([FullPath] = @FullPath_3eaf344a6f2c)
                  OR (([ParentID] = @ParentID_3eaf344a6f2c OR ([ParentID] IS NULL AND @ParentID_3eaf344a6f2c IS NULL)) AND [Name] = @Name_3eaf344a6f2c))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_3eaf344a6f2c,
  @Name = @Name_3eaf344a6f2c,
  @Category = @Category_3eaf344a6f2c,
  @Description = @Description_3eaf344a6f2c,
  @ParentID = @ParentID_3eaf344a6f2c,
  @FullPath = @FullPath_3eaf344a6f2c,
  @ResourceType = @ResourceType_3eaf344a6f2c,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_3eaf344a6f2c,
  @UIConfig = @UIConfig_3eaf344a6f2c,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_fd46b49875b9 UNIQUEIDENTIFIER,
@Name_fd46b49875b9 NVARCHAR(100),
@Category_fd46b49875b9 NVARCHAR(100),
@Description_fd46b49875b9 NVARCHAR(500),
@ParentID_fd46b49875b9 UNIQUEIDENTIFIER,
@FullPath_fd46b49875b9 NVARCHAR(500),
@ResourceType_fd46b49875b9 NVARCHAR(50),
@IsActive_fd46b49875b9 BIT,
@UIConfig_fd46b49875b9 NVARCHAR(MAX)
SET
  @ID_fd46b49875b9 = '05683886-9743-43D5-9E20-FB8DFBAF7818'
SET
  @Name_fd46b49875b9 = N'payments:write'
SET
  @Category_fd46b49875b9 = N'Orders'
SET
  @Description_fd46b49875b9 = N'Spend a customer''s account credit (Orders.ApplyAccountCredit)'
SET
  @ParentID_fd46b49875b9 = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_fd46b49875b9 = N'orders:payments:write'
SET
  @IsActive_fd46b49875b9 = 1

SELECT TOP 1 @ParentID_fd46b49875b9 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_fd46b49875b9 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_fd46b49875b9
                  OR ([FullPath] = @FullPath_fd46b49875b9)
                  OR (([ParentID] = @ParentID_fd46b49875b9 OR ([ParentID] IS NULL AND @ParentID_fd46b49875b9 IS NULL)) AND [Name] = @Name_fd46b49875b9))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_fd46b49875b9,
  @Name = @Name_fd46b49875b9,
  @Category = @Category_fd46b49875b9,
  @Description = @Description_fd46b49875b9,
  @ParentID = @ParentID_fd46b49875b9,
  @FullPath = @FullPath_fd46b49875b9,
  @ResourceType = @ResourceType_fd46b49875b9,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_fd46b49875b9,
  @UIConfig = @UIConfig_fd46b49875b9,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_663a16710195 UNIQUEIDENTIFIER,
@Name_663a16710195 NVARCHAR(100),
@Category_663a16710195 NVARCHAR(100),
@Description_663a16710195 NVARCHAR(500),
@ParentID_663a16710195 UNIQUEIDENTIFIER,
@FullPath_663a16710195 NVARCHAR(500),
@ResourceType_663a16710195 NVARCHAR(50),
@IsActive_663a16710195 BIT,
@UIConfig_663a16710195 NVARCHAR(MAX)
SET
  @ID_663a16710195 = 'D965B6FB-2B83-4F10-91BD-EFF8F82B2BC3'
SET
  @Name_663a16710195 = N'subscriptions:write'
SET
  @Category_663a16710195 = N'Orders'
SET
  @Description_663a16710195 = N'Change subscriptions: cancel, renew, amend and the overlap check'
SET
  @ParentID_663a16710195 = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_663a16710195 = N'orders:subscriptions:write'
SET
  @IsActive_663a16710195 = 1

SELECT TOP 1 @ParentID_663a16710195 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_663a16710195 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_663a16710195
                  OR ([FullPath] = @FullPath_663a16710195)
                  OR (([ParentID] = @ParentID_663a16710195 OR ([ParentID] IS NULL AND @ParentID_663a16710195 IS NULL)) AND [Name] = @Name_663a16710195))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_663a16710195,
  @Name = @Name_663a16710195,
  @Category = @Category_663a16710195,
  @Description = @Description_663a16710195,
  @ParentID = @ParentID_663a16710195,
  @FullPath = @FullPath_663a16710195,
  @ResourceType = @ResourceType_663a16710195,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_663a16710195,
  @UIConfig = @UIConfig_663a16710195,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_9d56db39746c UNIQUEIDENTIFIER,
@ApplicationID_9d56db39746c UNIQUEIDENTIFIER,
@ScopeID_9d56db39746c UNIQUEIDENTIFIER,
@ResourcePattern_9d56db39746c NVARCHAR(750),
@PatternType_9d56db39746c NVARCHAR(20),
@IsDeny_9d56db39746c BIT,
@Priority_9d56db39746c INT,
@RowFilterID_9d56db39746c UNIQUEIDENTIFIER
SET
  @ID_9d56db39746c = '7A0CD730-B96D-4F68-A6EE-DFB12D82E875'
SET
  @ApplicationID_9d56db39746c = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_9d56db39746c = '3599A29A-DB15-4AEE-89D3-2F19F5124BDC'
SET
  @ResourcePattern_9d56db39746c = N'*'
SET
  @PatternType_9d56db39746c = N'Include'
SET
  @IsDeny_9d56db39746c = 0
SET
  @Priority_9d56db39746c = 0

SELECT TOP 1 @ApplicationID_9d56db39746c = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_9d56db39746c THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_9d56db39746c = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:read' ORDER BY CASE WHEN [ID] = @ScopeID_9d56db39746c THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_9d56db39746c
                  OR ([ApplicationID] = @ApplicationID_9d56db39746c AND [ScopeID] = @ScopeID_9d56db39746c AND ([ResourcePattern] = @ResourcePattern_9d56db39746c OR ([ResourcePattern] IS NULL AND @ResourcePattern_9d56db39746c IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_9d56db39746c,
  @ApplicationID = @ApplicationID_9d56db39746c,
  @ScopeID = @ScopeID_9d56db39746c,
  @ResourcePattern = @ResourcePattern_9d56db39746c,
  @PatternType = @PatternType_9d56db39746c,
  @IsDeny = @IsDeny_9d56db39746c,
  @Priority = @Priority_9d56db39746c,
  @RowFilterID = @RowFilterID_9d56db39746c,
  @RowFilterID_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_835093f1f2cd UNIQUEIDENTIFIER,
@ApplicationID_835093f1f2cd UNIQUEIDENTIFIER,
@ScopeID_835093f1f2cd UNIQUEIDENTIFIER,
@ResourcePattern_835093f1f2cd NVARCHAR(750),
@PatternType_835093f1f2cd NVARCHAR(20),
@IsDeny_835093f1f2cd BIT,
@Priority_835093f1f2cd INT,
@RowFilterID_835093f1f2cd UNIQUEIDENTIFIER
SET
  @ID_835093f1f2cd = '17E22326-C53E-4F08-B779-E2B915AE4911'
SET
  @ApplicationID_835093f1f2cd = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_835093f1f2cd = 'D6071985-2297-4500-AC27-4F24210D0719'
SET
  @ResourcePattern_835093f1f2cd = N'*'
SET
  @PatternType_835093f1f2cd = N'Include'
SET
  @IsDeny_835093f1f2cd = 0
SET
  @Priority_835093f1f2cd = 0

SELECT TOP 1 @ApplicationID_835093f1f2cd = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_835093f1f2cd THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_835093f1f2cd = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:write' ORDER BY CASE WHEN [ID] = @ScopeID_835093f1f2cd THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_835093f1f2cd
                  OR ([ApplicationID] = @ApplicationID_835093f1f2cd AND [ScopeID] = @ScopeID_835093f1f2cd AND ([ResourcePattern] = @ResourcePattern_835093f1f2cd OR ([ResourcePattern] IS NULL AND @ResourcePattern_835093f1f2cd IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_835093f1f2cd,
  @ApplicationID = @ApplicationID_835093f1f2cd,
  @ScopeID = @ScopeID_835093f1f2cd,
  @ResourcePattern = @ResourcePattern_835093f1f2cd,
  @PatternType = @PatternType_835093f1f2cd,
  @IsDeny = @IsDeny_835093f1f2cd,
  @Priority = @Priority_835093f1f2cd,
  @RowFilterID = @RowFilterID_835093f1f2cd,
  @RowFilterID_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_79fcfa419830 UNIQUEIDENTIFIER,
@ApplicationID_79fcfa419830 UNIQUEIDENTIFIER,
@ScopeID_79fcfa419830 UNIQUEIDENTIFIER,
@ResourcePattern_79fcfa419830 NVARCHAR(750),
@PatternType_79fcfa419830 NVARCHAR(20),
@IsDeny_79fcfa419830 BIT,
@Priority_79fcfa419830 INT,
@RowFilterID_79fcfa419830 UNIQUEIDENTIFIER
SET
  @ID_79fcfa419830 = 'A8A3D77C-06AC-4C9D-9029-EBC0C924764C'
SET
  @ApplicationID_79fcfa419830 = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_79fcfa419830 = '3F957084-0543-45E1-AD99-8BF56C1EC04E'
SET
  @ResourcePattern_79fcfa419830 = N'*'
SET
  @PatternType_79fcfa419830 = N'Include'
SET
  @IsDeny_79fcfa419830 = 0
SET
  @Priority_79fcfa419830 = 0

SELECT TOP 1 @ApplicationID_79fcfa419830 = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_79fcfa419830 THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_79fcfa419830 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:payments:refund' ORDER BY CASE WHEN [ID] = @ScopeID_79fcfa419830 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_79fcfa419830
                  OR ([ApplicationID] = @ApplicationID_79fcfa419830 AND [ScopeID] = @ScopeID_79fcfa419830 AND ([ResourcePattern] = @ResourcePattern_79fcfa419830 OR ([ResourcePattern] IS NULL AND @ResourcePattern_79fcfa419830 IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_79fcfa419830,
  @ApplicationID = @ApplicationID_79fcfa419830,
  @ScopeID = @ScopeID_79fcfa419830,
  @ResourcePattern = @ResourcePattern_79fcfa419830,
  @PatternType = @PatternType_79fcfa419830,
  @IsDeny = @IsDeny_79fcfa419830,
  @Priority = @Priority_79fcfa419830,
  @RowFilterID = @RowFilterID_79fcfa419830,
  @RowFilterID_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_9946714dc467 UNIQUEIDENTIFIER,
@ApplicationID_9946714dc467 UNIQUEIDENTIFIER,
@ScopeID_9946714dc467 UNIQUEIDENTIFIER,
@ResourcePattern_9946714dc467 NVARCHAR(750),
@PatternType_9946714dc467 NVARCHAR(20),
@IsDeny_9946714dc467 BIT,
@Priority_9946714dc467 INT,
@RowFilterID_9946714dc467 UNIQUEIDENTIFIER
SET
  @ID_9946714dc467 = 'DC7BCA69-0E6C-47DB-BA8A-24CF5D275314'
SET
  @ApplicationID_9946714dc467 = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_9946714dc467 = '05683886-9743-43D5-9E20-FB8DFBAF7818'
SET
  @ResourcePattern_9946714dc467 = N'*'
SET
  @PatternType_9946714dc467 = N'Include'
SET
  @IsDeny_9946714dc467 = 0
SET
  @Priority_9946714dc467 = 0

SELECT TOP 1 @ApplicationID_9946714dc467 = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_9946714dc467 THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_9946714dc467 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:payments:write' ORDER BY CASE WHEN [ID] = @ScopeID_9946714dc467 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_9946714dc467
                  OR ([ApplicationID] = @ApplicationID_9946714dc467 AND [ScopeID] = @ScopeID_9946714dc467 AND ([ResourcePattern] = @ResourcePattern_9946714dc467 OR ([ResourcePattern] IS NULL AND @ResourcePattern_9946714dc467 IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_9946714dc467,
  @ApplicationID = @ApplicationID_9946714dc467,
  @ScopeID = @ScopeID_9946714dc467,
  @ResourcePattern = @ResourcePattern_9946714dc467,
  @PatternType = @PatternType_9946714dc467,
  @IsDeny = @IsDeny_9946714dc467,
  @Priority = @Priority_9946714dc467,
  @RowFilterID = @RowFilterID_9946714dc467,
  @RowFilterID_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_a1ecf94ca9e6 UNIQUEIDENTIFIER,
@ApplicationID_a1ecf94ca9e6 UNIQUEIDENTIFIER,
@ScopeID_a1ecf94ca9e6 UNIQUEIDENTIFIER,
@ResourcePattern_a1ecf94ca9e6 NVARCHAR(750),
@PatternType_a1ecf94ca9e6 NVARCHAR(20),
@IsDeny_a1ecf94ca9e6 BIT,
@Priority_a1ecf94ca9e6 INT,
@RowFilterID_a1ecf94ca9e6 UNIQUEIDENTIFIER
SET
  @ID_a1ecf94ca9e6 = '3391FEC3-6781-4FED-99B5-022C4F1958FF'
SET
  @ApplicationID_a1ecf94ca9e6 = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_a1ecf94ca9e6 = 'D965B6FB-2B83-4F10-91BD-EFF8F82B2BC3'
SET
  @ResourcePattern_a1ecf94ca9e6 = N'*'
SET
  @PatternType_a1ecf94ca9e6 = N'Include'
SET
  @IsDeny_a1ecf94ca9e6 = 0
SET
  @Priority_a1ecf94ca9e6 = 0

SELECT TOP 1 @ApplicationID_a1ecf94ca9e6 = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_a1ecf94ca9e6 THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_a1ecf94ca9e6 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:subscriptions:write' ORDER BY CASE WHEN [ID] = @ScopeID_a1ecf94ca9e6 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_a1ecf94ca9e6
                  OR ([ApplicationID] = @ApplicationID_a1ecf94ca9e6 AND [ScopeID] = @ScopeID_a1ecf94ca9e6 AND ([ResourcePattern] = @ResourcePattern_a1ecf94ca9e6 OR ([ResourcePattern] IS NULL AND @ResourcePattern_a1ecf94ca9e6 IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_a1ecf94ca9e6,
  @ApplicationID = @ApplicationID_a1ecf94ca9e6,
  @ScopeID = @ScopeID_a1ecf94ca9e6,
  @ResourcePattern = @ResourcePattern_a1ecf94ca9e6,
  @PatternType = @PatternType_a1ecf94ca9e6,
  @IsDeny = @IsDeny_a1ecf94ca9e6,
  @Priority = @Priority_a1ecf94ca9e6,
  @RowFilterID = @RowFilterID_a1ecf94ca9e6,
  @RowFilterID_Clear = 1;

GO
