-- =============================================================================================
-- BizApps Orders v5.21.x -- Metadata_Sync (one per release, generated by the build engineer)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --ci` (MJ CLI 6.1.4) against a database built from
-- migrations ONLY: MJ core 6.1.4, bizapps-common v5.47.0, bizapps-tasks v1.6.1, bizapps-accounting
-- v0.16.0, then this app's migrations at `next` (no unreleased seed held back). Push result:
-- 13 created, 5 updated, 385 unchanged, 0 errors.
--
-- CREATED: the entitlement access override -- the MJ.BizApps.Orders.Access.Override
-- authorization and its WaivePaymentHold / DeferCutoff children, the Apply Access Override
-- Decision action and its param, and the Access Override Approval task type (in bizapps-tasks'
-- TaskType, so its EXEC keeps the literal [__mj_BizAppsTasks]); the `orders` API scope with its two
-- child scopes and their grants to the MJAPI API application; and two remote operations.
--
-- UPDATED (5), checked column by column against a copy of the database taken before the push:
-- Capture Payment's InputTypeDefinition and the CheckoutAnswers related-record collection; the
-- rest are unchanged rows the generator re-saves. None reverts a migration.
--
-- NOT INCLUDED: the ML bench output (ml-models, ml-training-pipelines, ml-model-scoring-bindings,
-- record-processes), as in 5.20.
--
-- TRANSFORMS: `EXEC [${flyway:defaultSchema}]` -> `EXEC [${mjSchema}]` (the generator's name for
-- the core schema); string values are untouched. Every create is guarded on ID OR the table's
-- unique key; parents (Authorization, Action, API Scope, API Application, categories) are
-- re-resolved on the host by name or FullPath, and the RemoteOperation update resolves its ID by
-- OperationKey. Idempotent.
-- =============================================================================================
-- SQL Logging Session
-- Session ID: a1b172dc-c729-411f-b114-264f5ac8e6a9
-- Started: 2026-09-30T19:17:50.815Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: Remote Operations (core SP call only)
DECLARE @Name_1954ca6f6360 NVARCHAR(255),
@OperationKey_1954ca6f6360 NVARCHAR(255),
@CategoryID_1954ca6f6360 UNIQUEIDENTIFIER,
@Description_1954ca6f6360 NVARCHAR(MAX),
@InputTypeName_1954ca6f6360 NVARCHAR(255),
@InputTypeDefinition_1954ca6f6360 NVARCHAR(MAX),
@InputTypeIsArray_1954ca6f6360 BIT,
@OutputTypeName_1954ca6f6360 NVARCHAR(255),
@OutputTypeDefinition_1954ca6f6360 NVARCHAR(MAX),
@OutputTypeIsArray_1954ca6f6360 BIT,
@ExecutionMode_1954ca6f6360 NVARCHAR(20),
@RequiredScope_1954ca6f6360 NVARCHAR(255),
@RequiresSystemUser_1954ca6f6360 BIT,
@GenerationType_1954ca6f6360 NVARCHAR(20),
@Code_1954ca6f6360 NVARCHAR(MAX),
@CodeApprovalStatus_1954ca6f6360 NVARCHAR(20),
@CodeApprovedByUserID_1954ca6f6360 UNIQUEIDENTIFIER,
@CodeApprovedAt_1954ca6f6360 DATETIMEOFFSET,
@ContractFingerprint_1954ca6f6360 NVARCHAR(100),
@Status_1954ca6f6360 NVARCHAR(20),
@CacheTTLSeconds_1954ca6f6360 INT,
@TimeoutMS_1954ca6f6360 INT,
@MaxConcurrency_1954ca6f6360 INT,
@CodeLocked_1954ca6f6360 BIT,
@CodeComments_1954ca6f6360 NVARCHAR(MAX),
@Libraries_1954ca6f6360 NVARCHAR(MAX),
@ID_1954ca6f6360 UNIQUEIDENTIFIER
SET
  @Name_1954ca6f6360 = N'Capture Payment'
SET
  @OperationKey_1954ca6f6360 = N'Orders.CapturePayment'
SET
  @CategoryID_1954ca6f6360 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B303'
SET
  @Description_1954ca6f6360 = N'Take a payment and allocate it, in ONE transaction. Writing the header with its allocation lines is no longer the reason - PaymentHeader.Lines is a related-record collection, so a browser payment.Save() does that on its own. What remains is everything a save cannot decide, and all of it must happen in the same act as the write: SETTLING with the payment provider before the money is recorded as taken, recognising a re-submitted capture as the SAME payment rather than a second one, and turning an over-payment into spendable account credit (D68) rather than refusing it. A two-step capture-then-settle flow was rejected because between the steps there would be a captured payment the provider knows nothing about: cash recorded against nothing. The fee is computed server-side and returned, never accepted as input, because a client-supplied fee is a client-supplied general-ledger amount. Preview runs the real capture inside a transaction that always rolls back rather than modelling the arithmetic separately.'
SET
  @InputTypeName_1954ca6f6360 = N'OrdersCapturePaymentInput'
SET
  @InputTypeDefinition_1954ca6f6360 = N'/**
 * Input for `Orders.CapturePayment`.
 *
 * WHY THIS OPERATION EXISTS. Writing a payment header with its allocation lines in one transaction
 * is NOT the reason — `PaymentHeader.Lines` is a related-record collection, so a browser
 * `payment.Save()` does that on its own. What remains is everything a save cannot decide, and all of
 * it has to happen in the same act as the write:
 *
 *   · SETTLING with the payment provider before the money is recorded as taken. The provider is the
 *     authority on whether the money moved; recording first and asking after is how a database ends
 *     up holding cash that was declined.
 *   · Recognising a RE-SUBMITTED capture as the same payment rather than a second one. A
 *     double-clicked button must not take money twice, and only the server can tell the difference.
 *   · Turning an OVER-PAYMENT into account credit (D68) rather than refusing it.
 *
 * A two-step capture-then-settle flow was rejected. Between the steps there would be a captured
 * payment the provider knows nothing about — cash recorded against nothing — and any failure in the
 * second step would leave it there permanently.
 *
 * NOTE ON THE FEE: it is deliberately NOT an input. A client-supplied fee is a client-supplied
 * general-ledger amount, and the client has no access to the provider''s schedule. The server
 * computes it and returns it.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface OrdersCapturePaymentAllocationInput {
    OrderHeaderID: string;
    Amount: number;
    /** Settle a specific LINE rather than the order as a whole. Optional. */
    OrderLineID?: string | null;
    /**
     * Apply this share to a named instalment of the order (PR #220). Optional; without it the
     * database cascades the money oldest-due-first. The poller names the instalment its rail
     * invoice was issued for, so an instalment payment lands on the instalment it paid.
     */
    OrderHeaderPaymentScheduleID?: string | null;
}

/** Instrument detail, when the tender needs one. Never the PAN — only tokens and references (D38). */
export interface OrdersCapturePaymentDetailInput {
    PaymentProviderID?: string | null;
    ProviderInstrumentRef?: string | null;
    SourceCustomerPaymentMethodID?: string | null;
    ReferenceNumber?: string | null;
    InstrumentDate?: string | null;
}

export interface OrdersCapturePaymentInput {
    /**
     * The `PaymentIntent` row this payment settles, from `Orders.OpenPaymentIntent`.
     *
     * REQUIRED FOR A GATEWAY-COLLECTED PAYMENT and meaningless without one. `PaymentHeaderEntityServer`
     * reads the gateway''s own intent string THROUGH this row on the way to capture; a provider-backed
     * payment that does not carry it is refused with "there is nothing for the gateway to capture".
     *
     * Omitted for a RECORDED payment — a cheque, a wire, cash — where the money moved before any of
     * this code ran and there is no gateway to ask.
     */
    PaymentIntentID?: string | null;

    /**
     * Gross amount received. Must equal the sum of `Allocations[].Amount` (D68).
     *
     * The invariant is checked HERE rather than trusted from the caller: the page enforces it before
     * emitting, but the operation is the trust boundary, and a mismatch means cash recorded against
     * nothing or an order credited with money that never arrived.
     */
    Amount: number;

    /** Which company received the cash. */
    ReceivingCompanyID: string;

    /** Who paid. Exactly one of these. */
    BillToOrganizationID?: string | null;
    BillToPersonID?: string | null;

    /**
     * Tender by CODE, not id — the client should not have to resolve a lookup to take money. An
     * unknown code is refused by name rather than falling back to a default tender, because a
     * payment silently recorded as the wrong kind is invisible until somebody reconciles.
     */
    TenderCode: string;

    /** ''YYYY-MM-DD''. Defaults to today. */
    PaymentDate?: string;

    /** Cheque number, wire confirmation, free text. */
    Reference?: string | null;
    Notes?: string | null;

    /** Where the money lands. Must be non-empty. */
    Allocations: OrdersCapturePaymentAllocationInput[];

    PaymentDetail?: OrdersCapturePaymentDetailInput | null;

    /** Spend a stored-value balance instead of taking new cash. */
    SourceOrderHeaderID?: string | null;

    /**
     * Makes this call safe to retry. A double-clicked Capture, a retry after a timeout, a queue
     * redelivery — all must take the money ONCE.
     *
     * Supply a token the CLIENT generates when the user opens the form, not one derived from the
     * amount: two people legitimately paying the same amount on the same day must both go through.
     * A repeat call with the same token returns the ORIGINAL payment and sets `WasRetry`, rather
     * than taking money again or reporting a spurious failure.
     *
     * Optional. Without it a retry takes the payment twice, which is the caller''s choice to make.
     */
    IdempotencyKey?: string | null;

    /**
     * Compute and validate WITHOUT writing.
     *
     * Runs the REAL capture inside a transaction that always rolls back — not a separate model of
     * the arithmetic. A preview that reimplements the calculation eventually disagrees with the
     * capture, and the disagreement surfaces as a balanced journal entry for the wrong amount, which
     * nothing downstream can catch.
     */
    Preview?: boolean;
}
'
SET
  @InputTypeIsArray_1954ca6f6360 = 0
SET
  @OutputTypeName_1954ca6f6360 = N'OrdersCapturePaymentOutput'
SET
  @OutputTypeDefinition_1954ca6f6360 = N'/**
 * Output for `Orders.CapturePayment`.
 *
 * Carries the payment as saved, and adds
 * `OrderEffects` — what each order looks like AFTER the payment — so a screen can show the result
 * without a second round trip.
 *
 * EVERYTHING HERE IS READ BACK FROM WHAT THE ENGINE COMPUTED, never recomputed. Recomputing is the
 * mistake that produces a screen quietly disagreeing with the ledger, and the disagreement shows up
 * as a balanced journal entry for the wrong amount, which nothing downstream can catch.
 *
 * `JournalEntryPreview` and `BlockerResult` are declared in orders-save-order.input.ts and shared —
 * CodeGen emits every type file into one namespace, so they are referenced rather than redeclared.
 *
 * NO import statements — definitions are emitted verbatim.
 */

/** What one order looks like after the payment landed on it. */
export interface CapturePaymentOrderEffect {
    OrderHeaderID: string;
    OrderNumber: string;
    /** As the rollup triggers left it, not as the operation calculated it. */
    AmountPaid: number;
    Balance: number;
    PaymentStatus: string;
    /**
     * True when this order''s balance went NEGATIVE — the customer over-paid and the surplus is now
     * spendable credit (D68). Not an error: the account-credit screen depends on these existing.
     */
    HasCredit: boolean;
}

export interface OrdersCapturePaymentOutput {
    Success: boolean;
    Message?: string;

    PaymentHeaderID?: string | null;
    PaymentNumber?: string | null;
    /** Expected ''Captured''. Null on a refusal or a preview that found blockers. */
    Status?: string | null;

    /** As booked, after the engine has had its say. */
    Amount?: number;
    /**
     * The provider''s cut, computed SERVER-SIDE. Never accepted as input — a client-supplied fee is a
     * client-supplied general-ledger amount, and the client cannot see the provider''s schedule.
     * Zero for tenders with no provider.
     */
    ProcessingFeeAmount?: number;
    /** What actually reached the bank: Amount minus the fee. */
    NetAmount?: number;

    OrderEffects?: CapturePaymentOrderEffect[];

    /** The entries this produced, so a screen can show what moved. */
    JournalEntries?: JournalEntryPreview[];
    EntryCount?: number;
    AllBalanced?: boolean;

    /** Refusals, in the shape the UI already renders. */
    Blockers?: BlockerResult[];

    /**
     * True when nothing was written because this was a preview. The numbers above are what a real
     * capture WOULD produce — they come from running it and rolling back, not from a second model.
     */
    WasPreview?: boolean;

    /**
     * True when an `IdempotencyKey` matched an existing payment and THIS CALL TOOK NO MONEY. The
     * fields above describe that original payment, so a retry after a timeout shows the user what
     * actually happened rather than a spurious failure or a second charge.
     */
    WasRetry?: boolean;
    /** Echoed back so a caller can correlate, and so a retry is legible in a log. */
    IdempotencyKey?: string | null;
}

/**
 * A journal entry the capture will (or did) produce. Read-only everywhere in Orders.
 *
 * Declared here because this is now the only operation that reports entries — it moved with its last
 * user rather than being kept alive in a shared file nobody owned.
 */
export interface JournalEntryPreview {
    CompanyID: string;
    CompanyName: string;
    /** Which order line caused it. One entry per line, always. */
    LineNumber?: number | null;
    /** Set once the entry exists; null while previewing. */
    JournalEntryID?: string | null;
    EntryType: string;
    Balanced: boolean;
    Lines: Array<{ Side: ''Dr'' | ''Cr''; AccountRole: string; AccountName: string; Amount: number }>;
}
'
SET
  @OutputTypeIsArray_1954ca6f6360 = 0
SET
  @ExecutionMode_1954ca6f6360 = N'Sync'
SET
  @RequiredScope_1954ca6f6360 = N'orders:write'
SET
  @RequiresSystemUser_1954ca6f6360 = 0
SET
  @GenerationType_1954ca6f6360 = N'Manual'
SET
  @CodeApprovalStatus_1954ca6f6360 = N'Approved'
SET
  @Status_1954ca6f6360 = N'Active'
SET
  @CodeLocked_1954ca6f6360 = 0
SET
  @ID_1954ca6f6360 = '87E03341-1F8F-4F1E-A72D-25311266693A' 
SELECT TOP 1 @ID_1954ca6f6360 = [ID] FROM [${mjSchema}].[RemoteOperation] WHERE [OperationKey] = @OperationKey_1954ca6f6360 ORDER BY CASE WHEN [ID] = @ID_1954ca6f6360 THEN 0 ELSE 1 END
EXEC [${mjSchema}].spUpdateRemoteOperation @Name = @Name_1954ca6f6360,
  @OperationKey = @OperationKey_1954ca6f6360,
  @CategoryID = @CategoryID_1954ca6f6360,
  @Description = @Description_1954ca6f6360,
  @InputTypeName = @InputTypeName_1954ca6f6360,
  @InputTypeDefinition = @InputTypeDefinition_1954ca6f6360,
  @InputTypeIsArray = @InputTypeIsArray_1954ca6f6360,
  @OutputTypeName = @OutputTypeName_1954ca6f6360,
  @OutputTypeDefinition = @OutputTypeDefinition_1954ca6f6360,
  @OutputTypeIsArray = @OutputTypeIsArray_1954ca6f6360,
  @ExecutionMode = @ExecutionMode_1954ca6f6360,
  @RequiredScope = @RequiredScope_1954ca6f6360,
  @RequiresSystemUser = @RequiresSystemUser_1954ca6f6360,
  @GenerationType = @GenerationType_1954ca6f6360,
  @Code = @Code_1954ca6f6360,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_1954ca6f6360,
  @CodeApprovedByUserID = @CodeApprovedByUserID_1954ca6f6360,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_1954ca6f6360,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_1954ca6f6360,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_1954ca6f6360,
  @CacheTTLSeconds = @CacheTTLSeconds_1954ca6f6360,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_1954ca6f6360,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_1954ca6f6360,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_1954ca6f6360,
  @CodeComments = @CodeComments_1954ca6f6360,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_1954ca6f6360,
  @Libraries_Clear = 1,
  @ID = @ID_1954ca6f6360;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @ID_e25e7ac01ec0 UNIQUEIDENTIFIER,
@Name_e25e7ac01ec0 NVARCHAR(255),
@OperationKey_e25e7ac01ec0 NVARCHAR(255),
@CategoryID_e25e7ac01ec0 UNIQUEIDENTIFIER,
@Description_e25e7ac01ec0 NVARCHAR(MAX),
@InputTypeName_e25e7ac01ec0 NVARCHAR(255),
@InputTypeDefinition_e25e7ac01ec0 NVARCHAR(MAX),
@InputTypeIsArray_e25e7ac01ec0 BIT,
@OutputTypeName_e25e7ac01ec0 NVARCHAR(255),
@OutputTypeDefinition_e25e7ac01ec0 NVARCHAR(MAX),
@OutputTypeIsArray_e25e7ac01ec0 BIT,
@ExecutionMode_e25e7ac01ec0 NVARCHAR(20),
@RequiredScope_e25e7ac01ec0 NVARCHAR(255),
@RequiresSystemUser_e25e7ac01ec0 BIT,
@GenerationType_e25e7ac01ec0 NVARCHAR(20),
@Code_e25e7ac01ec0 NVARCHAR(MAX),
@CodeApprovalStatus_e25e7ac01ec0 NVARCHAR(20),
@CodeApprovedByUserID_e25e7ac01ec0 UNIQUEIDENTIFIER,
@CodeApprovedAt_e25e7ac01ec0 DATETIMEOFFSET,
@ContractFingerprint_e25e7ac01ec0 NVARCHAR(100),
@Status_e25e7ac01ec0 NVARCHAR(20),
@CacheTTLSeconds_e25e7ac01ec0 INT,
@TimeoutMS_e25e7ac01ec0 INT,
@MaxConcurrency_e25e7ac01ec0 INT,
@CodeLocked_e25e7ac01ec0 BIT,
@CodeComments_e25e7ac01ec0 NVARCHAR(MAX),
@Libraries_e25e7ac01ec0 NVARCHAR(MAX)
SET
  @ID_e25e7ac01ec0 = '8F2A296E-A2B7-4EBB-9B00-789B17CBA9DC'
SET
  @Name_e25e7ac01ec0 = N'Request Access Override'
SET
  @OperationKey_e25e7ac01ec0 = N'Orders.RequestAccessOverride'
SET
  @CategoryID_e25e7ac01ec0 = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B306'
SET
  @Description_e25e7ac01ec0 = N'Request an exception to payment-gated access on one order: WaivePaymentHold lifts the hold on grants awaiting payment, DeferCutoff lifts the renewal cutoff. Requires a reason, a last day, and the MJ.BizApps.Orders.Access.Override authorization for that type. Writes a Requested override and raises its Tasks approval; access changes only once it is approved.'
SET
  @InputTypeName_e25e7ac01ec0 = N'RequestAccessOverrideInput'
SET
  @InputTypeDefinition_e25e7ac01ec0 = N'/**
 * Input for `Orders.RequestAccessOverride`.
 *
 * An exception to payment-gated access on one order. Nothing changes until it is approved through
 * the task this raises.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface RequestAccessOverrideInput {
    OrderHeaderID: string;
    /** WaivePaymentHold lifts the hold on grants awaiting payment; DeferCutoff lifts the renewal cutoff. */
    OverrideType: ''WaivePaymentHold'' | ''DeferCutoff'';
    /** Why the exception is needed. Required. */
    Reason: string;
    /** Last day the override holds, YYYY-MM-DD, inclusive. Required; not before today. */
    EffectiveThrough: string;
}
'
SET
  @InputTypeIsArray_e25e7ac01ec0 = 0
SET
  @OutputTypeName_e25e7ac01ec0 = N'RequestAccessOverrideOutput'
SET
  @OutputTypeDefinition_e25e7ac01ec0 = N'/**
 * Output of `Orders.RequestAccessOverride`.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface RequestAccessOverrideOutput {
    Success: boolean;
    Message?: string;
    AccessOverrideID?: string;
    ApprovalTaskID?: string;
}
'
SET
  @OutputTypeIsArray_e25e7ac01ec0 = 0
SET
  @ExecutionMode_e25e7ac01ec0 = N'Sync'
SET
  @RequiredScope_e25e7ac01ec0 = N'orders:write'
SET
  @RequiresSystemUser_e25e7ac01ec0 = 0
SET
  @GenerationType_e25e7ac01ec0 = N'Manual'
SET
  @CodeApprovalStatus_e25e7ac01ec0 = N'Approved'
SET
  @Status_e25e7ac01ec0 = N'Active'
SET
  @CodeLocked_e25e7ac01ec0 = 0

SELECT TOP 1 @CategoryID_e25e7ac01ec0 = [ID] FROM [${mjSchema}].[RemoteOperationCategory] WHERE [Name] = N'Entitlements' ORDER BY CASE WHEN [ID] = @CategoryID_e25e7ac01ec0 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[RemoteOperation]
               WHERE [ID] = @ID_e25e7ac01ec0
                  OR ([OperationKey] = @OperationKey_e25e7ac01ec0))
EXEC [${mjSchema}].spCreateRemoteOperation @ID = @ID_e25e7ac01ec0,
  @Name = @Name_e25e7ac01ec0,
  @OperationKey = @OperationKey_e25e7ac01ec0,
  @CategoryID = @CategoryID_e25e7ac01ec0,
  @Description = @Description_e25e7ac01ec0,
  @InputTypeName = @InputTypeName_e25e7ac01ec0,
  @InputTypeDefinition = @InputTypeDefinition_e25e7ac01ec0,
  @InputTypeIsArray = @InputTypeIsArray_e25e7ac01ec0,
  @OutputTypeName = @OutputTypeName_e25e7ac01ec0,
  @OutputTypeDefinition = @OutputTypeDefinition_e25e7ac01ec0,
  @OutputTypeIsArray = @OutputTypeIsArray_e25e7ac01ec0,
  @ExecutionMode = @ExecutionMode_e25e7ac01ec0,
  @RequiredScope = @RequiredScope_e25e7ac01ec0,
  @RequiresSystemUser = @RequiresSystemUser_e25e7ac01ec0,
  @GenerationType = @GenerationType_e25e7ac01ec0,
  @Code = @Code_e25e7ac01ec0,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_e25e7ac01ec0,
  @CodeApprovedByUserID = @CodeApprovedByUserID_e25e7ac01ec0,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_e25e7ac01ec0,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_e25e7ac01ec0,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_e25e7ac01ec0,
  @CacheTTLSeconds = @CacheTTLSeconds_e25e7ac01ec0,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_e25e7ac01ec0,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_e25e7ac01ec0,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_e25e7ac01ec0,
  @CodeComments = @CodeComments_e25e7ac01ec0,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_e25e7ac01ec0,
  @Libraries_Clear = 1;

GO

-- Save MJ: Remote Operations (core SP call only)
DECLARE @ID_a8fd313fe1cc UNIQUEIDENTIFIER,
@Name_a8fd313fe1cc NVARCHAR(255),
@OperationKey_a8fd313fe1cc NVARCHAR(255),
@CategoryID_a8fd313fe1cc UNIQUEIDENTIFIER,
@Description_a8fd313fe1cc NVARCHAR(MAX),
@InputTypeName_a8fd313fe1cc NVARCHAR(255),
@InputTypeDefinition_a8fd313fe1cc NVARCHAR(MAX),
@InputTypeIsArray_a8fd313fe1cc BIT,
@OutputTypeName_a8fd313fe1cc NVARCHAR(255),
@OutputTypeDefinition_a8fd313fe1cc NVARCHAR(MAX),
@OutputTypeIsArray_a8fd313fe1cc BIT,
@ExecutionMode_a8fd313fe1cc NVARCHAR(20),
@RequiredScope_a8fd313fe1cc NVARCHAR(255),
@RequiresSystemUser_a8fd313fe1cc BIT,
@GenerationType_a8fd313fe1cc NVARCHAR(20),
@Code_a8fd313fe1cc NVARCHAR(MAX),
@CodeApprovalStatus_a8fd313fe1cc NVARCHAR(20),
@CodeApprovedByUserID_a8fd313fe1cc UNIQUEIDENTIFIER,
@CodeApprovedAt_a8fd313fe1cc DATETIMEOFFSET,
@ContractFingerprint_a8fd313fe1cc NVARCHAR(100),
@Status_a8fd313fe1cc NVARCHAR(20),
@CacheTTLSeconds_a8fd313fe1cc INT,
@TimeoutMS_a8fd313fe1cc INT,
@MaxConcurrency_a8fd313fe1cc INT,
@CodeLocked_a8fd313fe1cc BIT,
@CodeComments_a8fd313fe1cc NVARCHAR(MAX),
@Libraries_a8fd313fe1cc NVARCHAR(MAX)
SET
  @ID_a8fd313fe1cc = '6F1BE4BC-990A-4C93-B811-49F45B343397'
SET
  @Name_a8fd313fe1cc = N'Record Access Override Decision'
SET
  @OperationKey_a8fd313fe1cc = N'Orders.RecordAccessOverrideDecision'
SET
  @CategoryID_a8fd313fe1cc = 'B1C4E2A0-6F3D-4A18-9E52-7C0D5A81B306'
SET
  @Description_a8fd313fe1cc = N'Approve or reject a requested access override. Records the decision on the override''s Tasks approval and applies it: an approval re-decides the order''s grants at once.'
SET
  @InputTypeName_a8fd313fe1cc = N'RecordAccessOverrideDecisionInput'
SET
  @InputTypeDefinition_a8fd313fe1cc = N'/**
 * Input for `Orders.RecordAccessOverrideDecision`.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface RecordAccessOverrideDecisionInput {
    AccessOverrideID: string;
    /** A Tasks decision outcome code: Approved, ApprovedWithConditions or Rejected. */
    Outcome: string;
    Notes?: string;
}
'
SET
  @InputTypeIsArray_a8fd313fe1cc = 0
SET
  @OutputTypeName_a8fd313fe1cc = N'AccessOverrideDecisionOutput'
SET
  @OutputTypeDefinition_a8fd313fe1cc = N'/**
 * Output of `Orders.RecordAccessOverrideDecision`.
 *
 * NO import statements — definitions are emitted verbatim.
 */
export interface AccessOverrideDecisionOutput {
    Success: boolean;
    Message?: string;
    /** The override''s status after the call. */
    Status?: string;
    /** Grants whose status changed because the override was approved. */
    GrantsChanged?: number;
}
'
SET
  @OutputTypeIsArray_a8fd313fe1cc = 0
SET
  @ExecutionMode_a8fd313fe1cc = N'Sync'
SET
  @RequiredScope_a8fd313fe1cc = N'orders:write'
SET
  @RequiresSystemUser_a8fd313fe1cc = 0
SET
  @GenerationType_a8fd313fe1cc = N'Manual'
SET
  @CodeApprovalStatus_a8fd313fe1cc = N'Approved'
SET
  @Status_a8fd313fe1cc = N'Active'
SET
  @CodeLocked_a8fd313fe1cc = 0

SELECT TOP 1 @CategoryID_a8fd313fe1cc = [ID] FROM [${mjSchema}].[RemoteOperationCategory] WHERE [Name] = N'Entitlements' ORDER BY CASE WHEN [ID] = @CategoryID_a8fd313fe1cc THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[RemoteOperation]
               WHERE [ID] = @ID_a8fd313fe1cc
                  OR ([OperationKey] = @OperationKey_a8fd313fe1cc))
EXEC [${mjSchema}].spCreateRemoteOperation @ID = @ID_a8fd313fe1cc,
  @Name = @Name_a8fd313fe1cc,
  @OperationKey = @OperationKey_a8fd313fe1cc,
  @CategoryID = @CategoryID_a8fd313fe1cc,
  @Description = @Description_a8fd313fe1cc,
  @InputTypeName = @InputTypeName_a8fd313fe1cc,
  @InputTypeDefinition = @InputTypeDefinition_a8fd313fe1cc,
  @InputTypeIsArray = @InputTypeIsArray_a8fd313fe1cc,
  @OutputTypeName = @OutputTypeName_a8fd313fe1cc,
  @OutputTypeDefinition = @OutputTypeDefinition_a8fd313fe1cc,
  @OutputTypeIsArray = @OutputTypeIsArray_a8fd313fe1cc,
  @ExecutionMode = @ExecutionMode_a8fd313fe1cc,
  @RequiredScope = @RequiredScope_a8fd313fe1cc,
  @RequiresSystemUser = @RequiresSystemUser_a8fd313fe1cc,
  @GenerationType = @GenerationType_a8fd313fe1cc,
  @Code = @Code_a8fd313fe1cc,
  @Code_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_a8fd313fe1cc,
  @CodeApprovedByUserID = @CodeApprovedByUserID_a8fd313fe1cc,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_a8fd313fe1cc,
  @CodeApprovedAt_Clear = 1,
  @ContractFingerprint = @ContractFingerprint_a8fd313fe1cc,
  @ContractFingerprint_Clear = 1,
  @Status = @Status_a8fd313fe1cc,
  @CacheTTLSeconds = @CacheTTLSeconds_a8fd313fe1cc,
  @CacheTTLSeconds_Clear = 1,
  @TimeoutMS = @TimeoutMS_a8fd313fe1cc,
  @TimeoutMS_Clear = 1,
  @MaxConcurrency = @MaxConcurrency_a8fd313fe1cc,
  @MaxConcurrency_Clear = 1,
  @CodeLocked = @CodeLocked_a8fd313fe1cc,
  @CodeComments = @CodeComments_a8fd313fe1cc,
  @CodeComments_Clear = 1,
  @Libraries = @Libraries_a8fd313fe1cc,
  @Libraries_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_074a5d4947c4 UNIQUEIDENTIFIER,
@Name_074a5d4947c4 NVARCHAR(100),
@Category_074a5d4947c4 NVARCHAR(100),
@Description_074a5d4947c4 NVARCHAR(500),
@ParentID_074a5d4947c4 UNIQUEIDENTIFIER,
@FullPath_074a5d4947c4 NVARCHAR(500),
@ResourceType_074a5d4947c4 NVARCHAR(50),
@IsActive_074a5d4947c4 BIT,
@UIConfig_074a5d4947c4 NVARCHAR(MAX)
SET
  @ID_074a5d4947c4 = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @Name_074a5d4947c4 = N'orders'
SET
  @Category_074a5d4947c4 = N'Orders'
SET
  @Description_074a5d4947c4 = N'Parent scope for Orders remote operations'
SET
  @FullPath_074a5d4947c4 = N'orders'
SET
  @IsActive_074a5d4947c4 = 1

IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_074a5d4947c4
                  OR ([FullPath] = @FullPath_074a5d4947c4))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_074a5d4947c4,
  @Name = @Name_074a5d4947c4,
  @Category = @Category_074a5d4947c4,
  @Description = @Description_074a5d4947c4,
  @ParentID = @ParentID_074a5d4947c4,
  @ParentID_Clear = 1,
  @FullPath = @FullPath_074a5d4947c4,
  @ResourceType = @ResourceType_074a5d4947c4,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_074a5d4947c4,
  @UIConfig = @UIConfig_074a5d4947c4,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_9536c6f8a8f7 UNIQUEIDENTIFIER,
@Name_9536c6f8a8f7 NVARCHAR(100),
@Category_9536c6f8a8f7 NVARCHAR(100),
@Description_9536c6f8a8f7 NVARCHAR(500),
@ParentID_9536c6f8a8f7 UNIQUEIDENTIFIER,
@FullPath_9536c6f8a8f7 NVARCHAR(500),
@ResourceType_9536c6f8a8f7 NVARCHAR(50),
@IsActive_9536c6f8a8f7 BIT,
@UIConfig_9536c6f8a8f7 NVARCHAR(MAX)
SET
  @ID_9536c6f8a8f7 = '1C647BE9-702B-4D71-8F56-D6E6EB24C5F7'
SET
  @Name_9536c6f8a8f7 = N'entitlement-check'
SET
  @Category_9536c6f8a8f7 = N'Orders'
SET
  @Description_9536c6f8a8f7 = N'Check whether a person holds an entitlement (Orders.CheckEntitlement)'
SET
  @ParentID_9536c6f8a8f7 = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_9536c6f8a8f7 = N'orders:entitlement-check'
SET
  @IsActive_9536c6f8a8f7 = 1

SELECT TOP 1 @ParentID_9536c6f8a8f7 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_9536c6f8a8f7 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_9536c6f8a8f7
                  OR ([FullPath] = @FullPath_9536c6f8a8f7)
                  OR (([ParentID] = @ParentID_9536c6f8a8f7 OR ([ParentID] IS NULL AND @ParentID_9536c6f8a8f7 IS NULL)) AND [Name] = @Name_9536c6f8a8f7))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_9536c6f8a8f7,
  @Name = @Name_9536c6f8a8f7,
  @Category = @Category_9536c6f8a8f7,
  @Description = @Description_9536c6f8a8f7,
  @ParentID = @ParentID_9536c6f8a8f7,
  @FullPath = @FullPath_9536c6f8a8f7,
  @ResourceType = @ResourceType_9536c6f8a8f7,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_9536c6f8a8f7,
  @UIConfig = @UIConfig_9536c6f8a8f7,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Scopes (core SP call only)
DECLARE @ID_4d85a5a5acef UNIQUEIDENTIFIER,
@Name_4d85a5a5acef NVARCHAR(100),
@Category_4d85a5a5acef NVARCHAR(100),
@Description_4d85a5a5acef NVARCHAR(500),
@ParentID_4d85a5a5acef UNIQUEIDENTIFIER,
@FullPath_4d85a5a5acef NVARCHAR(500),
@ResourceType_4d85a5a5acef NVARCHAR(50),
@IsActive_4d85a5a5acef BIT,
@UIConfig_4d85a5a5acef NVARCHAR(MAX)
SET
  @ID_4d85a5a5acef = 'B0BF6F7A-2FAF-4F99-8E71-77E7CCDB1A5A'
SET
  @Name_4d85a5a5acef = N'entitlement-read'
SET
  @Category_4d85a5a5acef = N'Orders'
SET
  @Description_4d85a5a5acef = N'List a person''s entitlements (Orders.ListEntitlements)'
SET
  @ParentID_4d85a5a5acef = 'B01CD343-1430-420E-B71D-143D2A5C1DF1'
SET
  @FullPath_4d85a5a5acef = N'orders:entitlement-read'
SET
  @IsActive_4d85a5a5acef = 1

SELECT TOP 1 @ParentID_4d85a5a5acef = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders' ORDER BY CASE WHEN [ID] = @ParentID_4d85a5a5acef THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIScope]
               WHERE [ID] = @ID_4d85a5a5acef
                  OR ([FullPath] = @FullPath_4d85a5a5acef)
                  OR (([ParentID] = @ParentID_4d85a5a5acef OR ([ParentID] IS NULL AND @ParentID_4d85a5a5acef IS NULL)) AND [Name] = @Name_4d85a5a5acef))
EXEC [${mjSchema}].spCreateAPIScope @ID = @ID_4d85a5a5acef,
  @Name = @Name_4d85a5a5acef,
  @Category = @Category_4d85a5a5acef,
  @Description = @Description_4d85a5a5acef,
  @ParentID = @ParentID_4d85a5a5acef,
  @FullPath = @FullPath_4d85a5a5acef,
  @ResourceType = @ResourceType_4d85a5a5acef,
  @ResourceType_Clear = 1,
  @IsActive = @IsActive_4d85a5a5acef,
  @UIConfig = @UIConfig_4d85a5a5acef,
  @UIConfig_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_3965b200817c UNIQUEIDENTIFIER,
@ApplicationID_3965b200817c UNIQUEIDENTIFIER,
@ScopeID_3965b200817c UNIQUEIDENTIFIER,
@ResourcePattern_3965b200817c NVARCHAR(750),
@PatternType_3965b200817c NVARCHAR(20),
@IsDeny_3965b200817c BIT,
@Priority_3965b200817c INT,
@RowFilterID_3965b200817c UNIQUEIDENTIFIER
SET
  @ID_3965b200817c = '6AAC64F9-A00C-4F9F-9F32-C9DD3230A69D'
SET
  @ApplicationID_3965b200817c = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_3965b200817c = '1C647BE9-702B-4D71-8F56-D6E6EB24C5F7'
SET
  @ResourcePattern_3965b200817c = N'*'
SET
  @PatternType_3965b200817c = N'Include'
SET
  @IsDeny_3965b200817c = 0
SET
  @Priority_3965b200817c = 0

SELECT TOP 1 @ApplicationID_3965b200817c = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_3965b200817c THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_3965b200817c = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:entitlement-check' ORDER BY CASE WHEN [ID] = @ScopeID_3965b200817c THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_3965b200817c
                  OR ([ApplicationID] = @ApplicationID_3965b200817c AND [ScopeID] = @ScopeID_3965b200817c AND ([ResourcePattern] = @ResourcePattern_3965b200817c OR ([ResourcePattern] IS NULL AND @ResourcePattern_3965b200817c IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_3965b200817c,
  @ApplicationID = @ApplicationID_3965b200817c,
  @ScopeID = @ScopeID_3965b200817c,
  @ResourcePattern = @ResourcePattern_3965b200817c,
  @PatternType = @PatternType_3965b200817c,
  @IsDeny = @IsDeny_3965b200817c,
  @Priority = @Priority_3965b200817c,
  @RowFilterID = @RowFilterID_3965b200817c,
  @RowFilterID_Clear = 1;

GO

-- Save MJ: API Application Scopes (core SP call only)
DECLARE @ID_4c99c0f01c90 UNIQUEIDENTIFIER,
@ApplicationID_4c99c0f01c90 UNIQUEIDENTIFIER,
@ScopeID_4c99c0f01c90 UNIQUEIDENTIFIER,
@ResourcePattern_4c99c0f01c90 NVARCHAR(750),
@PatternType_4c99c0f01c90 NVARCHAR(20),
@IsDeny_4c99c0f01c90 BIT,
@Priority_4c99c0f01c90 INT,
@RowFilterID_4c99c0f01c90 UNIQUEIDENTIFIER
SET
  @ID_4c99c0f01c90 = 'ACA9A012-0AC5-432C-A8B9-C387CA25813C'
SET
  @ApplicationID_4c99c0f01c90 = '15A906BC-55F3-489C-A7D3-F8DAE9F26D6B'
SET
  @ScopeID_4c99c0f01c90 = 'B0BF6F7A-2FAF-4F99-8E71-77E7CCDB1A5A'
SET
  @ResourcePattern_4c99c0f01c90 = N'*'
SET
  @PatternType_4c99c0f01c90 = N'Include'
SET
  @IsDeny_4c99c0f01c90 = 0
SET
  @Priority_4c99c0f01c90 = 0

SELECT TOP 1 @ApplicationID_4c99c0f01c90 = [ID] FROM [${mjSchema}].[APIApplication] WHERE [Name] = N'MJAPI' ORDER BY CASE WHEN [ID] = @ApplicationID_4c99c0f01c90 THEN 0 ELSE 1 END
SELECT TOP 1 @ScopeID_4c99c0f01c90 = [ID] FROM [${mjSchema}].[APIScope] WHERE [FullPath] = N'orders:entitlement-read' ORDER BY CASE WHEN [ID] = @ScopeID_4c99c0f01c90 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[APIApplicationScope]
               WHERE [ID] = @ID_4c99c0f01c90
                  OR ([ApplicationID] = @ApplicationID_4c99c0f01c90 AND [ScopeID] = @ScopeID_4c99c0f01c90 AND ([ResourcePattern] = @ResourcePattern_4c99c0f01c90 OR ([ResourcePattern] IS NULL AND @ResourcePattern_4c99c0f01c90 IS NULL))))
EXEC [${mjSchema}].spCreateAPIApplicationScope @ID = @ID_4c99c0f01c90,
  @ApplicationID = @ApplicationID_4c99c0f01c90,
  @ScopeID = @ScopeID_4c99c0f01c90,
  @ResourcePattern = @ResourcePattern_4c99c0f01c90,
  @PatternType = @PatternType_4c99c0f01c90,
  @IsDeny = @IsDeny_4c99c0f01c90,
  @Priority = @Priority_4c99c0f01c90,
  @RowFilterID = @RowFilterID_4c99c0f01c90,
  @RowFilterID_Clear = 1;

GO

-- Save MJ: Actions (core SP call only)
DECLARE @ID_bd01eb9d473b UNIQUEIDENTIFIER,
@CategoryID_bd01eb9d473b UNIQUEIDENTIFIER,
@Name_bd01eb9d473b NVARCHAR(425),
@Description_bd01eb9d473b NVARCHAR(MAX),
@Type_bd01eb9d473b NVARCHAR(20),
@UserPrompt_bd01eb9d473b NVARCHAR(MAX),
@UserComments_bd01eb9d473b NVARCHAR(MAX),
@Code_bd01eb9d473b NVARCHAR(MAX),
@CodeComments_bd01eb9d473b NVARCHAR(MAX),
@CodeApprovalStatus_bd01eb9d473b NVARCHAR(20),
@CodeApprovalComments_bd01eb9d473b NVARCHAR(MAX),
@CodeApprovedByUserID_bd01eb9d473b UNIQUEIDENTIFIER,
@CodeApprovedAt_bd01eb9d473b DATETIMEOFFSET,
@CodeLocked_bd01eb9d473b BIT,
@ForceCodeGeneration_bd01eb9d473b BIT,
@RetentionPeriod_bd01eb9d473b INT,
@Status_bd01eb9d473b NVARCHAR(20),
@DriverClass_bd01eb9d473b NVARCHAR(255),
@ParentID_bd01eb9d473b UNIQUEIDENTIFIER,
@IconClass_bd01eb9d473b NVARCHAR(100),
@DefaultCompactPromptID_bd01eb9d473b UNIQUEIDENTIFIER,
@Config_bd01eb9d473b NVARCHAR(MAX),
@RuntimeActionConfiguration_bd01eb9d473b NVARCHAR(MAX),
@MaxExecutionTimeMS_bd01eb9d473b INT,
@CreatedByAgentID_bd01eb9d473b UNIQUEIDENTIFIER
SET
  @ID_bd01eb9d473b = '442E3FEA-1838-42F9-AE34-72BB4E79C833'
SET
  @CategoryID_bd01eb9d473b = '359F5241-25D1-4949-A74F-C20CA3EECC3A'
SET
  @Name_bd01eb9d473b = N'Apply Access Override Decision'
SET
  @Description_bd01eb9d473b = N'Apply the outcome of an access override''s approval task to the override: an approval makes it Approved and re-decides the order''s grants; a rejection makes it Rejected; a task closed any other way withdraws it. Idempotent.'
SET
  @Type_bd01eb9d473b = N'Custom'
SET
  @UserPrompt_bd01eb9d473b = N'Apply the decision on an access override approval task.'
SET
  @CodeApprovalStatus_bd01eb9d473b = N'Approved'
SET
  @CodeLocked_bd01eb9d473b = 0
SET
  @ForceCodeGeneration_bd01eb9d473b = 0
SET
  @Status_bd01eb9d473b = N'Active'
SET
  @DriverClass_bd01eb9d473b = N'Orders.ApplyAccessOverrideDecision'
SET
  @IconClass_bd01eb9d473b = N'fa-solid fa-stamp' 
SELECT TOP 1 @CategoryID_bd01eb9d473b = [ID] FROM [${mjSchema}].[ActionCategory] WHERE [Name] = N'Orders' ORDER BY CASE WHEN [ID] = @CategoryID_bd01eb9d473b THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[Action]
               WHERE [ID] = @ID_bd01eb9d473b)
EXEC [${mjSchema}].spCreateAction @ID = @ID_bd01eb9d473b,
  @CategoryID = @CategoryID_bd01eb9d473b,
  @Name = @Name_bd01eb9d473b,
  @Description = @Description_bd01eb9d473b,
  @Type = @Type_bd01eb9d473b,
  @UserPrompt = @UserPrompt_bd01eb9d473b,
  @UserComments = @UserComments_bd01eb9d473b,
  @UserComments_Clear = 1,
  @Code = @Code_bd01eb9d473b,
  @Code_Clear = 1,
  @CodeComments = @CodeComments_bd01eb9d473b,
  @CodeComments_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_bd01eb9d473b,
  @CodeApprovalComments = @CodeApprovalComments_bd01eb9d473b,
  @CodeApprovalComments_Clear = 1,
  @CodeApprovedByUserID = @CodeApprovedByUserID_bd01eb9d473b,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_bd01eb9d473b,
  @CodeApprovedAt_Clear = 1,
  @CodeLocked = @CodeLocked_bd01eb9d473b,
  @ForceCodeGeneration = @ForceCodeGeneration_bd01eb9d473b,
  @RetentionPeriod = @RetentionPeriod_bd01eb9d473b,
  @RetentionPeriod_Clear = 1,
  @Status = @Status_bd01eb9d473b,
  @DriverClass = @DriverClass_bd01eb9d473b,
  @ParentID = @ParentID_bd01eb9d473b,
  @ParentID_Clear = 1,
  @IconClass = @IconClass_bd01eb9d473b,
  @DefaultCompactPromptID = @DefaultCompactPromptID_bd01eb9d473b,
  @DefaultCompactPromptID_Clear = 1,
  @Config = @Config_bd01eb9d473b,
  @Config_Clear = 1,
  @RuntimeActionConfiguration = @RuntimeActionConfiguration_bd01eb9d473b,
  @RuntimeActionConfiguration_Clear = 1,
  @MaxExecutionTimeMS = @MaxExecutionTimeMS_bd01eb9d473b,
  @MaxExecutionTimeMS_Clear = 1,
  @CreatedByAgentID = @CreatedByAgentID_bd01eb9d473b,
  @CreatedByAgentID_Clear = 1;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_ada5a4bff9e2 UNIQUEIDENTIFIER,
@ActionID_ada5a4bff9e2 UNIQUEIDENTIFIER,
@Name_ada5a4bff9e2 NVARCHAR(255),
@DefaultValue_ada5a4bff9e2 NVARCHAR(MAX),
@Type_ada5a4bff9e2 NCHAR(10),
@ValueType_ada5a4bff9e2 NVARCHAR(30),
@IsArray_ada5a4bff9e2 BIT,
@Description_ada5a4bff9e2 NVARCHAR(MAX),
@IsRequired_ada5a4bff9e2 BIT,
@MediaModality_ada5a4bff9e2 NVARCHAR(20),
@LogValue_ada5a4bff9e2 BIT
SET
  @ID_ada5a4bff9e2 = '48C2C73D-3DF0-472A-9C94-8CAF6E0CB26D'
SET
  @ActionID_ada5a4bff9e2 = '442E3FEA-1838-42F9-AE34-72BB4E79C833'
SET
  @Name_ada5a4bff9e2 = N'TaskID'
SET
  @Type_ada5a4bff9e2 = N'Input'
SET
  @ValueType_ada5a4bff9e2 = N'Scalar'
SET
  @IsArray_ada5a4bff9e2 = 0
SET
  @Description_ada5a4bff9e2 = N'The approval task whose outcome to apply. Tasks passes it when the task closes.'
SET
  @IsRequired_ada5a4bff9e2 = 1
SET
  @LogValue_ada5a4bff9e2 = 1

SELECT TOP 1 @ActionID_ada5a4bff9e2 = [ID] FROM [${mjSchema}].[Action] WHERE [Name] = N'Apply Access Override Decision' ORDER BY CASE WHEN [ID] = @ActionID_ada5a4bff9e2 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
               WHERE [ID] = @ID_ada5a4bff9e2
                  OR ([ActionID] = @ActionID_ada5a4bff9e2 AND [Name] = @Name_ada5a4bff9e2))
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_ada5a4bff9e2,
  @ActionID = @ActionID_ada5a4bff9e2,
  @Name = @Name_ada5a4bff9e2,
  @DefaultValue = @DefaultValue_ada5a4bff9e2,
  @DefaultValue_Clear = 1,
  @Type = @Type_ada5a4bff9e2,
  @ValueType = @ValueType_ada5a4bff9e2,
  @IsArray = @IsArray_ada5a4bff9e2,
  @Description = @Description_ada5a4bff9e2,
  @IsRequired = @IsRequired_ada5a4bff9e2,
  @MediaModality = @MediaModality_ada5a4bff9e2,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_ada5a4bff9e2;

GO

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
DECLARE @ID_794ce786f46d UNIQUEIDENTIFIER,
@Name_794ce786f46d NVARCHAR(100),
@Description_794ce786f46d NVARCHAR(MAX),
@IconClass_794ce786f46d NVARCHAR(100),
@DefaultPriority_794ce786f46d NVARCHAR(20),
@OnAssignActionID_794ce786f46d UNIQUEIDENTIFIER,
@OnCompleteActionID_794ce786f46d UNIQUEIDENTIFIER,
@OnOverdueActionID_794ce786f46d UNIQUEIDENTIFIER,
@OnPercentChangeActionID_794ce786f46d UNIQUEIDENTIFIER,
@IsActive_794ce786f46d BIT,
@OnRejectActionID_794ce786f46d UNIQUEIDENTIFIER,
@OnCancelActionID_794ce786f46d UNIQUEIDENTIFIER,
@Code_794ce786f46d NVARCHAR(50),
@OnCreateActionID_794ce786f46d UNIQUEIDENTIFIER,
@OnStatusChangeActionID_794ce786f46d UNIQUEIDENTIFIER
SET
  @ID_794ce786f46d = 'B321B638-B3B2-4072-BB2B-053407D1D4DE'
SET
  @Name_794ce786f46d = N'Access Override Approval'
SET
  @Description_794ce786f46d = N'Approve or reject an exception to payment-gated access on an order. Closing the task applies the decision to the override.'
SET
  @IconClass_794ce786f46d = N'fa-solid fa-unlock-keyhole'
SET
  @DefaultPriority_794ce786f46d = N'High'
SET
  @OnCompleteActionID_794ce786f46d = '442E3FEA-1838-42F9-AE34-72BB4E79C833'
SET
  @IsActive_794ce786f46d = 1
SET
  @OnRejectActionID_794ce786f46d = '442E3FEA-1838-42F9-AE34-72BB4E79C833'
SET
  @OnCancelActionID_794ce786f46d = '442E3FEA-1838-42F9-AE34-72BB4E79C833'
SET
  @Code_794ce786f46d = N'ORDERS_ACCESS_OVERRIDE' 
SELECT TOP 1 @OnCompleteActionID_794ce786f46d = [ID] FROM [${mjSchema}].[Action] WHERE [Name] = N'Apply Access Override Decision' ORDER BY CASE WHEN [ID] = @OnCompleteActionID_794ce786f46d THEN 0 ELSE 1 END
SELECT TOP 1 @OnRejectActionID_794ce786f46d = [ID] FROM [${mjSchema}].[Action] WHERE [Name] = N'Apply Access Override Decision' ORDER BY CASE WHEN [ID] = @OnRejectActionID_794ce786f46d THEN 0 ELSE 1 END
SELECT TOP 1 @OnCancelActionID_794ce786f46d = [ID] FROM [${mjSchema}].[Action] WHERE [Name] = N'Apply Access Override Decision' ORDER BY CASE WHEN [ID] = @OnCancelActionID_794ce786f46d THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [__mj_BizAppsTasks].[TaskType]
               WHERE [ID] = @ID_794ce786f46d
                  OR ([Code] = @Code_794ce786f46d)
                  OR ([Name] = @Name_794ce786f46d))
EXEC [__mj_BizAppsTasks].spCreateTaskType @ID = @ID_794ce786f46d,
  @Name = @Name_794ce786f46d,
  @Description = @Description_794ce786f46d,
  @IconClass = @IconClass_794ce786f46d,
  @DefaultPriority = @DefaultPriority_794ce786f46d,
  @OnAssignActionID = @OnAssignActionID_794ce786f46d,
  @OnAssignActionID_Clear = 1,
  @OnCompleteActionID = @OnCompleteActionID_794ce786f46d,
  @OnOverdueActionID = @OnOverdueActionID_794ce786f46d,
  @OnOverdueActionID_Clear = 1,
  @OnPercentChangeActionID = @OnPercentChangeActionID_794ce786f46d,
  @OnPercentChangeActionID_Clear = 1,
  @IsActive = @IsActive_794ce786f46d,
  @OnRejectActionID = @OnRejectActionID_794ce786f46d,
  @OnCancelActionID = @OnCancelActionID_794ce786f46d,
  @Code = @Code_794ce786f46d,
  @OnCreateActionID = @OnCreateActionID_794ce786f46d,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_794ce786f46d,
  @OnStatusChangeActionID_Clear = 1;

GO

-- Save MJ: Authorizations (core SP call only)
DECLARE @ID_c45a5ea4f2a5 UNIQUEIDENTIFIER,
@ParentID_c45a5ea4f2a5 UNIQUEIDENTIFIER,
@Name_c45a5ea4f2a5 NVARCHAR(100),
@IsActive_c45a5ea4f2a5 BIT,
@UseAuditLog_c45a5ea4f2a5 BIT,
@Description_c45a5ea4f2a5 NVARCHAR(MAX)
SET
  @ID_c45a5ea4f2a5 = 'AB81C474-1942-40C9-A05F-90E441C7A7F7'
SET
  @Name_c45a5ea4f2a5 = N'MJ.BizApps.Orders.Access.Override'
SET
  @IsActive_c45a5ea4f2a5 = 1
SET
  @UseAuditLog_c45a5ea4f2a5 = 1
SET
  @Description_c45a5ea4f2a5 = N'Parent grant for requesting exceptions to payment-gated access on an order. Child authorizations are WaivePaymentHold and DeferCutoff, one per override type. Holding the parent grants both. Who may approve a request is decided separately (bizapps-orders#360).' 
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[Authorization]
               WHERE [ID] = @ID_c45a5ea4f2a5
                  OR ([Name] = @Name_c45a5ea4f2a5))
EXEC [${mjSchema}].spCreateAuthorization @ID = @ID_c45a5ea4f2a5,
  @ParentID = @ParentID_c45a5ea4f2a5,
  @ParentID_Clear = 1,
  @Name = @Name_c45a5ea4f2a5,
  @IsActive = @IsActive_c45a5ea4f2a5,
  @UseAuditLog = @UseAuditLog_c45a5ea4f2a5,
  @Description = @Description_c45a5ea4f2a5;

GO

-- Save MJ: Authorizations (core SP call only)
DECLARE @ID_3ea803d29605 UNIQUEIDENTIFIER,
@ParentID_3ea803d29605 UNIQUEIDENTIFIER,
@Name_3ea803d29605 NVARCHAR(100),
@IsActive_3ea803d29605 BIT,
@UseAuditLog_3ea803d29605 BIT,
@Description_3ea803d29605 NVARCHAR(MAX)
SET
  @ID_3ea803d29605 = '2A127B15-E119-478B-8E22-17C2125D68CC'
SET
  @ParentID_3ea803d29605 = 'AB81C474-1942-40C9-A05F-90E441C7A7F7'
SET
  @Name_3ea803d29605 = N'MJ.BizApps.Orders.Access.Override.WaivePaymentHold'
SET
  @IsActive_3ea803d29605 = 1
SET
  @UseAuditLog_3ea803d29605 = 1
SET
  @Description_3ea803d29605 = N'Request a WaivePaymentHold override on an order: its grants held for payment go Active before the payment arrives, through a stated last day. Requires a reason, and takes effect only once approved.' 
SELECT TOP 1 @ParentID_3ea803d29605 = [ID] FROM [${mjSchema}].[Authorization] WHERE [Name] = N'MJ.BizApps.Orders.Access.Override' ORDER BY CASE WHEN [ID] = @ParentID_3ea803d29605 THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[Authorization]
               WHERE [ID] = @ID_3ea803d29605
                  OR ([Name] = @Name_3ea803d29605))
EXEC [${mjSchema}].spCreateAuthorization @ID = @ID_3ea803d29605,
  @ParentID = @ParentID_3ea803d29605,
  @Name = @Name_3ea803d29605,
  @IsActive = @IsActive_3ea803d29605,
  @UseAuditLog = @UseAuditLog_3ea803d29605,
  @Description = @Description_3ea803d29605;

GO

-- Save MJ: Authorizations (core SP call only)
DECLARE @ID_db4166ef56aa UNIQUEIDENTIFIER,
@ParentID_db4166ef56aa UNIQUEIDENTIFIER,
@Name_db4166ef56aa NVARCHAR(100),
@IsActive_db4166ef56aa BIT,
@UseAuditLog_db4166ef56aa BIT,
@Description_db4166ef56aa NVARCHAR(MAX)
SET
  @ID_db4166ef56aa = '4B3E6438-CCAC-4800-A337-7A7E166932B4'
SET
  @ParentID_db4166ef56aa = 'AB81C474-1942-40C9-A05F-90E441C7A7F7'
SET
  @Name_db4166ef56aa = N'MJ.BizApps.Orders.Access.Override.DeferCutoff'
SET
  @IsActive_db4166ef56aa = 1
SET
  @UseAuditLog_db4166ef56aa = 1
SET
  @Description_db4166ef56aa = N'Request a DeferCutoff override on a renewal order: its grants stay Active past the renewal cutoff, through a stated last day. Requires a reason, and takes effect only once approved.' 
SELECT TOP 1 @ParentID_db4166ef56aa = [ID] FROM [${mjSchema}].[Authorization] WHERE [Name] = N'MJ.BizApps.Orders.Access.Override' ORDER BY CASE WHEN [ID] = @ParentID_db4166ef56aa THEN 0 ELSE 1 END
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[Authorization]
               WHERE [ID] = @ID_db4166ef56aa
                  OR ([Name] = @Name_db4166ef56aa))
EXEC [${mjSchema}].spCreateAuthorization @ID = @ID_db4166ef56aa,
  @ParentID = @ParentID_db4166ef56aa,
  @Name = @Name_db4166ef56aa,
  @IsActive = @IsActive_db4166ef56aa,
  @UseAuditLog = @UseAuditLog_db4166ef56aa,
  @Description = @Description_db4166ef56aa;

GO

-- Save MJ: Entity Relationships (core SP call only)
DECLARE @EntityID_431a850d8f8b UNIQUEIDENTIFIER,
@Sequence_431a850d8f8b INT,
@RelatedEntityID_431a850d8f8b UNIQUEIDENTIFIER,
@BundleInAPI_431a850d8f8b BIT,
@IncludeInParentAllQuery_431a850d8f8b BIT,
@Type_431a850d8f8b NCHAR(20),
@EntityKeyField_431a850d8f8b NVARCHAR(255),
@RelatedEntityJoinField_431a850d8f8b NVARCHAR(255),
@JoinView_431a850d8f8b NVARCHAR(255),
@JoinEntityJoinField_431a850d8f8b NVARCHAR(255),
@JoinEntityInverseJoinField_431a850d8f8b NVARCHAR(255),
@DisplayInForm_431a850d8f8b BIT,
@DisplayLocation_431a850d8f8b NVARCHAR(50),
@DisplayName_431a850d8f8b NVARCHAR(255),
@DisplayIconType_431a850d8f8b NVARCHAR(50),
@DisplayIcon_431a850d8f8b NVARCHAR(255),
@DisplayComponentID_431a850d8f8b UNIQUEIDENTIFIER,
@DisplayComponentConfiguration_431a850d8f8b NVARCHAR(MAX),
@AutoUpdateFromSchema_431a850d8f8b BIT,
@AdditionalFieldsToInclude_431a850d8f8b NVARCHAR(MAX),
@AutoUpdateAdditionalFieldsToInclude_431a850d8f8b BIT,
@RelatedRecordCollection_431a850d8f8b NVARCHAR(MAX),
@Configuration_431a850d8f8b NVARCHAR(MAX),
@ID_431a850d8f8b UNIQUEIDENTIFIER
SET
  @EntityID_431a850d8f8b = 'FC529BC8-FF09-44A9-B454-26EAFDAC791B'
SET
  @Sequence_431a850d8f8b = 12
SET
  @RelatedEntityID_431a850d8f8b = '2719A581-1FE7-4728-9649-5B95175AE1F9'
SET
  @BundleInAPI_431a850d8f8b = 1
SET
  @IncludeInParentAllQuery_431a850d8f8b = 0
SET
  @Type_431a850d8f8b = N'One To Many'
SET
  @RelatedEntityJoinField_431a850d8f8b = N'OrderHeaderID'
SET
  @DisplayInForm_431a850d8f8b = 1
SET
  @DisplayLocation_431a850d8f8b = N'After Field Tabs'
SET
  @DisplayIconType_431a850d8f8b = N'Related Entity Icon'
SET
  @AutoUpdateFromSchema_431a850d8f8b = 1
SET
  @AutoUpdateAdditionalFieldsToInclude_431a850d8f8b = 1
SET
  @RelatedRecordCollection_431a850d8f8b = N'{"Name":"CheckoutAnswers","Source":"database","Load":"explicit","OnRemove":"delete","OrderBy":"QuestionKey ASC","ClearAfterSave":false}'
SET
  @ID_431a850d8f8b = '7006E6C1-5258-45DD-BB43-22DF9EB79809' EXEC [${mjSchema}].spUpdateEntityRelationship @EntityID = @EntityID_431a850d8f8b,
  @Sequence = @Sequence_431a850d8f8b,
  @RelatedEntityID = @RelatedEntityID_431a850d8f8b,
  @BundleInAPI = @BundleInAPI_431a850d8f8b,
  @IncludeInParentAllQuery = @IncludeInParentAllQuery_431a850d8f8b,
  @Type = @Type_431a850d8f8b,
  @EntityKeyField = @EntityKeyField_431a850d8f8b,
  @EntityKeyField_Clear = 1,
  @RelatedEntityJoinField = @RelatedEntityJoinField_431a850d8f8b,
  @JoinView = @JoinView_431a850d8f8b,
  @JoinView_Clear = 1,
  @JoinEntityJoinField = @JoinEntityJoinField_431a850d8f8b,
  @JoinEntityJoinField_Clear = 1,
  @JoinEntityInverseJoinField = @JoinEntityInverseJoinField_431a850d8f8b,
  @JoinEntityInverseJoinField_Clear = 1,
  @DisplayInForm = @DisplayInForm_431a850d8f8b,
  @DisplayLocation = @DisplayLocation_431a850d8f8b,
  @DisplayName = @DisplayName_431a850d8f8b,
  @DisplayName_Clear = 1,
  @DisplayIconType = @DisplayIconType_431a850d8f8b,
  @DisplayIcon = @DisplayIcon_431a850d8f8b,
  @DisplayIcon_Clear = 1,
  @DisplayComponentID = @DisplayComponentID_431a850d8f8b,
  @DisplayComponentID_Clear = 1,
  @DisplayComponentConfiguration = @DisplayComponentConfiguration_431a850d8f8b,
  @DisplayComponentConfiguration_Clear = 1,
  @AutoUpdateFromSchema = @AutoUpdateFromSchema_431a850d8f8b,
  @AdditionalFieldsToInclude = @AdditionalFieldsToInclude_431a850d8f8b,
  @AdditionalFieldsToInclude_Clear = 1,
  @AutoUpdateAdditionalFieldsToInclude = @AutoUpdateAdditionalFieldsToInclude_431a850d8f8b,
  @RelatedRecordCollection = @RelatedRecordCollection_431a850d8f8b,
  @Configuration = @Configuration_431a850d8f8b,
  @Configuration_Clear = 1,
  @ID = @ID_431a850d8f8b;

GO


-- End of SQL Logging Session
-- Session ID: a1b172dc-c729-411f-b114-264f5ac8e6a9
-- Completed: 2026-09-30T19:18:06.355Z
-- Duration: 15540ms
-- Total Statements: 15
