/**
 * MJDEV-MANAGED — do not hand-edit (regenerated by `mjdev app gui-test sync`).
 *
 * TIER 4 bootstrap — the REAL production data path: component → real GraphQL client → running
 * MJAPI → DB. Drives `setupGraphQLClient` (the SAME client the browser uses) with an `mj_sk_*` key.
 * Port is discovered from `mjdev ps`; the key is minted via `mjdev key` at runtime.
 */
import { execSync } from 'node:child_process';
import {
  setupGraphQLClient,
  GraphQLProviderConfigData,
} from '@memberjunction/graphql-dataprovider';

// Register @RegisterClass entity subclasses so RunView/GetEntityObject resolve rows to their
// generated subclasses. We ride the SAME generated manifest the real client (MJExplorer) imports —
// `@memberjunction/ng-bootstrap-lite`'s CLASS_REGISTRATIONS references every @RegisterClass class in
// the MJ dep tree, so the COMPLETE set is registered (core + AI + every @RegisterForStartup engine's
// entity subclasses). This matters because `setupGraphQLClient` runs `StartupManager.Startup()`, which
// fires the full server startup engine sequence; a partial registration (e.g. only core-entities)
// leaves an engine like AIEngineBase resolving `MJAIPromptCategoryEntity` (no `Prompts` getter) → a
// `.push` on undefined deep in its Load. Importing the manifest keeps us complete-by-construction as
// MJ adds entities, instead of hand-maintaining a package list. `void .length` references the const so
// AOT/tree-shaking cannot drop the side-effect import (same guard MJExplorer relies on).
import { CLASS_REGISTRATIONS } from '@memberjunction/ng-bootstrap-lite';
void CLASS_REGISTRATIONS.length;
import './tier4.app-entities'; // the app's own generated entity subclasses (per-app)

const LAUNCHER = process.env.MJDEV_BIN ?? '/Users/marcelotorres/MJDev/bin/mjdev';
const SLUG = process.env.MJDEV_SLUG ?? 'accounting-engine-dev';

let bootstrapped = false;
let keepAliveDisabled = false;

/**
 * ECONNRESET hardening. `graphql-request` uses the process's global `fetch` (undici), which pools
 * and keeps HTTP connections alive by default. A kept-alive socket to MJAPI can be closed by the
 * server while idle — e.g. during slow test setup between this bootstrap and the first query — and
 * then reused, surfacing as `ECONNRESET` on the first real request (NOT a subprocess-ordering issue:
 * the socket simply went stale). We turn connection reuse off for the harness process so every
 * request opens a fresh connection — nothing to go stale. Best-effort: undici ships with Node but is
 * not always a resolvable bare import, so we no-op if it's absent (then bootstrap right before use).
 */
async function disableHttpKeepAlive(): Promise<void> {
  if (keepAliveDisabled) return;
  keepAliveDisabled = true;
  try {
    const undici = (await import('undici')) as {
      setGlobalDispatcher: (d: unknown) => void;
      Agent: new (opts: Record<string, unknown>) => unknown;
    };
    // keepAliveTimeout ~1ms → idle sockets close almost immediately, so no request ever reuses a
    // socket the server may have already dropped. Localhost cost of a fresh connection is negligible.
    undici.setGlobalDispatcher(
      new undici.Agent({ pipelining: 0, keepAliveTimeout: 1, keepAliveMaxTimeout: 1 })
    );
  } catch {
    // undici not resolvable in this app — fall back to the "bootstrap late" guidance in README.md.
  }
}

/** Boot the real GraphQL client against the running MJAPI. Idempotent. */
export async function bootstrapTier4(): Promise<{ url: string }> {
  const ps = JSON.parse(execSync(`${LAUNCHER} ps ${SLUG} --json`).toString());
  const api = (ps.processes ?? []).find(
    (p: { label?: string; status?: string; port?: number }) =>
      p.label === 'MJAPI' && p.status === 'running'
  );
  if (!api?.port) {
    throw new Error(
      `Tier 4: MJAPI not running for '${SLUG}'. Start it with 'mjdev run ${SLUG} api' and wait for ready.`
    );
  }
  const url = `http://localhost:${api.port}`;
  if (bootstrapped) return { url };

  await disableHttpKeepAlive(); // must run before the first fetch the GraphQL client makes

  const userAPIKey = execSync(`${LAUNCHER} key ${SLUG}`).toString().trim();
  // WSURL points at the REAL running MJAPI WebSocket endpoint — the SAME value MJExplorer uses
  // (`GRAPHQL_WS_URI = ws://localhost:<apiPort>/` in its generated environment.ts). Parity, not a
  // blank: a blank WSURL made a `BaseFormComponent`-derived entity form's record-change graphql-ws
  // subscription do `new WebSocket('')` → `SyntaxError: The URL '' is invalid.` and crash the render.
  // With the real URL the subscription connects to MJAPI exactly as production does (validated:
  // socketState=connected, clean process exit) — no divergence, no WebSocket stub. (See ADR-033.)
  const wsurl = `ws://localhost:${api.port}/`;
  const config = new GraphQLProviderConfigData(
    '', // token — unused (authenticating via the user API key)
    url,
    wsurl, // REAL MJAPI WS endpoint (parity with MJExplorer's GRAPHQL_WS_URI)
    async () => '', // refreshTokenFunction — no-op (API key doesn't expire like a JWT)
    '__mj', // MJCoreSchemaName — MJ's core-schema default (matches env MJ_CORE_SCHEMA_NAME)
    undefined, // includeSchemas
    undefined, // excludeSchemas
    undefined, // mjAPIKey (system key) — not this
    userAPIKey // userAPIKey (mj_sk_*)
  );
  await setupGraphQLClient(config);
  bootstrapped = true;
  return { url };
}
