/**
 * MJDEV-MANAGED — do not hand-edit (regenerated by `mjdev app gui-test sync`).
 * TIER 4 vitest config — jsdom + @analogjs/vite-plugin-angular (jit:false AOT).
 * Run from the Angular package root: `npx vitest run --config test-harnesses/gui/vitest.gui.config.ts`
 */
import { defineConfig } from 'vitest/config';
import angular from '@analogjs/vite-plugin-angular';
import { fileURLToPath } from 'node:url';

const setupFile = fileURLToPath(new URL('./tier4-dom.setup.ts', import.meta.url));

export default defineConfig({
  plugins: [angular({ jit: false, tsconfig: './test-harnesses/gui/tsconfig.gui.json' })],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: [setupFile],
    include: ['test-harnesses/gui/**/*.dom.test.ts'],
    testTimeout: 60000,
    hookTimeout: 180000,
    fileParallelism: false,
    pool: 'forks',
    passWithNoTests: false,
    server: {
      deps: {
        external: [
          /@memberjunction\//,
          /@mj-biz-apps\//,
          /graphql-ws/,
          /graphql-request/,
          /ag-grid/,
        ],
      },
    },
  },
});
